In [1]:
import numpy as np
import pandas as pd
import json
import os
import tarfile
import csv

In [2]:
os.walk('C:/Users/Louisa Zhao/Desktop/CORD/1/biorxiv_medrxiv.tar')

Convert to DF and Text preprocessing

In [3]:
df_cord_meta = pd.read_csv("C:/Users/Louisa Zhao/Desktop/CORD/3/metadata.csv",sep=",",header=0)

In [4]:
df_cord_meta.head()

,sha,source_x,title,doi,pmcid,pubmed_id,license,abstract,publish_time,authors,journal,Microsoft Academic Paper ID,WHO #Covidence,has_full_text,full_text_file
0,NaN,Elsevier,Intrauterine virus infections and congenital h...,10.1016/0002-8703(72)90077-4,NaN,4361535.0,els-covid,Abstract The etiologic basis for the vast majo...,1972-12-31,"Overall, James C.",American Heart Journal,NaN,NaN,False,custom_license
1,NaN,Elsevier,Coronaviruses in Balkan nephritis,10.1016/0002-8703(80)90355-5,NaN,6243850.0,els-covid,NaN,1980-03-31,"Georgescu, Leonida; Diosi, Peter; Buţiu, Ioan;...",American Heart Journal,NaN,NaN,False,custom_license
2,NaN,Elsevier,Cigarette smoking and coronary heart disease: ...,10.1016/0002-8703(80)90356-7,NaN,7355701.0,els-covid,NaN,1980-03-31,"Friedman, Gary D",American Heart Journal,NaN,NaN,False,custom_license
3,aecbc613ebdab36753235197ffb4f35734b5ca63,Elsevier,Clinical and immunologic studies in identical ...,10.1016/0002-9343(73)90176-9,NaN,4579077.0,els-covid,"Abstract Middle-aged female identical twins, o...",1973-08-31,"Brunner, Carolyn M.; Horwitz, David A.; Shann,...",The American Journal of Medicine,NaN,NaN,True,custom_license
4,NaN,Elsevier,Epidemiology of community-acquired respiratory...,10.1016/0002-9343(85)90361-4,NaN,4014285.0,els-covid,Abstract Upper respiratory tract infections ar...,1985-06-28,"Garibaldi, Richard A.",The American Journal of Medicine,NaN,NaN,False,custom_license

In [5]:
df_cord_meta['title'] = df_cord_meta['title'].fillna('')
df_cord_meta['abstract'] = df_cord_meta['abstract'].fillna('')
df_cord_meta['title_abstract'] = df_cord_meta.title + " " + df_cord_meta.abstract
df_cord_meta.head()

,sha,source_x,title,doi,pmcid,pubmed_id,license,abstract,publish_time,authors,journal,Microsoft Academic Paper ID,WHO #Covidence,has_full_text,full_text_file,title_abstract
0,NaN,Elsevier,Intrauterine virus infections and congenital h...,10.1016/0002-8703(72)90077-4,NaN,4361535.0,els-covid,Abstract The etiologic basis for the vast majo...,1972-12-31,"Overall, James C.",American Heart Journal,NaN,NaN,False,custom_license,Intrauterine virus infections and congenital h...
1,NaN,Elsevier,Coronaviruses in Balkan nephritis,10.1016/0002-8703(80)90355-5,NaN,6243850.0,els-covid,,1980-03-31,"Georgescu, Leonida; Diosi, Peter; Buţiu, Ioan;...",American Heart Journal,NaN,NaN,False,custom_license,Coronaviruses in Balkan nephritis
2,NaN,Elsevier,Cigarette smoking and coronary heart disease: ...,10.1016/0002-8703(80)90356-7,NaN,7355701.0,els-covid,,1980-03-31,"Friedman, Gary D",American Heart Journal,NaN,NaN,False,custom_license,Cigarette smoking and coronary heart disease: ...
3,aecbc613ebdab36753235197ffb4f35734b5ca63,Elsevier,Clinical and immunologic studies in identical ...,10.1016/0002-9343(73)90176-9,NaN,4579077.0,els-covid,"Abstract Middle-aged female identical twins, o...",1973-08-31,"Brunner, Carolyn M.; Horwitz, David A.; Shann,...",The American Journal of Medicine,NaN,NaN,True,custom_license,Clinical and immunologic studies in identical ...
4,NaN,Elsevier,Epidemiology of community-acquired respiratory...,10.1016/0002-9343(85)90361-4,NaN,4014285.0,els-covid,Abstract Upper respiratory tract infections ar...,1985-06-28,"Garibaldi, Richard A.",The American Journal of Medicine,NaN,NaN,False,custom_license,Epidemiology of community-acquired respiratory...

In [6]:
texts = df_cord_meta[(pd.notnull(df_cord_meta['title_abstract']))].title_abstract.tolist()
texts[0]

'Intrauterine virus infections and congenital heart disease Abstract The etiologic basis for the vast majority of cases of congenital heart disease remains largely undefined. Viruses have been considered to be likely candidates since the recognition of the association between intrauterine rubella and congenital heart disease. Although the pathogenesis of cardiovascular defects is poorly understood, information gained from the study of congenital rubella syndrome suggests that mechanisms such as focal endothelial cell damage, resulting in obliteration of vascular supply, decreased growth rate, and shortened survival time of certain cells, and disturbed DNA replication in cells whose chromosomes were damaged secondary to the effects of virus replication may be operative in the production of defects in the developing fetus. In addition to rubella there is suggestive, but not conclusive, evidence that Coxsackie B3 and B4 virus infections during pregnancy can result in the birth of infants with a variety of types of congenital heart lesions and that intrauterine mumps virus infection may be etiologically related to the postnatal development of endocardial fibroelastosis (EFE). Although there are a number of other viruses that are potential etiologic agents of congenital heart disease, the current status of information is inadequate to allow even suggestive associations to be made. The most profitable areas for future investigation appear to be: (1) the epidemiology of congenital heart disease, (2) prospective studies of the association of maternal viral infection with abnormal offspring, (3) the in-depth virologic investigation of the infant with a cardiac defect, and (4) the development of experimental animal models of congenital heart disease. Successful control of virus-induced congenital heart disease will depend on the results of these investigations and the development of vaccines against the identified causative viruses and/or safe and effective antiviral chemotherapy for the woman in early gestation who is infected with a known teratogenic agent.'

In [7]:
#Special module written for this class
#This provides access to data and to helper functions from previous weeks
#Make sure you update it before starting this notebook
import lucem_illud #pip install -U git+git://github.com/UChicago-Computational-Content-Analysis/lucem_illud.git


#All these packages need to be installed from pip
#These are all for the cluster detection
import sklearn
import sklearn.feature_extraction.text
import sklearn.pipeline
import sklearn.preprocessing
import sklearn.datasets
import sklearn.cluster
import sklearn.decomposition
import sklearn.metrics

import scipy #For hierarchical clustering and some visuals
#import scipy.cluster.hierarchy
import gensim#For topic modeling
import requests #For downloading our datasets
import numpy as np #for arrays
import pandas #gives us DataFrames
import matplotlib.pyplot as plt #For graphics
import matplotlib.cm #Still for graphics
import seaborn as sns #Makes the graphics look nicer

%matplotlib inline

import itertools
import json

In [8]:
import networkx as nx

import sklearn #For generating some matrices
import pandas #For DataFrames
import numpy as np #For arrays
import matplotlib.pyplot as plt #For plotting
import seaborn #Makes the plots look nice
import scipy #Some stats
import nltk #a little language code
from IPython.display import Image #for pics

import pickle #if you want to save layouts
import os

In [9]:
import gensim, sklearn
import spacy
import sys
sys.path.append(r'C:\Users\Louisa Zhao\anaconda3\Lib\site-packages')
sys.path.append(r'C:\Users\Louisa Zhao\anaconda3\Lib\site-packages\en_core_sci_sm')
import scispacy #the package for biomedical and clinical text processing

In [10]:
nlp = spacy.load(r'C:\Users\Louisa Zhao\anaconda3\Lib\site-packages\en_core_sci_md-0.4.0\en_core_sci_md\en_core_sci_md-0.4.0') # loading biomedical text processing package

C:\Users\Louisa Zhao\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\util.py:275: UserWarning: [W031] Model 'en_core_sci_md' (0.4.0) requires spaCy v3.0 and is incompatible with the current spaCy version (2.3.5). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)

In [11]:
import pickle

In [ ]:
%%time

processed_docs = list()
num = 0
for doc in nlp.pipe(texts[:10],n_process=6,batch_size = 100):
    ents = doc.ents # name entities
    
    # Lemmatize token, remove punctutation and stopwords
    doc = [token.lemma_ for token in doc if not token.is_punct and not token.is_stop]
    
    doc.extend([str(entity) for entity in ents if len(entity) > 1])
    processed_docs.append(doc)
    print(num+1)

pickle.dump(processed_docs, open("datasets_output/texts/processed_docs_cord19_scispacy.pk", "wb"))