In [1]:
import pandas as pd

text_march = pd.read_csv(r'C:\Users\Louisa Zhao\Desktop\CORD\3\word-lem.txt', delimiter = "\t")
text_march_network = pd.read_csv(r'C:\Users\Louisa Zhao\Desktop\CORD\3\network-term-lem.txt', delimiter = "\t",header = None)

text_jan = pd.read_csv(r'C:\Users\Louisa Zhao\Desktop\CORD\11\word.txt', delimiter = "\t")
text_jan_network = pd.read_csv(r'C:\Users\Louisa Zhao\Desktop\CORD\11\network word.txt', delimiter = "\t",header = None)

In [2]:
text_march_network.to_csv(r"C:\Users\Louisa Zhao\Desktop\CORD\3\node_march.csv")

In [3]:
pd.read_csv(r"C:\Users\Louisa Zhao\Desktop\CORD\3\node_march.csv")

         Unnamed: 0     0     1   2
0                 0     1     5   1
1                 1     1    40   2
2                 2     1   102   1
3                 3     1   124   1
4                 4     1   136   1
...             ...   ...   ...  ..
1427536     1427536  5983  5994   2
1427537     1427537  5987  5988   6
1427538     1427538  5989  5990   1
1427539     1427539  5990  5993   2
1427540     1427540  5993  5995  14

[1427541 rows x 4 columns]

In [4]:
target_word = text_march['label'][4836]
target_word

'rt pcr'

In [5]:
text_march_network[text_march_network[0].isin([4387])][1]

1314770    4390
1314771    4391
1314772    4394
1314773    4395
1314774    4400
           ...
1315117    5960
1315118    5965
1315119    5978
1315120    5983
1315121    5994
Name: 1, Length: 352, dtype: int64

In [6]:
for i in text_march_network[text_march_network[0].isin([4387])][1]:
    target_word = text_march['label'][i-1]
    print(target_word)

protein function
protein gene
protein kinase
protein kinase c
protein protein interaction
protein sar
protein severe acute respiratory syndrome coronavirus
protein spot
protein structure
protein synthesis
proteolytic processing
proteomic analysis
prrsv
prrsv infection
ptb
pulmonary inflammation
purification
pvx
qtl
quality
quantitative proteomic
quasispecy
quercetin
radix
rdrp
reactive oxygen species
reading frame
real time pcr
reality
receptor
receptor antagonist
receptor binding
receptor binding site
receptor interaction
recombinant
recombinant protein
recombinant vesicular stomatitis virus
recombinant virus
recombination
reference strain
regulated protein
regulator
regulatory factor
related protein
release
renilla luciferase
renin
renin angiotensin system
reovirus
repeat
replicase
replicase gene
replicase polyprotein
replicate
replication
replication complex
replication cycle
replication pathogenesis
replication transcription
replication virus
replication vitro
replicon
reporter
reporter gene
residue
resource
respiratory pathogen
respiratory syncytial virus
respiratory syndrome
respiratory syndrome coronavirus
respiratory syndrome coronavirus infection
respiratory virus infection
response infection
response viral infection
resveratrol
retinoic acid inducible gene
retrovirus
reverse transcriptase polymerase chain reaction
reverse transcription pcr
reverse transcription polymerase chain reaction
rheumatoid arthritis
rhinovirus
rhinovirus infection
ribosomal frameshifting
rice
rift valley fever virus
rig i
risk factor
rna
rna binding protein
rna genome
rna interference
rna level
rna molecule
rna polymerase
rna processing
rna recombination
rna replication
rna seq
rna structure
rna synthesis
rna transcript
rna virus
rnai
rnp
rsv
rsv infection
rvfv
s1 protein
s1 s2
sample preparation
sample size
sars cov infection
scale
scfv
sci
score
scov
secretory pathway
section
segment
sequence
sequence element
ser
serine
serine protease
severe acute respiratory syndrome cov
sg formation
sgmrna
sham
short hairpin rna
short interfering rna
shrna
signal
signal transduction
signal transduction pathway
signaling
signaling pathway
signalling
silencing
simian immunodeficiency virus
simplex virus
simplex virus type
sin
sinensis
single chain variable fragment
sirna
size exclusion chromatography
small interfering rna
small intestine
small molecule inhibitor
soc
solubility
specific immune response
specific inhibitor
specific manner
specific mutation
specific sirna
specimen
spectroscopy
spike
spike protein
spring
sputum
stable cell line
stage infection
starvation
stat
stat1
stem cell
steroid
stimulation
stimulator
strand rna
stress granule
stress response
structural characterization
structural gene
structural protein
structural study
structure
structure function
study design
subgenomic mrna
subject
substitution
substrate
subunit
subunit vaccine
suggestion
superfamily
supernatant
supplementation
suppress
suppression
suppressor
surface expression
swine industry
symptom
syncytium formation
synthase
synthesis
t cell
t cell response
t helper
tannin
target gene
tbp
terminal
terminal domain
terminal kinase
terminal region
termini
tgev infection
tgf
tgn
theme
thing
tim
time dependent manner
time flight mass spectrometry
tissue culture
title
tlr2
tlr7
tmprss2
tnf alpha
toc
tomography
top
torovirus
trade
traf3
trafficking
trainee
trans golgi network
transcriptase
transcription factor
transcription loop
transcriptional activity
transcriptional level
transcriptional regulation
transfected cell
transfection
transferase
transgenic plant
translation initiation
translation initiation factor
translational frameshifting
transmembrane
transmembrane domain
transmembrane segment
transmission disease
trauma
travel
treg
treg cell
triage
trial background
tropical disease
trss
truncation
tubule
tumor cell
tumor growth
tumor necrosis factor alpha
tumorigenesis
tumour necrosis factor
type i interferon
type ii
type ii transmembrane serine protease
type iii
ubiquitin proteasome system
ubiquitination
ubl
umrah
unigene
uninfected control
unique feature
urban area
usage pattern
vaccine design
vaccinee
vaccinology
variant virus
varicella zoster virus
vero cell
vesicular stomatitis virus
vesicular stomatitis virus glycoprotein
victim
viral attachment
viral entry host cell
viral family
viral genome replication
viral growth
viral membrane
viral metagenomic
viral particle
viral propagation
viral protein
viral protein expression
viral protein synthesis
viral replication complex
viral respiratory infection
viral rna dependent rna polymerase
viral rna replication
viral spike
viral transcription
virale
virion assembly
virol
virome
virtual screening
virus control
virus entry cell
virus evolution
virus glycoprotein
virus infected cell
virus infectivity
virus neutralization
virus pathogenesis
virus persistence
virus receptor
virus replication
virus respiratoire
virus vector
virus viability
viruses bacterium
visceral leishmaniasis
vitro activity
vitro result
vivo
vivo study
vol
vre
vsv g
web science
western blot analysis
western blot assay
western blotting
western country
white blood cell count
wild type level
wild type protein
wild type virus
wildlife
workforce
x ray structure
year age
yellow fever virus
younger age
zoonotic disease

# Network of March Data

In [31]:
import networkx as nx
import sklearn #For generating some matrices
import pandas #For DataFrames
import numpy as np #For arrays
import matplotlib.pyplot as plt #For plotting
import seaborn #Makes the plots look nice

In [32]:
g = nx.Graph()

In [33]:
node_1 = text_march_network[0]

In [34]:
node_list1 = [i for i in text_march_network[0]]
node_list2 = [i for i in text_march_network[1]]

In [35]:
len(node_list1)

1427541

In [36]:
node = (node_list1,node_list2)

In [37]:
for i in range(len(node_list1)):
    g.add_node(node_list1[i])
    g.add_node(node_list2[i])
    g.add_edge(node_list1[i],node_list2[i])

In [38]:
len(g.nodes)

5995

In [39]:
len(g.edges)

1427541

In [40]:
print(nx.info(g))

Name:
Type: Graph
Number of nodes: 5995
Number of edges: 1427541
Average degree: 476.2439

In [41]:
dcentralities = nx.degree_centrality(g)
sorted(dcentralities.items(), reverse = True, key = lambda x:x[1])

[(712, 0.8238238238238239),
 (3965, 0.8124791458124792),
 (5965, 0.8003003003003003),
 (641, 0.792625959292626),
 (4383, 0.7912912912912913),
 (4686, 0.67334000667334),
 (40, 0.6661661661661662),
 (1834, 0.6519853186519854),
 (4966, 0.6376376376376377),
 (3846, 0.6284617951284618),
 (5273, 0.6151151151151152),
 (3455, 0.6094427761094428),
 (4688, 0.5999332665999333),
 (3963, 0.5949282615949283),
 (5361, 0.5944277610944277),
 (4551, 0.589255922589256),
 (845, 0.5857524190857525),
 (147, 0.5812479145812479),
 (5867, 0.5799132465799133),
 (1146, 0.5745745745745746),
 (1912, 0.5635635635635636),
 (4785, 0.5590590590590591),
 (832, 0.5497163830497164),
 (3533, 0.5393727060393727),
 (3995, 0.5363697030363698),
 (4628, 0.5308641975308642),
 (3441, 0.5305305305305306),
 (3291, 0.53003003003003),
 (3855, 0.5296963630296964),
 (1409, 0.5285285285285286),
 (2837, 0.5215215215215215),
 (2054, 0.5201868535201869),
 (1502, 0.5180180180180181),
 (2586, 0.5176843510176844),
 (4143, 0.5173506840173507),
 (3431, 0.51001001001001),
 (1029, 0.503003003003003),
 (4771, 0.5001668335001669),
 (2805, 0.49466132799466134),
 (3295, 0.49115782449115786),
 (2398, 0.49049049049049054),
 (4039, 0.4893226559893227),
 (5591, 0.4858191524858192),
 (1008, 0.4826493159826493),
 (2240, 0.478978978978979),
 (3357, 0.4774774774774775),
 (2566, 0.4771438104771438),
 (2768, 0.4758091424758092),
 (3278, 0.47564230897564236),
 (736, 0.4491157824491158),
 (5384, 0.44477811144477813),
 (4837, 0.44127460794127465),
 (4684, 0.438938938938939),
 (4696, 0.43843843843843844),
 (3241, 0.43493493493493496),
 (4027, 0.43360026693360026),
 (5788, 0.4252585919252586),
 (62, 0.42442442442442446),
 (124, 0.4239239239239239),
 (4095, 0.41491491491491495),
 (3435, 0.4117450784117451),
 (4351, 0.40940940940940945),
 (5527, 0.4087420754087421),
 (2686, 0.4072405739072406),
 (1078, 0.40690690690690695),
 (5041, 0.40540540540540543),
 (4911, 0.4045712379045713),
 (2189, 0.4037370704037371),
 (1048, 0.40357023690357025),
 (3190, 0.4032365699032366),
 (4660, 0.4032365699032366),
 (4832, 0.40190190190190195),
 (3077, 0.4012345679012346),
 (1320, 0.39372706039372707),
 (5163, 0.39356022689356024),
 (1724, 0.3907240573907241),
 (5294, 0.38621955288621956),
 (1973, 0.3857190523857191),
 (4808, 0.3852185518852186),
 (2109, 0.38421755088421755),
 (470, 0.3840507173840507),
 (1252, 0.38355021688355023),
 (3706, 0.38221554888221554),
 (2767, 0.3808808808808809),
 (5850, 0.38071404738071407),
 (5373, 0.37971304637971304),
 (1035, 0.37871204537871206),
 (3155, 0.37754421087754425),
 (1703, 0.3760427093760427),
 (110, 0.3758758758758759),
 (4207, 0.3738738738738739),
 (4175, 0.37370704037370706),
 (3265, 0.3727060393727061),
 (5341, 0.3710377043710377),
 (2409, 0.36970303636970303),
 (2887, 0.3695362028695362),
 (1751, 0.3640306973640307),
 (2817, 0.3603603603603604),
 (4300, 0.35919252585919254),
 (4674, 0.3580246913580247),
 (1034, 0.3570236903570237),
 (4777, 0.35685685685685686),
 (672, 0.35685685685685686),
 (1055, 0.35618952285618954),
 (2894, 0.3528528528528529),
 (4752, 0.3525191858525192),
 (781, 0.35235235235235235),
 (5783, 0.3521855188521855),
 (4664, 0.3515181848515182),
 (1427, 0.3515181848515182),
 (3203, 0.3505171838505172),
 (2668, 0.349683016349683),
 (5793, 0.3495161828495162),
 (4303, 0.34818151484818155),
 (3469, 0.3478478478478479),
 (3529, 0.34684684684684686),
 (5932, 0.3458458458458459),
 (5807, 0.3445111778445112),
 (4268, 0.3420086753420087),
 (5337, 0.34184184184184185),
 (4369, 0.3385051718385052),
 (3931, 0.33783783783783783),
 (2035, 0.3370036703370037),
 (328, 0.33683683683683685),
 (3454, 0.33683683683683685),
 (5303, 0.3353353353353353),
 (1617, 0.3351685018351685),
 (2637, 0.3341675008341675),
 (5013, 0.3314981648314982),
 (633, 0.32999666332999666),
 (2372, 0.327660994327661),
 (3336, 0.32665999332666),
 (4445, 0.32632632632632635),
 (1174, 0.3259926593259927),
 (2676, 0.32582582582582587),
 (549, 0.3253253253253253),
 (1978, 0.32198865532198867),
 (2917, 0.31931931931931934),
 (283, 0.3178178178178178),
 (1755, 0.3178178178178178),
 (887, 0.31431431431431434),
 (3084, 0.31381381381381385),
 (1535, 0.31381381381381385),
 (4668, 0.31314647981314647),
 (1700, 0.3123123123123123),
 (1139, 0.3114781448114782),
 (5167, 0.31131131131131135),
 (469, 0.31064397731064397),
 (478, 0.31064397731064397),
 (4604, 0.3098098098098098),
 (2177, 0.30930930930930933),
 (5589, 0.3089756423089757),
 (3822, 0.30847514180847513),
 (232, 0.30747414080747415),
 (4080, 0.30747414080747415),
 (3180, 0.30747414080747415),
 (4896, 0.30547213880547214),
 (1990, 0.3051384718051385),
 (258, 0.30447113780447116),
 (5090, 0.3021354688021355),
 (5466, 0.3001334668001335),
 (3911, 0.29896563229896567),
 (5523, 0.2942942942942943),
 (2003, 0.2932932932932933),
 (3791, 0.29062395729062396),
 (586, 0.2884551217884551),
 (1152, 0.2879546212879546),
 (3826, 0.28745412078745414),
 (2947, 0.2872872872872873),
 (2406, 0.2872872872872873),
 (5954, 0.2867867867867868),
 (3189, 0.2854521187854521),
 (3146, 0.2852852852852853),
 (4557, 0.28311644978311645),
 (1340, 0.28311644978311645),
 (4919, 0.2829496162829496),
 (2536, 0.28261594928261596),
 (4818, 0.2822822822822823),
 (2323, 0.2817817817817818),
 (2233, 0.28128128128128127),
 (5763, 0.28111444778111444),
 (20, 0.2804471137804471),
 (387, 0.28011344678011346),
 (3691, 0.28011344678011346),
 (5501, 0.2797797797797798),
 (754, 0.279612946279613),
 (4502, 0.2791124457791125),
 (1825, 0.2782782782782783),
 (4942, 0.2782782782782783),
 (784, 0.27811144477811145),
 (4167, 0.27811144477811145),
 (3459, 0.2779446112779446),
 (971, 0.27694361027694364),
 (2609, 0.2764431097764431),
 (117, 0.2759426092759426),
 (4676, 0.2747747747747748),
 (2963, 0.27460794127460797),
 (1985, 0.2742742742742743),
 (5707, 0.2742742742742743),
 (5229, 0.2739406072739406),
 (3633, 0.2724391057724391),
 (2734, 0.2717717717717718),
 (4491, 0.2704371037704371),
 (3835, 0.26960293626960297),
 (4015, 0.26960293626960297),
 (327, 0.2692692692692693),
 (148, 0.2689356022689356),
 (1710, 0.26876876876876876),
 (4423, 0.26876876876876876),
 (4673, 0.2682682682682683),
 (4098, 0.2679346012679346),
 (3053, 0.2674341007674341),
 (4360, 0.2664330997664331),
 (1906, 0.2659325992659326),
 (2631, 0.26559893226559894),
 (825, 0.26559893226559894),
 (5546, 0.26459793126459796),
 (3100, 0.26459793126459796),
 (1793, 0.2642642642642643),
 (5497, 0.2642642642642643),
 (4536, 0.2639305972639306),
 (5976, 0.26326326326326327),
 (4935, 0.26309642976309644),
 (1113, 0.2624290957624291),
 (2832, 0.26209542876209546),
 (5279, 0.26176176176176175),
 (3758, 0.26126126126126126),
 (1858, 0.26076076076076077),
 (2485, 0.26076076076076077),
 (3422, 0.26059392726059394),
 (4683, 0.2604270937604271),
 (5170, 0.2602602602602603),
 (749, 0.2597597597597598),
 (1355, 0.25942609275942613),
 (4968, 0.25925925925925924),
 (2799, 0.25925925925925924),
 (4045, 0.2584250917584251),
 (1335, 0.25825825825825827),
 (3587, 0.2572572572572573),
 (1016, 0.25692359025692363),
 (361, 0.2565899232565899),
 (3830, 0.2559225892559226),
 (4428, 0.2552552552552553),
 (5452, 0.2547547547547548),
 (4200, 0.2547547547547548),
 (293, 0.25458792125458796),
 (5201, 0.2539205872539206),
 (4894, 0.2534200867534201),
 (1753, 0.2527527527527528),
 (3724, 0.25175175175175174),
 (2952, 0.25075075075075076),
 (685, 0.2504170837504171),
 (4128, 0.24974974974974976),
 (4195, 0.24858191524858192),
 (618, 0.2484150817484151),
 (411, 0.2479145812479146),
 (4963, 0.24774774774774777),
 (427, 0.24708041374708042),
 (612, 0.24657991324657993),
 (5982, 0.24624624624624625),
 (333, 0.24524524524524527),
 (240, 0.2450784117450784),
 (5881, 0.2450784117450784),
 (2802, 0.24391057724391058),
 (5521, 0.24374374374374375),
 (30, 0.24357691024357692),
 (3922, 0.2434100767434101),
 (1587, 0.24324324324324326),
 (1263, 0.2429095762429096),
 (5948, 0.24274274274274277),
 (4229, 0.24174174174174176),
 (508, 0.24057390724057393),
 (4575, 0.2400734067400734),
 (4159, 0.23973973973973975),
 (904, 0.23957290623957292),
 (1462, 0.23923923923923926),
 (943, 0.2379045712379046),
 (395, 0.2375709042375709),
 (2713, 0.2369035702369036),
 (4992, 0.23673673673673676),
 (5528, 0.23673673673673676),
 (1637, 0.2365699032365699),
 (1358, 0.2365699032365699),
 (4693, 0.23623623623623624),
 (5088, 0.23623623623623624),
 (18, 0.23590256923590258),
 (5352, 0.23590256923590258),
 (2395, 0.23556890223556892),
 (3882, 0.2354020687354021),
 (1321, 0.2335669002335669),
 (4011, 0.23306639973306642),
 (4173, 0.23306639973306642),
 (2776, 0.23289956623289956),
 (5862, 0.23239906573239907),
 (88, 0.23223223223223224),
 (2784, 0.23206539873206541),
 (3912, 0.23206539873206541),
 (2007, 0.2315648982315649),
 (1785, 0.23139806473139807),
 (5559, 0.23123123123123124),
 (940, 0.2295628962295629),
 (1668, 0.2295628962295629),
 (4086, 0.2290623957290624),
 (3256, 0.22772772772772773),
 (5271, 0.2275608942275609),
 (926, 0.22622622622622623),
 (91, 0.2260593927260594),
 (1121, 0.22589255922589258),
 (5724, 0.22572572572572575),
 (601, 0.22572572572572575),
 (2499, 0.22539205872539206),
 (22, 0.22522522522522523),
 (5300, 0.2245578912245579),
 (5298, 0.22372372372372373),
 (1260, 0.22372372372372373),
 (1872, 0.22339005672339007),
 (3307, 0.22238905572238907),
 (4576, 0.2220553887220554),
 (5015, 0.22188855522188858),
 (4356, 0.22088755422088757),
 (4354, 0.22022022022022023),
 (1375, 0.2200533867200534),
 (1919, 0.21971971971971974),
 (3185, 0.2190523857190524),
 (1953, 0.21838505171838507),
 (932, 0.2175508842175509),
 (3151, 0.2175508842175509),
 (4542, 0.21738405071738406),
 (4906, 0.21721721721721723),
 (956, 0.21721721721721723),
 (1153, 0.21688355021688355),
 (4898, 0.21688355021688355),
 (3436, 0.21588254921588257),
 (3756, 0.21588254921588257),
 (1142, 0.21588254921588257),
 (5842, 0.21571571571571574),
 (786, 0.21571571571571574),
 (1956, 0.21538204871538205),
 (298, 0.2150483817150484),
 (5283, 0.2150483817150484),
 (5412, 0.21488154821488156),
 (5407, 0.2145478812145479),
 (897, 0.2145478812145479),
 (916, 0.21421421421421422),
 (648, 0.21371371371371373),
 (4079, 0.2135468802135469),
 (1011, 0.2135468802135469),
 (480, 0.21338004671338007),
 (2779, 0.2132132132132132),
 (2722, 0.2125458792125459),
 (2836, 0.21221221221221223),
 (159, 0.21087754421087757),
 (200, 0.21087754421087757),
 (4365, 0.20970970970970973),
 (1838, 0.20954287620954287),
 (4387, 0.20787454120787455),
 (5949, 0.20770770770770772),
 (2549, 0.20704037370704037),
 (2655, 0.20653987320653988),
 (2415, 0.20637303970637305),
 (907, 0.20620620620620622),
 (2457, 0.20587253920587256),
 (5326, 0.20587253920587256),
 (515, 0.20553887220553888),
 (506, 0.20537203870537205),
 (5689, 0.20487153820487156),
 (4176, 0.20270270270270271),
 (925, 0.20253586920253588),
 (4469, 0.20220220220220222),
 (4594, 0.20220220220220222),
 (3640, 0.20220220220220222),
 (116, 0.20186853520186854),
 (2789, 0.20136803470136805),
 (1075, 0.20136803470136805),
 (224, 0.20053386720053387),
 (125, 0.19986653319986655),
 (5047, 0.19953286619953287),
 (2928, 0.19936603269936604),
 (3628, 0.1991991991991992),
 (2730, 0.1991991991991992),
 (5725, 0.19903236569903238),
 (1093, 0.19886553219886555),
 (4324, 0.19869869869869872),
 (4728, 0.1985318651985319),
 (1371, 0.1985318651985319),
 (4115, 0.19753086419753088),
 (726, 0.1971971971971972),
 (4188, 0.1971971971971972),
 (4659, 0.1971971971971972),
 (1115, 0.19686353019686353),
 (421, 0.19652986319652987),
 (3815, 0.19652986319652987),
 (3246, 0.19652986319652987),
 (2386, 0.19652986319652987),
 (3247, 0.19619619619619622),
 (810, 0.19602936269602936),
 (5519, 0.19586252919586253),
 (2024, 0.1956956956956957),
 (1812, 0.19536202869536204),
 (4572, 0.1951951951951952),
 (3243, 0.1951951951951952),
 (4319, 0.19486152819486155),
 (1945, 0.1946946946946947),
 (1884, 0.19436102769436103),
 (1273, 0.19402736069402737),
 (5624, 0.19386052719386054),
 (2449, 0.1936936936936937),
 (1432, 0.19336002669336003),
 (32, 0.19336002669336003),
 (4694, 0.1931931931931932),
 (5828, 0.19285952619285954),
 (530, 0.19285952619285954),
 (2387, 0.19252585919252588),
 (4036, 0.19235902569235905),
 (976, 0.19152485819152487),
 (977, 0.19135802469135804),
 (5978, 0.1906906906906907),
 (5429, 0.19035702369035704),
 (1060, 0.1901901901901902),
 (2380, 0.18985652318985652),
 (539, 0.18935602268935603),
 (1986, 0.18935602268935603),
 (1007, 0.1891891891891892),
 (2792, 0.1891891891891892),
 (3945, 0.18902235568902237),
 (703, 0.18902235568902237),
 (270, 0.1886886886886887),
 (3112, 0.18852185518852185),
 (3941, 0.18852185518852185),
 (372, 0.18852185518852185),
 (5197, 0.18835502168835502),
 (1449, 0.1881881881881882),
 (1506, 0.18785452118785453),
 (5652, 0.1876876876876877),
 (5099, 0.18735402068735402),
 (3205, 0.18651985318651987),
 (5317, 0.18635301968635304),
 (2328, 0.18635301968635304),
 (5278, 0.18601935268601935),
 (4118, 0.18585251918585252),
 (3091, 0.1856856856856857),
 (1097, 0.1856856856856857),
 (5396, 0.1856856856856857),
 (2593, 0.1856856856856857),
 (4177, 0.18551885218551886),
 (5921, 0.18535201868535203),
 (3032, 0.18485151818485152),
 (142, 0.18485151818485152),
 (1367, 0.18451785118451786),
 (4570, 0.18435101768435103),
 (3222, 0.18368368368368368),
 (3566, 0.18351685018351685),
 (2267, 0.1831831831831832),
 (5612, 0.18284951618284953),
 (3789, 0.18284951618284953),
 (4878, 0.18284951618284953),
 (3296, 0.1826826826826827),
 (2771, 0.18218218218218218),
 (5603, 0.18201534868201535),
 (776, 0.18184851518184852),
 (2654, 0.1816816816816817),
 (5973, 0.1816816816816817),
 (2276, 0.1806806806806807),
 (1179, 0.1801801801801802),
 (4044, 0.1801801801801802),
 (2743, 0.1798465131798465),
 (4672, 0.1798465131798465),
 (5340, 0.1791791791791792),
 (1674, 0.17884551217884553),
 (5941, 0.17884551217884553),
 (1460, 0.17867867867867868),
 (5802, 0.17867867867867868),
 (5252, 0.17867867867867868),
 (2251, 0.1781781781781782),
 (3280, 0.1781781781781782),
 (4125, 0.17801134467801136),
 (2164, 0.17801134467801136),
 (1187, 0.17784451117784453),
 (2195, 0.17784451117784453),
 (1636, 0.17751084417751084),
 (4231, 0.17684351017684352),
 (640, 0.1766766766766767),
 (2613, 0.1766766766766767),
 (5444, 0.17650984317650986),
 (1422, 0.176343009676343),
 (3049, 0.17600934267600934),
 (261, 0.17584250917584252),
 (3622, 0.17567567567567569),
 (622, 0.17550884217550886),
 (3526, 0.17534200867534203),
 (5775, 0.17500834167500834),
 (1331, 0.17500834167500834),
 (5276, 0.17500834167500834),
 (3686, 0.17467467467467468),
 (2625, 0.17450784117450785),
 (3823, 0.17450784117450785),
 (1108, 0.17434100767434102),
 (1889, 0.17434100767434102),
 (3042, 0.1741741741741742),
 (3993, 0.1741741741741742),
 (5432, 0.1741741741741742),
 (51, 0.17400734067400736),
 (2136, 0.1738405071738405),
 (873, 0.17367367367367367),
 (3283, 0.17367367367367367),
 (1558, 0.17300633967300635),
 (4960, 0.17300633967300635),
 (3359, 0.17283950617283952),
 (4901, 0.17283950617283952),
 (5661, 0.17267267267267267),
 (846, 0.17267267267267267),
 (1407, 0.17267267267267267),
 (3776, 0.17217217217217218),
 (5010, 0.17217217217217218),
 (701, 0.17200533867200535),
 (2472, 0.17200533867200535),
 (1363, 0.1716716716716717),
 (4112, 0.17150483817150486),
 (2066, 0.17117117117117117),
 (4999, 0.17100433767100434),
 (3920, 0.17067067067067068),
 (931, 0.17050383717050385),
 (5722, 0.17017017017017017),
 (2393, 0.17000333667000334),
 (704, 0.1698365031698365),
 (1886, 0.1698365031698365),
 (1149, 0.16966966966966968),
 (3073, 0.16966966966966968),
 (5461, 0.16950283616950285),
 (2772, 0.16866866866866867),
 (911, 0.16866866866866867),
 (3264, 0.16866866866866867),
 (360, 0.16850183516850184),
 (2504, 0.168335001668335),
 (4738, 0.168335001668335),
 (3663, 0.16816816816816818),
 (132, 0.16800133466800135),
 (3532, 0.16783450116783452),
 (739, 0.16766766766766766),
 (1499, 0.16766766766766766),
 (2322, 0.16750083416750083),
 (4979, 0.16750083416750083),
 (967, 0.167334000667334),
 (2527, 0.167334000667334),
 (2916, 0.16716716716716717),
 (4238, 0.16666666666666669),
 (3559, 0.166332999666333),
 (4279, 0.16616616616616617),
 (1376, 0.16616616616616617),
 (4275, 0.16616616616616617),
 (50, 0.1658324991658325),
 (3887, 0.1658324991658325),
 (5809, 0.16566566566566568),
 (670, 0.16533199866533202),
 (1712, 0.16499833166499833),
 (5551, 0.16499833166499833),
 (3367, 0.16499833166499833),
 (1206, 0.1648314981648315),
 (92, 0.164330997664331),
 (5899, 0.16399733066399733),
 (4330, 0.1638304971638305),
 (4394, 0.16366366366366367),
 (5504, 0.16366366366366367),
 (4352, 0.16349683016349684),
 (5325, 0.16349683016349684),
 (2725, 0.16349683016349684),
 (5113, 0.16332999666333),
 (4538, 0.16299632966299635),
 (3402, 0.1628294961628295),
 (1172, 0.16266266266266266),
 (5751, 0.16266266266266266),
 (980, 0.16199532866199534),
 (1582, 0.1618284951618285),
 (5699, 0.1618284951618285),
 (2073, 0.1618284951618285),
 (5893, 0.16166166166166168),
 (3238, 0.16166166166166168),
 (5134, 0.16149482816149482),
 (5579, 0.16149482816149482),
 (377, 0.161327994661328),
 (198, 0.16116116116116116),
 (3137, 0.16116116116116116),
 (5717, 0.16116116116116116),
 (2696, 0.16116116116116116),
 (1527, 0.16099432766099434),
 (5517, 0.16099432766099434),
 (4729, 0.1608274941608275),
 (4149, 0.16066066066066068),
 (3130, 0.16049382716049385),
 (5694, 0.16049382716049385),
 (5876, 0.15999332665999333),
 (3915, 0.15999332665999333),
 (1441, 0.15999332665999333),
 (3075, 0.159325992659326),
 (2585, 0.159325992659326),
 (5879, 0.15899232565899232),
 (2481, 0.15899232565899232),
 (2033, 0.15899232565899232),
 (1455, 0.1588254921588255),
 (1841, 0.1588254921588255),
 (4233, 0.1588254921588255),
 (5734, 0.1588254921588255),
 (5067, 0.15865865865865866),
 (3892, 0.15865865865865866),
 (4985, 0.15849182515849183),
 (4621, 0.15849182515849183),
 (4817, 0.15849182515849183),
 (5343, 0.15815815815815817),
 (2573, 0.15815815815815817),
 (568, 0.15799132465799134),
 (5776, 0.15799132465799134),
 (5378, 0.15799132465799134),
 (4630, 0.15765765765765766),
 (4247, 0.15765765765765766),
 (782, 0.15765765765765766),
 (4206, 0.157323990657324),
 (899, 0.1568234901568235),
 (4426, 0.1568234901568235),
 (5924, 0.15615615615615616),
 (5182, 0.15615615615615616),
 (5531, 0.15598932265598933),
 (5502, 0.15598932265598933),
 (412, 0.1558224891558225),
 (5854, 0.15515515515515516),
 (2752, 0.15498832165498833),
 (2839, 0.1548214881548215),
 (3518, 0.1548214881548215),
 (1979, 0.1548214881548215),
 (461, 0.15448782115448784),
 (746, 0.15448782115448784),
 (5399, 0.154320987654321),
 (1374, 0.154320987654321),
 (4350, 0.154320987654321),
 (3373, 0.15415415415415415),
 (3493, 0.1538204871538205),
 (4768, 0.1538204871538205),
 (5335, 0.1538204871538205),
 (621, 0.15365365365365366),
 (4554, 0.15365365365365366),
 (1763, 0.15348682015348683),
 (729, 0.1529863196529863),
 (2221, 0.1529863196529863),
 (2343, 0.15265265265265265),
 (5310, 0.152318985652319),
 (524, 0.15215215215215216),
 (4834, 0.15215215215215216),
 (4678, 0.15198531865198533),
 (935, 0.1518184851518185),
 (3511, 0.151317984651318),
 (1894, 0.15115115115115116),
 (3781, 0.15115115115115116),
 (4565, 0.15098431765098433),
 (2269, 0.15098431765098433),
 (5653, 0.15065065065065067),
 (2243, 0.1504838171504838),
 (1692, 0.14998331664998332),
 (3562, 0.14998331664998332),
 (5827, 0.1498164831498165),
 (2943, 0.14964964964964966),
 (1379, 0.14948281614948283),
 (5488, 0.14948281614948283),
 (4645, 0.14948281614948283),
 (5625, 0.14931598264931598),
 (398, 0.14914914914914915),
 (2878, 0.14914914914914915),
 (4155, 0.14914914914914915),
 (4391, 0.14914914914914915),
 (2077, 0.14914914914914915),
 (5721, 0.14898231564898232),
 (5184, 0.14898231564898232),
 (4069, 0.1488154821488155),
 (3355, 0.14848181514848183),
 (4806, 0.14848181514848183),
 (4013, 0.14848181514848183),
 (307, 0.14848181514848183),
 (4411, 0.148314981648315),
 (4698, 0.14814814814814817),
 (3499, 0.14814814814814817),
 (5321, 0.1479813146479813),
 (4790, 0.1479813146479813),
 (494, 0.1479813146479813),

In [17]:
dcentralities[4837] # centraility of PCR in March

0.44127460794127465

In [18]:
americanNeighbors = g.neighbors(4837)
g_american = g.subgraph(americanNeighbors)
print(nx.info(g_american))

Name:
Type: Graph
Number of nodes: 2645
Number of edges: 553695
Average degree: 418.6730

In [44]:
dcentralities_gsub = nx.degree_centrality(g_american )
sorted(dcentralities_gsub.items(), reverse = True, key = lambda x:x[1])

[(641, 0.8929652042360061),
 (5965, 0.8891830559757943),
 (3965, 0.8812405446293495),
 (712, 0.8555219364599093),
 (4383, 0.8165658093797277),
 (3846, 0.7673978819969743),
 (3995, 0.7673978819969743),
 (4966, 0.7522692889561271),
 (40, 0.75),
 (5361, 0.7416792738275341),
 (4686, 0.7326021180030258),
 (845, 0.7227685325264751),
 (147, 0.7148260211800302),
 (1146, 0.705748865355522),
 (1912, 0.7023449319213313),
 (1409, 0.6993192133131619),
 (4688, 0.6822995461422088),
 (832, 0.680786686838124),
 (4785, 0.6781391830559758),
 (1834, 0.6773827534039335),
 (4143, 0.6728441754916793),
 (2586, 0.6645234493192134),
 (3441, 0.6622541603630863),
 (3455, 0.6448562783661119),
 (2054, 0.6304841149773072),
 (4551, 0.6293494704992436),
 (5273, 0.6244326777609682),
 (3855, 0.624054462934947),
 (3291, 0.6236762481089259),
 (4696, 0.6225416036308623),
 (2398, 0.6138426626323752),
 (3963, 0.6119515885022693),
 (5867, 0.6062783661119516),
 (5163, 0.6013615733736762),
 (4771, 0.5990922844175491),
 (3533, 0.5979576399394857),
 (4684, 0.5949319213313162),
 (1008, 0.594553706505295),
 (3295, 0.5900151285930408),
 (4039, 0.5888804841149773),
 (3357, 0.5877458396369137),
 (4175, 0.5775340393343419),
 (2837, 0.5748865355521937),
 (5591, 0.5665658093797277),
 (4628, 0.5635400907715583),
 (124, 0.56089258698941),
 (2240, 0.5571104387291982),
 (110, 0.556732223903177),
 (2805, 0.5465204236006052),
 (4832, 0.5465204236006052),
 (1029, 0.5427382753403933),
 (1320, 0.5374432677760969),
 (2189, 0.5347957639939486),
 (4095, 0.5347957639939486),
 (2566, 0.5310136157337367),
 (3431, 0.5260968229954615),
 (4674, 0.5234493192133132),
 (5527, 0.5234493192133132),
 (3241, 0.5211800302571861),
 (1502, 0.5204236006051437),
 (3278, 0.5139939485627837),
 (4752, 0.5136157337367625),
 (1427, 0.5094553706505295),
 (4300, 0.5090771558245083),
 (2768, 0.5071860816944024),
 (736, 0.5052950075642966),
 (3190, 0.5030257186081695),
 (4911, 0.5018910741301059),
 (5384, 0.5003782148260212),
 (1078, 0.5),
 (1751, 0.49735249621785177),
 (5294, 0.4969742813918306),
 (3435, 0.49583963691376703),
 (3706, 0.4947049924357035),
 (1048, 0.49205748865355525),
 (4351, 0.49205748865355525),
 (4080, 0.48978819969742815),
 (3203, 0.48789712556732223),
 (2894, 0.48411497730711045),
 (1724, 0.48373676248108927),
 (672, 0.4829803328290469),
 (1055, 0.48222390317700453),
 (4668, 0.4791981845688351),
 (5341, 0.476928895612708),
 (5793, 0.47655068078668683),
 (4777, 0.47579425113464446),
 (3077, 0.47503782148260215),
 (1700, 0.47276853252647505),
 (5337, 0.47012102874432676),
 (1034, 0.46747352496217853),
 (5788, 0.462178517397882),
 (4808, 0.45915279878971255),
 (5041, 0.45839636913767023),
 (1252, 0.45537065052950076),
 (4027, 0.4508320726172466),
 (4207, 0.45007564296520425),
 (2676, 0.44818456883509833),
 (2917, 0.44704992435703483),
 (781, 0.44440242057488655),
 (1139, 0.44402420574886536),
 (2686, 0.44402420574886536),
 (2637, 0.4402420574886536),
 (4303, 0.4394856278366112),
 (5013, 0.43835098335854766),
 (2817, 0.4379727685325265),
 (4536, 0.43494704992435707),
 (3265, 0.4338124054462935),
 (328, 0.4322995461422088),
 (2372, 0.4319213313161876),
 (4919, 0.43116490166414523),
 (1703, 0.43078668683812404),
 (4229, 0.43078668683812404),
 (2767, 0.43040847201210286),
 (3931, 0.4300302571860817),
 (2887, 0.428517397881997),
 (62, 0.4281391830559758),
 (2109, 0.4281391830559758),
 (1174, 0.42776096822995463),
 (4676, 0.42776096822995463),
 (4268, 0.42700453857791226),
 (1113, 0.4266263237518911),
 (3180, 0.4262481089258699),
 (232, 0.4254916792738275),
 (4664, 0.42473524962178516),
 (1535, 0.424357034795764),
 (633, 0.4209531013615734),
 (887, 0.420196671709531),
 (1978, 0.4198184568835098),
 (2485, 0.4186838124054463),
 (3155, 0.41603630862329805),
 (1035, 0.41376701966717094),
 (20, 0.41263237518910745),
 (5352, 0.41036308623298035),
 (2952, 0.409606656580938),
 (4818, 0.409606656580938),
 (5850, 0.40771558245083206),
 (4660, 0.40695915279878975),
 (2406, 0.4062027231467474),
 (3791, 0.4062027231467474),
 (4683, 0.4062027231467474),
 (4673, 0.4027987897125567),
 (5279, 0.4027987897125567),
 (5373, 0.40242057488653554),
 (4445, 0.40090771558245086),
 (3084, 0.4001512859304085),
 (4423, 0.4001512859304085),
 (470, 0.39863842662632376),
 (3469, 0.39863842662632376),
 (117, 0.3975037821482602),
 (5976, 0.39636913767019666),
 (2035, 0.3959909228441755),
 (2963, 0.3959909228441755),
 (1973, 0.39561270801815435),
 (2177, 0.39523449319213316),
 (2409, 0.394856278366112),
 (3922, 0.3940998487140696),
 (1793, 0.39372163388804843),
 (5167, 0.39372163388804843),
 (971, 0.39107413010590014),
 (3822, 0.39107413010590014),
 (1990, 0.39069591527987896),
 (148, 0.3903177004538578),
 (4542, 0.38956127080181546),
 (293, 0.38767019667170954),
 (549, 0.3869137670196672),
 (4968, 0.3869137670196672),
 (2668, 0.3861573373676248),
 (5589, 0.3857791225416036),
 (5783, 0.38502269288956126),
 (1617, 0.3846444780635401),
 (3911, 0.38388804841149776),
 (5090, 0.38161875945537066),
 (586, 0.3804841149773071),
 (5807, 0.3801059001512859),
 (4942, 0.3789712556732224),
 (4693, 0.3778366111951589),
 (932, 0.3770801815431165),
 (1152, 0.37632375189107414),
 (5932, 0.37594553706505296),
 (2832, 0.3755673222390318),
 (1906, 0.3744326777609682),
 (956, 0.37405446293494704),
 (5982, 0.37291981845688355),
 (5763, 0.37254160363086236),
 (4557, 0.3721633888048412),
 (4896, 0.3721633888048412),
 (3189, 0.37178517397882),
 (5954, 0.37065052950075644),
 (685, 0.3698940998487141),
 (387, 0.3691376701966717),
 (5707, 0.36838124054462934),
 (4098, 0.36800302571860816),
 (2536, 0.367624810892587),
 (3724, 0.3657337367624811),
 (1753, 0.36459909228441756),
 (4015, 0.3642208774583964),
 (2799, 0.3638426626323752),
 (618, 0.363464447806354),
 (3454, 0.3619515885022693),
 (5303, 0.36157337367624814),
 (4369, 0.36119515885022696),
 (1858, 0.3608169440242058),
 (3529, 0.3608169440242058),
 (3146, 0.3600605143721634),
 (4502, 0.3600605143721634),
 (2499, 0.3596822995461422),
 (478, 0.3577912254160363),
 (825, 0.3574130105900151),
 (411, 0.3551437216338881),
 (91, 0.3540090771558245),
 (4963, 0.3540090771558245),
 (3758, 0.35325264750378216),
 (5466, 0.352874432677761),
 (1340, 0.3524962178517398),
 (5523, 0.3524962178517398),
 (283, 0.3521180030257186),
 (4011, 0.3517397881996974),
 (4894, 0.35136157337367624),
 (3826, 0.3483358547655068),
 (4604, 0.3483358547655068),
 (3587, 0.3468229954614221),
 (3882, 0.3460665658093797),
 (2631, 0.34531013615733736),
 (5452, 0.34493192133131617),
 (4491, 0.3434190620272315),
 (926, 0.3430408472012103),
 (1462, 0.3430408472012103),
 (3830, 0.3430408472012103),
 (5501, 0.3426626323751891),
 (612, 0.34228441754916794),
 (3633, 0.34228441754916794),
 (1825, 0.34190620272314676),
 (4195, 0.34190620272314676),
 (1872, 0.3415279878971256),
 (258, 0.340393343419062),
 (333, 0.340393343419062),
 (4738, 0.340393343419062),
 (5201, 0.34001512859304084),
 (4167, 0.33925869894099847),
 (3336, 0.33850226928895616),
 (4935, 0.3373676248108926),
 (4319, 0.33623298033282906),
 (469, 0.3354765506807867),
 (200, 0.3332072617246596),
 (18, 0.3324508320726173),
 (240, 0.3316944024205749),
 (2233, 0.3316944024205749),
 (2734, 0.33093797276853254),
 (904, 0.33055975794251136),
 (515, 0.329803328290469),
 (5497, 0.329803328290469),
 (3100, 0.3294251134644478),
 (1956, 0.32866868381240544),
 (601, 0.3275340393343419),
 (916, 0.3275340393343419),
 (88, 0.32715582450832076),
 (361, 0.3263993948562784),
 (2380, 0.3260211800302572),
 (2449, 0.3260211800302572),
 (5170, 0.325642965204236),
 (4128, 0.32526475037821484),
 (5015, 0.32526475037821484),
 (976, 0.3241301059001513),
 (2395, 0.3241301059001513),
 (940, 0.3237518910741301),
 (22, 0.3233736762481089),
 (784, 0.3233736762481089),
 (2323, 0.3233736762481089),
 (5948, 0.32261724659606655),
 (427, 0.32223903177004537),
 (5283, 0.32223903177004537),
 (5862, 0.32148260211800306),
 (5881, 0.32148260211800306),
 (4365, 0.3207261724659607),
 (1637, 0.3203479576399395),
 (2713, 0.31959152798789714),
 (3566, 0.31883509833585477),
 (4200, 0.3184568835098336),
 (1710, 0.31732223903177004),
 (907, 0.31656580937972767),
 (1260, 0.3161875945537065),
 (5559, 0.3161875945537065),
 (4428, 0.3154311649016642),
 (2784, 0.315052950075643),
 (4360, 0.315052950075643),
 (925, 0.3146747352496218),
 (1121, 0.3124054462934947),
 (3247, 0.3124054462934947),
 (2947, 0.3120272314674735),
 (4576, 0.3120272314674735),
 (1587, 0.3097579425113465),
 (1785, 0.3093797276853253),
 (3691, 0.3090015128593041),
 (298, 0.30786686838124055),
 (1142, 0.30786686838124055),
 (4575, 0.3071104387291982),
 (754, 0.306732223903177),
 (943, 0.306732223903177),
 (3912, 0.306732223903177),
 (2836, 0.3063540090771558),
 (327, 0.30597579425113464),
 (5531, 0.30597579425113464),
 (1011, 0.3048411497730711),
 (125, 0.3037065052950076),
 (3941, 0.3033282904689864),
 (5407, 0.3029500756429652),
 (2549, 0.30257186081694404),
 (4694, 0.30257186081694404),
 (1884, 0.30219364599092285),
 (3112, 0.30219364599092285),
 (1422, 0.30181543116490167),
 (3422, 0.30181543116490167),
 (5941, 0.30181543116490167),
 (1886, 0.3006807866868381),
 (3246, 0.29992435703479575),
 (4538, 0.29954614220877457),
 (4960, 0.29954614220877457),
 (1321, 0.2991679273827534),
 (1432, 0.29878971255673226),
 (1355, 0.2984114977307111),
 (1358, 0.2980332829046899),
 (3459, 0.2980332829046899),
 (4173, 0.2980332829046899),
 (1986, 0.2957639939485628),
 (3053, 0.2957639939485628),
 (2195, 0.2950075642965204),
 (4572, 0.2950075642965204),
 (4728, 0.2950075642965204),
 (3559, 0.2927382753403934),
 (3815, 0.2927382753403934),
 (4992, 0.2916036308623298),
 (786, 0.29122541603630864),
 (2328, 0.29084720121028745),
 (3920, 0.29084720121028745),
 (1153, 0.28895612708018154),
 (5546, 0.28895612708018154),
 (3243, 0.287821482602118),
 (935, 0.28706505295007567),
 (539, 0.2863086232980333),
 (4678, 0.28555219364599094),
 (5973, 0.28555219364599094),
 (1335, 0.28517397881996975),
 (931, 0.28479576399394857),
 (1812, 0.28479576399394857),
 (159, 0.2844175491679274),
 (1889, 0.2844175491679274),
 (3756, 0.2840393343419062),
 (5444, 0.2840393343419062),
 (5528, 0.283661119515885),
 (506, 0.28177004538577916),
 (5661, 0.2810136157337368),
 (1093, 0.2806354009077156),
 (1953, 0.2802571860816944),
 (1016, 0.2783661119515885),
 (4159, 0.2783661119515885),
 (5271, 0.2783661119515885),
 (2722, 0.27685325264750377),
 (749, 0.2764750378214826),
 (5842, 0.2764750378214826),
 (3628, 0.27609682299546146),
 (5088, 0.27609682299546146),
 (977, 0.27571860816944027),
 (1449, 0.27571860816944027),
 (3789, 0.27571860816944027),
 (4878, 0.27571860816944027),
 (2655, 0.2745839636913767),
 (5252, 0.2745839636913767),
 (3436, 0.27420574886535554),
 (92, 0.27382753403933435),
 (2776, 0.27344931921331317),
 (4737, 0.27344931921331317),
 (5689, 0.273071104387292),
 (4985, 0.2726928895612708),
 (4659, 0.2723146747352496),
 (3562, 0.27193645990922843),
 (4188, 0.27193645990922843),
 (5010, 0.27155824508320725),
 (5317, 0.2708018154311649),
 (4354, 0.27042360060514375),
 (1263, 0.2696671709531014),
 (911, 0.2692889561270802),
 (3640, 0.2692889561270802),
 (2386, 0.268910741301059),
 (5734, 0.268910741301059),
 (5278, 0.26815431164901665),
 (5652, 0.26815431164901665),
 (4672, 0.2670196671709531),
 (1187, 0.26626323751891073),
 (1392, 0.26550680786686837),
 (1838, 0.26550680786686837),
 (2789, 0.26550680786686837),
 (3499, 0.2639939485627837),
 (846, 0.2636157337367625),
 (2470, 0.26285930408472014),
 (524, 0.26210287443267777),
 (4681, 0.2617246596066566),
 (5949, 0.2617246596066566),
 (1097, 0.2613464447806354),
 (3945, 0.2613464447806354),
 (5921, 0.2609682299546142),
 (1367, 0.26059001512859303),
 (2007, 0.26059001512859303),
 (4149, 0.26059001512859303),
 (4324, 0.26059001512859303),
 (3238, 0.26021180030257185),
 (2073, 0.2594553706505295),
 (5838, 0.2594553706505295),
 (2802, 0.25869894099848717),
 (1375, 0.258320726172466),
 (4999, 0.2575642965204236),
 (5197, 0.25642965204236007),
 (2730, 0.2560514372163389),
 (5724, 0.2560514372163389),
 (4036, 0.2556732223903177),
 (360, 0.2552950075642965),
 (2654, 0.2552950075642965),
 (2736, 0.2552950075642965),
 (703, 0.25453857791225415),
 (4044, 0.25416036308623297),
 (5694, 0.25416036308623297),
 (4118, 0.25340393343419065),
 (2504, 0.25302571860816947),
 (4906, 0.25302571860816947),
 (421, 0.2518910741301059),
 (1668, 0.2518910741301059),
 (2024, 0.2518910741301059),
 (5182, 0.25113464447806355),
 (568, 0.25075642965204237),
 (2066, 0.25075642965204237),
 (3296, 0.25075642965204237),
 (4227, 0.25075642965204237),
 (2415, 0.2503782148260212),
 (5300, 0.24924357034795763),
 (5134, 0.24886535552193648),
 (5340, 0.24886535552193648),
 (2251, 0.2484871406959153),
 (873, 0.2481089258698941),
 (4115, 0.2481089258698941),
 (4698, 0.2481089258698941),
 (1108, 0.24773071104387293),
 (5519, 0.24773071104387293),
 (5722, 0.24773071104387293),
 (4834, 0.24735249621785174),
 (51, 0.24697428139183056),
 (5184, 0.24659606656580937),
 (3185, 0.24621785173978822),
 (2276, 0.24583963691376703),
 (3887, 0.24583963691376703),
 (5530, 0.24583963691376703),
 (398, 0.24546142208774585),
 (3205, 0.24546142208774585),
 (5235, 0.24470499243570348),
 (2792, 0.2443267776096823),
 (530, 0.24394856278366112),
 (5603, 0.24394856278366112),
 (90, 0.2428139183055976),
 (1415, 0.2428139183055976),
 (3511, 0.24205748865355523),
 (5612, 0.24205748865355523),
 (5802, 0.24205748865355523),
 (3993, 0.24167927382753404),
 (2710, 0.24130105900151286),
 (5899, 0.24130105900151286),
 (307, 0.24092284417549167),
 (3137, 0.24092284417549167),
 (4570, 0.24054462934947052),
 (2393, 0.24016641452344933),
 (5432, 0.24016641452344933),
 (2743, 0.23940998487140697),
 (412, 0.23903177004538578),
 (2457, 0.23903177004538578),
 (1506, 0.2386535552193646),
 (3892, 0.23827534039334342),
 (810, 0.23789712556732223),
 (5326, 0.23789712556732223),
 (3997, 0.2371406959152799),
 (4013, 0.2371406959152799),
 (1945, 0.23600605143721634),
 (32, 0.23562783661119516),
 (3359, 0.23562783661119516),
 (3042, 0.23487140695915282),
 (4079, 0.23487140695915282),
 (5429, 0.23487140695915282),
 (5775, 0.23487140695915282),
 (1331, 0.23449319213313163),
 (1692, 0.23449319213313163),
 (1894, 0.23411497730711045),
 (2527, 0.23411497730711045),
 (3823, 0.23411497730711045),
 (1460, 0.23373676248108927),
 (4391, 0.23373676248108927),
 (377, 0.23335854765506808),
 (4920, 0.2329803328290469),
 (5236, 0.2329803328290469),
 (2584, 0.23222390317700453),
 (4231, 0.2314674735249622),
 (5310, 0.231089258698941),
 (5826, 0.231089258698941),
 (1075, 0.23071104387291982),
 (5725, 0.23033282904689864),
 (1149, 0.22995461422087746),
 (2585, 0.22995461422087746),
 (2706, 0.22995461422087746),
 (4901, 0.22995461422087746),
 (4148, 0.22919818456883512),
 (5790, 0.22919818456883512),
 (726, 0.22881996974281393),
 (3373, 0.22881996974281393),
 (3764, 0.22844175491679275),
 (5653, 0.22844175491679275),
 (4176, 0.22806354009077157),
 (2267, 0.22768532526475038),
 (5468, 0.22768532526475038),
 (4350, 0.2273071104387292),
 (2033, 0.22692889561270801),
 (4238, 0.22655068078668683),
 (4817, 0.22655068078668683),
 (1007, 0.22617246596066568),
 (5099, 0.22617246596066568),
 (5205, 0.22617246596066568),
 (5343, 0.22617246596066568),
 (5579, 0.22617246596066568),
 (4279, 0.2254160363086233),
 (5502, 0.2254160363086233),
 (1363, 0.22503782148260212),
 (2498, 0.22503782148260212),
 (704, 0.22465960665658094),
 (897, 0.22465960665658094),
 (2613, 0.22465960665658094),
 (4594, 0.22465960665658094),
 (2928, 0.22428139183055976),
 (2573, 0.22390317700453857),
 (5624, 0.22390317700453857),
 (372, 0.22352496217851742),
 (2625, 0.22314674735249623),
 (1391, 0.22239031770045387),
 (2752, 0.22239031770045387),
 (461, 0.22201210287443268),
 (1003, 0.22201210287443268),
 (1273, 0.22201210287443268),
 (4220, 0.22201210287443268),
 (5717, 0.22201210287443268),
 (1636, 0.2216338880484115),
 (1934, 0.2216338880484115),
 (261, 0.22125567322239031),
 (572, 0.22087745839636913),
 (3130, 0.22087745839636913),
 (1371, 0.22049924357034797),
 (3541, 0.22049924357034797),
 (132, 0.2201210287443268),
 (643, 0.21936459909228442),
 (2696, 0.21936459909228442),
 (967, 0.21898638426626324),
 (1763, 0.21898638426626324),
 (4103, 0.21898638426626324),
 (5978, 0.21898638426626324),
 (622, 0.21860816944024206),
 (3312, 0.21860816944024206),
 (2593, 0.21822995461422087),
 (2771, 0.21822995461422087),
 (5854, 0.21822995461422087),
 (5047, 0.21785173978819972),
 (1674, 0.21747352496217853),
 (912, 0.21709531013615735),
 (972, 0.21709531013615735),
 (3697, 0.21709531013615735),
 (4286, 0.21671709531013617),
 (2343, 0.21633888048411498),
 (2399, 0.21633888048411498),
 (1374, 0.2159606656580938),
 (5335, 0.2159606656580938),
 (3841, 0.21558245083207261),
 (4272, 0.21558245083207261),
 (5312, 0.21558245083207261),
 (2322, 0.21520423600605143),
 (5858, 0.21520423600605143),
 (3686, 0.21482602118003027),
 (2461, 0.2144478063540091),
 (3110, 0.2144478063540091),
 (1455, 0.2140695915279879),
 (1744, 0.2140695915279879),
 (2725, 0.2140695915279879),
 (833, 0.21369137670196672),
 (1005, 0.21369137670196672),
 (1194, 0.21369137670196672),
 (1540, 0.21331316187594554),
 (2943, 0.21331316187594554),
 (5625, 0.21331316187594554),
 (5924, 0.21331316187594554),
 (3073, 0.21255673222390317),
 (5126, 0.21255673222390317),
 (3402, 0.212178517397882),
 (5832, 0.212178517397882),
 (4729, 0.21180030257186083),
 (339, 0.21104387291981846),
 (2432, 0.21104387291981846),
 (2747, 0.21104387291981846),
 (270, 0.2102874432677761),
 (2786, 0.2099092284417549),
 (3858, 0.20953101361573373),
 (5778, 0.20953101361573373),
 (142, 0.2087745839636914),
 (199, 0.2087745839636914),
 (4206, 0.2087745839636914),
 (2844, 0.2083963691376702),
 (3222, 0.2083963691376702),
 (594, 0.20801815431164902),
 (782, 0.20801815431164902),
 (4529, 0.20801815431164902),
 (4031, 0.20763993948562784),
 (1558, 0.20726172465960666),
 (1979, 0.20726172465960666),
 (5461, 0.20726172465960666),
 (129, 0.20688350983358547),
 (5162, 0.20688350983358547),
 (1172, 0.2065052950075643),
 (1179, 0.2065052950075643),
 (1230, 0.2065052950075643),
 (3663, 0.2065052950075643),
 (2472, 0.20612708018154313),
 (4735, 0.20612708018154313),
 (2798, 0.20574886535552195),
 (50, 0.20499243570347958),
 (1898, 0.20499243570347958),
 (607, 0.2046142208774584),
 (2893, 0.2046142208774584),
 (5827, 0.2046142208774584),
 (5524, 0.2042360060514372),
 (5879, 0.20385779122541603),
 (2645, 0.20347957639939487),
 (930, 0.2031013615733737),
 (3423, 0.2031013615733737),
 (3781, 0.2031013615733737),
 (4838, 0.2031013615733737),
 (2063, 0.2027231467473525),
 (3094, 0.2027231467473525),
 (4275, 0.20234493192133132),
 (5131, 0.20234493192133132),
 (3873, 0.20196671709531014),
 (3283, 0.20158850226928895),
 (3355, 0.20158850226928895),
 (3613, 0.20158850226928895),
 (2236, 0.20121028744326777),
 (2794, 0.20121028744326777),
 (2221, 0.2008320726172466),
 (2465, 0.20045385779122543),
 (4210, 0.20045385779122543),
 (2218, 0.20007564296520425),
 (4069, 0.20007564296520425),
 (5325, 0.20007564296520425),
 (1083, 0.19969742813918306),
 (1132, 0.19931921331316188),
 (1437, 0.19931921331316188),
 (1754, 0.19931921331316188),
 (5077, 0.19931921331316188),
 (4304, 0.1989409984871407),
 (701, 0.1985627836611195),
 (2269, 0.1985627836611195),
 (4790, 0.1985627836611195),
 (5488, 0.1985627836611195),
 (1060, 0.19780635400907717),
 (3661, 0.197428139183056),
 (4589, 0.197428139183056),
 (3388, 0.1970499243570348),
 (5481, 0.19667170953101362),
 (5504, 0.19667170953101362),
 (655, 0.19629349470499244),
 (3881, 0.19629349470499244),
 (2839, 0.19591527987897125),
 (3294, 0.19591527987897125),
 (3622, 0.19591527987897125),
 (5656, 0.19591527987897125),
 (5865, 0.19591527987897125),
 (814, 0.19553706505295007),
 (980, 0.19553706505295007),
 (4645, 0.19553706505295007),
 (5721, 0.19553706505295007),
 (3769, 0.1951588502269289),
 (5809, 0.1951588502269289),
 (5893, 0.19478063540090773),
 (2077, 0.19440242057488655),
 (4038, 0.19440242057488655),
 (5831, 0.19440242057488655),
 (2046, 0.19402420574886536),

pcr related words: case year patient cell protein outbreak pcr sequence

write function match the num to the word

# Network of 2021 Data

In [8]:
node_list3 = [i for i in text_jan_network[0]]
node_list4 = [i for i in text_jan_network[1]]

In [9]:
len(node_list4)

1302248

In [12]:
g2 = nx.Graph()

In [13]:
for i in range(len(node_list3)):
    g2.add_node(node_list3[i])
    g2.add_node(node_list4[i])
    g2.add_edge(node_list3[i],node_list4[i])

In [14]:
len(g2.nodes)

3358

In [15]:
len(g2.edges)

1302248

In [16]:
dcentralities2 = nx.degree_centrality(g2)
sorted(dcentralities2.items(), reverse = True, key = lambda x:x[1])

[(3264, 0.9261245159368483),
 (2419, 0.9243372058385463),
 (596, 0.9195710455764075),
 (1728, 0.906166219839142),
 (531, 0.8835269585939827),
 (2378, 0.8826333035448317),
 (2664, 0.8796544533809949),
 (366, 0.8370568960381293),
 (1462, 0.8129282097110515),
 (551, 0.8066726243669943),
 (2191, 0.8060768543342269),
 (2965, 0.8030980041703902),
 (2092, 0.8010128090557045),
 (1296, 0.8001191540065534),
 (1872, 0.7980339588918677),
 (3097, 0.7908847184986595),
 (2997, 0.7902889484658921),
 (2663, 0.785820673220137),
 (2457, 0.7846291331546023),
 (739, 0.7765862377122431),
 (124, 0.7566279416145367),
 (3047, 0.755436401549002),
 (3010, 0.7545427464998511),
 (1592, 0.7485850461721775),
 (1825, 0.7414358057789693),
 (2841, 0.7411379207625857),
 (3210, 0.7399463806970509),
 (133, 0.7372654155495978),
 (2184, 0.7327971403038427),
 (2067, 0.7274352100089365),
 (971, 0.7199880845993446),
 (2591, 0.7170092344355079),
 (1413, 0.7140303842716711),
 (452, 0.7101578790586833),
 (2438, 0.7092642240095323),
 (131, 0.7080726839439976),
 (965, 0.7071790288948466),
 (1322, 0.7056896038129282),
 (3247, 0.7047959487637772),
 (23, 0.7044980637473935),
 (786, 0.7044980637473935),
 (3026, 0.7044980637473935),
 (1093, 0.7036044086982425),
 (1732, 0.7018170985999405),
 (1436, 0.7006255585344057),
 (2953, 0.6943699731903485),
 (2537, 0.6940720881739648),
 (59, 0.6940720881739648),
 (2422, 0.6934763181411975),
 (2137, 0.6878165028299077),
 (2897, 0.685731307715222),
 (2812, 0.6830503425677689),
 (915, 0.6812630324694667),
 (186, 0.6797736073875484),
 (1829, 0.6797736073875484),
 (2809, 0.677390527256479),
 (2083, 0.6687518617813524),
 (2119, 0.6660708966338993),
 (1055, 0.6657730116175157),
 (1335, 0.6621983914209115),
 (1819, 0.6574322311587727),
 (2995, 0.6565385761096216),
 (3167, 0.6526660708966339),
 (2795, 0.6508787607983318),
 (1754, 0.6505808757819481),
 (1706, 0.6499851057491808),
 (2736, 0.6481977956508788),
 (65, 0.6422400953232053),
 (2220, 0.6410485552576706),
 (3109, 0.63777182007745),
 (1388, 0.6353887399463807),
 (2087, 0.6344950848972296),
 (3124, 0.6338993148644623),
 (1733, 0.6336014298480787),
 (1361, 0.6318141197497765),
 (875, 0.6315162347333929),
 (763, 0.6303246946678582),
 (44, 0.6300268096514745),
 (2908, 0.6297289246350909),
 (1137, 0.6297289246350909),
 (604, 0.6279416145367888),
 (1777, 0.6273458445040214),
 (29, 0.6252606493893357),
 (530, 0.6252606493893357),
 (2689, 0.6175156389633601),
 (2927, 0.6163240988978255),
 (1057, 0.6157283288650581),
 (2285, 0.6148346738159071),
 (1359, 0.6145367887995233),
 (164, 0.6133452487339887),
 (3304, 0.6124515936848376),
 (317, 0.6118558236520703),
 (3231, 0.6085790884718498),
 (1611, 0.6073875484063151),
 (1727, 0.6058981233243967),
 (291, 0.6053023532916294),
 (1258, 0.6017277330950253),
 (3276, 0.6011319630622579),
 (224, 0.6008340780458743),
 (2525, 0.5996425379803396),
 (2185, 0.5993446529639559),
 (864, 0.5978552278820375),
 (3023, 0.5978552278820375),
 (3266, 0.5969615728328865),
 (1280, 0.5930890676198987),
 (2837, 0.5930890676198987),
 (1468, 0.5886207923741436),
 (1771, 0.5856419422103069),
 (2617, 0.5838546321120047),
 (485, 0.5838546321120047),
 (2317, 0.5820673220137027),
 (1879, 0.580875781948168),
 (63, 0.580875781948168),
 (1540, 0.5802800119154007),
 (725, 0.5796842418826333),
 (2787, 0.5793863568662496),
 (999, 0.5775990467679476),
 (2228, 0.5755138516532619),
 (2962, 0.572535001489425),
 (1049, 0.5719392314566577),
 (709, 0.570747691391123),
 (1863, 0.569854036341972),
 (622, 0.5686624962764373),
 (2447, 0.5686624962764373),
 (1506, 0.5686624962764373),
 (2817, 0.5665773011617515),
 (776, 0.5662794161453679),
 (345, 0.5659815311289842),
 (1473, 0.5653857610962169),
 (2715, 0.5618111408996127),
 (1759, 0.5615132558832291),
 (2308, 0.5612153708668454),
 (2492, 0.5612153708668454),
 (1442, 0.5609174858504618),
 (2782, 0.5600238308013107),
 (749, 0.5585344057193923),
 (140, 0.5579386356866249),
 (462, 0.5570449806374739),
 (980, 0.5558534405719392),
 (1233, 0.5555555555555556),
 (173, 0.5543640154900208),
 (1921, 0.5519809353589514),
 (516, 0.5507893952934168),
 (2656, 0.5495978552278821),
 (841, 0.548704200178731),
 (1420, 0.5463211200476616),
 (1909, 0.5448316949657432),
 (1593, 0.5439380399165922),
 (1379, 0.5433422698838248),
 (2257, 0.5424486148346738),
 (2926, 0.5415549597855228),
 (2621, 0.5397676496872207),
 (2967, 0.5397676496872207),
 (3240, 0.5397676496872207),
 (444, 0.5382782246053024),
 (3322, 0.5370866845397676),
 (3228, 0.536788799523384),
 (281, 0.536788799523384),
 (2052, 0.5352993744414656),
 (1455, 0.5344057193923145),
 (2637, 0.5338099493595472),
 (430, 0.5338099493595472),
 (1360, 0.5320226392612452),
 (2996, 0.5320226392612452),
 (2750, 0.5320226392612452),
 (659, 0.5299374441465594),
 (2406, 0.5299374441465594),
 (2091, 0.5296395591301757),
 (1398, 0.528448019064641),
 (534, 0.524873398868037),
 (2652, 0.5239797438188859),
 (2781, 0.5221924337205839),
 (2175, 0.5218945487042002),
 (701, 0.5212987786714328),
 (741, 0.5212987786714328),
 (3029, 0.5195114685731308),
 (909, 0.5189156985403635),
 (2561, 0.5156389633601429),
 (1465, 0.5144474232946082),
 (2597, 0.5111706881143878),
 (2628, 0.5105749180816205),
 (3298, 0.5099791480488531),
 (2778, 0.5093833780160858),
 (2569, 0.5087876079833185),
 (448, 0.5075960679177838),
 (561, 0.5075960679177838),
 (273, 0.5072981829014),
 (1661, 0.5067024128686327),
 (3037, 0.505510872803098),
 (125, 0.504617217753947),
 (1427, 0.5034256776884123),
 (21, 0.5013404825737265),
 (2113, 0.5010425975573428),
 (773, 0.49865951742627346),
 (2379, 0.4980637473935061),
 (2273, 0.4980637473935061),
 (1207, 0.4974679773607387),
 (748, 0.4929997021149836),
 (148, 0.49210604706583255),
 (2103, 0.4918081620494489),
 (2101, 0.4897229669347632),
 (1134, 0.48882931188561213),
 (2948, 0.48853142686922846),
 (3219, 0.4882335418528448),
 (2470, 0.4870420017873101),
 (404, 0.48614834673815904),
 (2280, 0.48614834673815904),
 (1221, 0.48406315162347335),
 (1025, 0.48406315162347335),
 (2604, 0.4819779565087876),
 (3186, 0.4807864164432529),
 (673, 0.4804885314268692),
 (2768, 0.4804885314268692),
 (3156, 0.4804885314268692),
 (1212, 0.48019064641048553),
 (1397, 0.4792969913613345),
 (1779, 0.4787012213285672),
 (1528, 0.47750968126303245),
 (91, 0.4769139112302651),
 (873, 0.4769139112302651),
 (2887, 0.47661602621388144),
 (3237, 0.47631814119749777),
 (1435, 0.4754244861483467),
 (466, 0.47512660113196303),
 (3075, 0.47482871611557936),
 (784, 0.474232946082812),
 (52, 0.47393506106642835),
 (2640, 0.4736371760500447),
 (1866, 0.473339291033661),
 (1772, 0.4709562109025916),
 (394, 0.47065832588620793),
 (1171, 0.46976467083705686),
 (1205, 0.46797736073875484),
 (1518, 0.46797736073875484),
 (2797, 0.4676794757223712),
 (3076, 0.4667858206732201),
 (1676, 0.4667858206732201),
 (2607, 0.4647006255585344),
 (282, 0.46291331546023234),
 (2668, 0.46291331546023234),
 (1673, 0.4626154304438487),
 (1104, 0.45874292523086085),
 (633, 0.4575513851653262),
 (1748, 0.4572535001489425),
 (356, 0.45665773011617516),
 (400, 0.45606196008340777),
 (3350, 0.45546619005064043),
 (2532, 0.4548704200178731),
 (2288, 0.45427464998510575),
 (2573, 0.45427464998510575),
 (695, 0.45427464998510575),
 (779, 0.4539767649687221),
 (359, 0.45278522490318734),
 (662, 0.4524873398868037),
 (818, 0.4524873398868037),
 (3235, 0.45218945487042),
 (1432, 0.451295799821269),
 (3090, 0.451295799821269),
 (1187, 0.4509979148048853),
 (2282, 0.45070002978850165),
 (2205, 0.45010425975573426),
 (179, 0.4498063747393506),
 (3183, 0.4495084897229669),
 (3292, 0.44921060470658325),
 (1625, 0.44801906464104857),
 (2870, 0.44772117962466484),
 (2662, 0.44772117962466484),
 (3166, 0.4474232946082812),
 (533, 0.4462317545427465),
 (2245, 0.4459338695263628),
 (758, 0.44504021447721176),
 (266, 0.4447423294608281),
 (2685, 0.4444444444444444),
 (1183, 0.44325290437890974),
 (1636, 0.442061364313375),
 (2650, 0.44146559428060766),
 (1268, 0.441167709264224),
 (3101, 0.4408698242478403),
 (783, 0.4408698242478403),
 (2114, 0.44057193923145666),
 (305, 0.44057193923145666),
 (2603, 0.43967828418230565),
 (322, 0.43967828418230565),
 (75, 0.4384867441167709),
 (1441, 0.43818885910038724),
 (3004, 0.4358057789693178),
 (492, 0.43312481382186474),
 (1984, 0.43312481382186474),
 (1192, 0.43282692880548107),
 (3224, 0.4325290437890974),
 (1598, 0.4325290437890974),
 (2193, 0.4313375037235627),
 (2670, 0.43044384867441166),
 (350, 0.43044384867441166),
 (1492, 0.430145963658028),
 (927, 0.430145963658028),
 (1511, 0.4289544235924933),
 (482, 0.42865653857610964),
 (1671, 0.4283586535597259),
 (777, 0.42776288352695857),
 (1122, 0.42716711349419123),
 (3108, 0.42716711349419123),
 (2421, 0.42686922847780756),
 (1477, 0.4265713434614239),
 (1450, 0.4265713434614239),
 (199, 0.4256776884122729),
 (2416, 0.42537980339588916),
 (2849, 0.42448614834673815),
 (2065, 0.42329460828120347),
 (2063, 0.42210306821566873),
 (3305, 0.42180518319928506),
 (3080, 0.4215072981829014),
 (1341, 0.4215072981829014),
 (1347, 0.4206136431337504),
 (2287, 0.4203157581173667),
 (2784, 0.4203157581173667),
 (371, 0.4203157581173667),
 (1279, 0.4197199880845993),
 (10, 0.41942210306821565),
 (2001, 0.41942210306821565),
 (278, 0.419124218051832),
 (1926, 0.41823056300268097),
 (900, 0.41823056300268097),
 (676, 0.41823056300268097),
 (2682, 0.4179326779862973),
 (1846, 0.4176347929699136),
 (2118, 0.4176347929699136),
 (1415, 0.41674113792076256),
 (1275, 0.4164432529043789),
 (1344, 0.4155495978552279),
 (247, 0.4152517128388442),
 (1108, 0.4152517128388442),
 (785, 0.41495382782246054),
 (2850, 0.41435805778969315),
 (772, 0.4137622877569258),
 (3106, 0.4137622877569258),
 (18, 0.4128686327077748),
 (753, 0.41227286267500746),
 (1672, 0.41227286267500746),
 (142, 0.41227286267500746),
 (1886, 0.41167709264224006),
 (3100, 0.41167709264224006),
 (1191, 0.4113792076258564),
 (2763, 0.4113792076258564),
 (1071, 0.4113792076258564),
 (567, 0.4101876675603217),
 (2231, 0.4101876675603217),
 (583, 0.4101876675603217),
 (2747, 0.4101876675603217),
 (3151, 0.4101876675603217),
 (259, 0.40988978254393804),
 (1630, 0.4086982424784033),
 (2969, 0.4086982424784033),
 (19, 0.40720881739648496),
 (2070, 0.40720881739648496),
 (1943, 0.4069109323801013),
 (2295, 0.4066130473637176),
 (3015, 0.40631516234733395),
 (2046, 0.4060172773309502),
 (54, 0.4054215072981829),
 (1560, 0.40482573726541554),
 (1300, 0.40393208221626453),
 (3244, 0.40393208221626453),
 (2226, 0.40214477211796246),
 (2939, 0.40214477211796246),
 (766, 0.40125111706881145),
 (1131, 0.40125111706881145),
 (2424, 0.40125111706881145),
 (1660, 0.40125111706881145),
 (1962, 0.40125111706881145),
 (1094, 0.40065534703604405),
 (1824, 0.39976169198689304),
 (1281, 0.39946380697050937),
 (2324, 0.3982722669049747),
 (3134, 0.3973786118558236),
 (1756, 0.3967828418230563),
 (382, 0.3964849568066726),
 (2994, 0.39618707179028895),
 (2930, 0.3955913017575216),
 (837, 0.3949955317247542),
 (1589, 0.39469764670837054),
 (3226, 0.39469764670837054),
 (3129, 0.39439976169198687),
 (710, 0.39380399165921953),
 (1874, 0.39350610664283586),
 (2916, 0.3932082216264522),
 (2756, 0.39261245159368485),
 (2440, 0.39261245159368485),
 (145, 0.39201668156091746),
 (1542, 0.3896336014298481),
 (1056, 0.38933571641346437),
 (242, 0.38844206136431336),
 (3252, 0.38754840631516235),
 (1802, 0.386952636282395),
 (2766, 0.3866547512660113),
 (591, 0.3857610962168603),
 (861, 0.3857610962168603),
 (3136, 0.3857610962168603),
 (2460, 0.3854632112004766),
 (2694, 0.3854632112004766),
 (198, 0.38516532618409294),
 (1151, 0.38486744116770927),
 (2117, 0.3845695561513256),
 (1220, 0.38427167113494193),
 (675, 0.38427167113494193),
 (1126, 0.38367590110217453),
 (1342, 0.38337801608579086),
 (520, 0.3827822460530235),
 (679, 0.38159070598748884),
 (2698, 0.3803991659219541),
 (996, 0.37980339588918677),
 (1602, 0.3795055108728031),
 (1493, 0.37920762585641943),
 (38, 0.37920762585641943),
 (1515, 0.37920762585641943),
 (1366, 0.3786118558236521),
 (157, 0.377718200774501),
 (367, 0.37742031575811735),
 (1764, 0.3771224307417337),
 (2443, 0.3771224307417337),
 (2373, 0.37682454572535),
 (2451, 0.37682454572535),
 (1711, 0.3762287756925827),
 (2709, 0.375930890676199),
 (1213, 0.3753351206434316),
 (941, 0.3753351206434316),
 (2918, 0.37503723562704794),
 (2430, 0.37473935061066427),
 (130, 0.3744414655942806),
 (1543, 0.37414358057789693),
 (1431, 0.3735478105451296),
 (2976, 0.3732499255287459),
 (1226, 0.3732499255287459),
 (2856, 0.3732499255287459),
 (204, 0.3726541554959785),
 (1412, 0.3726541554959785),
 (2560, 0.3726541554959785),
 (549, 0.3726541554959785),
 (1887, 0.37235627047959485),
 (2833, 0.3720583854632112),
 (429, 0.3717605004468275),
 (976, 0.3717605004468275),
 (2665, 0.37146261543044384),
 (2733, 0.3711647304140602),
 (2666, 0.3708668453976765),
 (3329, 0.37056896038129283),
 (1775, 0.37056896038129283),
 (3254, 0.3693774203157581),
 (2970, 0.36907953529937443),
 (3172, 0.36907953529937443),
 (1875, 0.36907953529937443),
 (2194, 0.36878165028299076),
 (2174, 0.36878165028299076),
 (1942, 0.3684837652666071),
 (1446, 0.3681858802502234),
 (2495, 0.3681858802502234),
 (1814, 0.3681858802502234),
 (523, 0.3675901102174561),
 (2352, 0.3675901102174561),
 (2209, 0.36520703008638666),
 (934, 0.3643133750372356),
 (57, 0.36401549002085193),
 (2914, 0.36282394995531725),
 (457, 0.3625260649389336),
 (1665, 0.3625260649389336),
 (1794, 0.3616324098897825),
 (902, 0.36133452487339884),
 (344, 0.3610366398570152),
 (598, 0.36044086982424783),
 (2719, 0.36044086982424783),
 (246, 0.36044086982424783),
 (362, 0.36014298480786416),
 (3300, 0.35924932975871315),
 (640, 0.35924932975871315),
 (1652, 0.35895144474232943),
 (2672, 0.35895144474232943),
 (1303, 0.35865355972594576),
 (1955, 0.3583556747095621),
 (1184, 0.35775990467679475),
 (1801, 0.3574620196604111),
 (2558, 0.3574620196604111),
 (422, 0.3571641346440274),
 (928, 0.3571641346440274),
 (860, 0.3559725945784927),
 (1139, 0.355674709562109),
 (1960, 0.355674709562109),
 (2943, 0.355674709562109),
 (532, 0.35537682454572533),
 (3287, 0.35537682454572533),
 (1904, 0.35418528448019065),
 (2325, 0.353887399463807),
 (2653, 0.3535895144474233),
 (577, 0.3532916294310396),
 (112, 0.35269585939827225),
 (1623, 0.35269585939827225),
 (1633, 0.35269585939827225),
 (1273, 0.3523979743818886),
 (1302, 0.35180220434912124),
 (1202, 0.35180220434912124),
 (337, 0.35150431933273757),
 (163, 0.3512064343163539),
 (212, 0.3512064343163539),
 (1146, 0.3512064343163539),
 (1631, 0.3512064343163539),
 (1340, 0.35090854929997023),
 (1362, 0.35090854929997023),
 (2563, 0.35090854929997023),
 (114, 0.3506106642835865),
 (1371, 0.3506106642835865),
 (411, 0.35031277926720283),
 (1248, 0.35031277926720283),
 (2577, 0.35031277926720283),
 (3191, 0.35031277926720283),
 (2102, 0.3497170092344355),
 (2799, 0.3494191242180518),
 (1336, 0.34912123920166815),
 (911, 0.3488233541852845),
 (120, 0.34822758415251714),
 (2922, 0.34822758415251714),
 (250, 0.3479296991361334),
 (3073, 0.3473339291033661),
 (2743, 0.3473339291033661),
 (1325, 0.34644027405421507),
 (704, 0.3461423890378314),
 (2626, 0.3461423890378314),
 (889, 0.34584450402144773),
 (1037, 0.34584450402144773),
 (894, 0.34584450402144773),
 (2090, 0.34554661900506406),
 (1867, 0.34554661900506406),
 (239, 0.3452487339886804),
 (2234, 0.3452487339886804),
 (1026, 0.3452487339886804),
 (2267, 0.34495084897229666),
 (233, 0.3443550789395293),
 (166, 0.3443550789395293),
 (1774, 0.34405719392314565),
 (2620, 0.34405719392314565),
 (2615, 0.343759308906762),
 (2971, 0.343759308906762),
 (998, 0.3434614238903783),
 (1804, 0.3434614238903783),
 (1200, 0.34316353887399464),
 (2902, 0.342865653857611),
 (3213, 0.342865653857611),
 (2112, 0.3422698838248436),
 (1699, 0.3422698838248436),
 (3314, 0.3419719988084599),
 (2794, 0.34167411379207624),
 (1881, 0.34167411379207624),
 (1152, 0.34137622877569257),
 (1368, 0.34137622877569257),
 (2912, 0.3410783437593089),
 (217, 0.34048257372654156),
 (1583, 0.34048257372654156),
 (506, 0.3395889186773905),
 (566, 0.3395889186773905),
 (426, 0.3395889186773905),
 (637, 0.3395889186773905),
 (872, 0.3395889186773905),
 (1744, 0.33899314864462315),
 (1594, 0.3386952636282395),
 (1695, 0.33809949359547214),
 (1383, 0.3378016085790885),
 (793, 0.3378016085790885),
 (2354, 0.3375037235627048),
 (218, 0.33720583854632113),
 (1983, 0.33720583854632113),
 (1407, 0.33661006851355374),
 (1585, 0.33631218349717007),
 (1042, 0.33631218349717007),
 (86, 0.3360142984807864),
 (964, 0.33571641346440273),
 (339, 0.33571641346440273),
 (477, 0.33571641346440273),
 (39, 0.3351206434316354),
 (1595, 0.3351206434316354),
 (361, 0.333631218349717),
 (1554, 0.333631218349717),
 (3126, 0.33303544831694964),
 (722, 0.332737563300566),
 (590, 0.3324396782841823),
 (2107, 0.33214179326779864),
 (1859, 0.33184390825141497),
 (99, 0.3315460232350313),
 (3128, 0.3315460232350313),
 (3077, 0.33124813821864757),
 (2618, 0.33124813821864757),
 (1180, 0.3309502532022639),
 (1557, 0.3297587131367292),
 (2192, 0.3297587131367292),
 (1078, 0.3297587131367292),
 (1935, 0.32946082812034555),
 (1457, 0.3288650580875782),
 (1461, 0.3285671730711945),
 (378, 0.3285671730711945),
 (1414, 0.3285671730711945),
 (1496, 0.3285671730711945),
 (2932, 0.3285671730711945),
 (1417, 0.3282692880548108),
 (1580, 0.32797140303842715),
 (2651, 0.32797140303842715),
 (1746, 0.3273756330056598),
 (3169, 0.3273756330056598),
 (2318, 0.3273756330056598),
 (61, 0.3264819779565088),
 (1194, 0.3264819779565088),
 (2893, 0.3264819779565088),
 (1229, 0.3261840929401251),
 (78, 0.3261840929401251),
 (2713, 0.32588620792374146),
 (2396, 0.32558832290735773),
 (2240, 0.32558832290735773),
 (1902, 0.32529043789097406),
 (831, 0.3249925528745904),
 (2559, 0.3249925528745904),
 (804, 0.3240988978254394),
 (1349, 0.3240988978254394),
 (1265, 0.3238010128090557),
 (143, 0.32290735775990465),
 (3081, 0.322609472743521),
 (1590, 0.322609472743521),
 (424, 0.32201370271075364),
 (2585, 0.3214179326779863),
 (2658, 0.3214179326779863),
 (768, 0.3211200476616026),
 (3180, 0.3211200476616026),
 (973, 0.3211200476616026),
 (2638, 0.3211200476616026),
 (175, 0.32082216264521896),
 (2445, 0.3205242776288353),
 (1357, 0.3205242776288353),
 (292, 0.3199285075960679),
 (969, 0.3199285075960679),
 (674, 0.3199285075960679),
 (2555, 0.3196306225796842),
 (2296, 0.3196306225796842),
 (1605, 0.31933273756330055),
 (1784, 0.31933273756330055),
 (1822, 0.31933273756330055),
 (2702, 0.3190348525469169),
 (1181, 0.31843908251414954),
 (1896, 0.31843908251414954),
 (501, 0.31814119749776587),
 (272, 0.3178433124813822),
 (539, 0.3178433124813822),
 (484, 0.3178433124813822),
 (1572, 0.3172475424486148),
 (2789, 0.3172475424486148),
 (929, 0.31694965743223114),
 (2172, 0.31694965743223114),
 (2811, 0.31694965743223114),
 (3059, 0.31694965743223114),
 (184, 0.31665177241584747),
 (1780, 0.31665177241584747),
 (7, 0.31665177241584747),
 (3000, 0.31665177241584747),
 (1203, 0.31665177241584747),
 (1339, 0.31665177241584747),
 (1338, 0.3163538873994638),
 (1209, 0.3160560023830801),
 (187, 0.3160560023830801),
 (1385, 0.3160560023830801),
 (2929, 0.3160560023830801),
 (463, 0.3151623473339291),
 (959, 0.3151623473339291),
 (134, 0.31486446231754545),
 (2941, 0.31426869228477805),
 (1254, 0.31426869228477805),
 (1551, 0.31426869228477805),
 (1475, 0.31337503723562704),
 (2453, 0.31337503723562704),
 (498, 0.31248138218647603),
 (2334, 0.31248138218647603),
 (1190, 0.31218349717009236),
 (1686, 0.31218349717009236),
 (207, 0.31188561215370864),
 (3164, 0.31158772713732497),
 (2944, 0.31158772713732497),
 (2076, 0.3112898421209413),
 (564, 0.3112898421209413),
 (2771, 0.3109919571045576),
 (2699, 0.3109919571045576),
 (2836, 0.3109919571045576),
 (2980, 0.31069407208817396),
 (1015, 0.31069407208817396),
 (867, 0.3103961870717903),
 (2509, 0.3103961870717903),
 (2710, 0.3103961870717903),
 (2116, 0.3100983020554066),
 (2808, 0.3100983020554066),

In [17]:
dcentralities2

{1: 0.20673220137027107,
 4: 0.3065236818588025,
 10: 0.41942210306821565,
 14: 0.1620494489127197,
 21: 0.5013404825737265,
 23: 0.7044980637473935,
 29: 0.6252606493893357,
 33: 0.18915698540363418,
 34: 0.09949359547214776,
 44: 0.6300268096514745,
 47: 0.27047959487637774,
 52: 0.47393506106642835,
 61: 0.3264819779565088,
 72: 0.1546023235031278,
 73: 0.11826035150431934,
 75: 0.4384867441167709,
 76: 0.1778373547810545,
 77: 0.11021745606196008,
 82: 0.0816204944891272,
 98: 0.035746201966041107,
 99: 0.3315460232350313,
 111: 0.26630920464700625,
 124: 0.7566279416145367,
 125: 0.504617217753947,
 126: 0.18379505510872804,
 127: 0.20285969615728328,
 129: 0.12332439678284182,
 131: 0.7080726839439976,
 133: 0.7372654155495978,
 145: 0.39201668156091746,
 148: 0.49210604706583255,
 152: 0.08698242478403335,
 160: 0.07208817396484957,
 164: 0.6133452487339887,
 170: 0.20613643133750373,
 184: 0.31665177241584747,
 198: 0.38516532618409294,
 200: 0.17992254989574025,
 204: 0.3726541554959785,
 214: 0.2817992254989574,
 215: 0.2103068215668752,
 221: 0.128686327077748,
 222: 0.19302949061662197,
 223: 0.11408996127494787,
 224: 0.6008340780458743,
 225: 0.21656240691093237,
 229: 0.2734584450402145,
 233: 0.3443550789395293,
 239: 0.3452487339886804,
 242: 0.38844206136431336,
 243: 0.22639261245159367,
 245: 0.1620494489127197,
 248: 0.2088173964849568,
 258: 0.2064343163538874,
 259: 0.40988978254393804,
 261: 0.28865058087578194,
 266: 0.4447423294608281,
 283: 0.28150134048257375,
 292: 0.3199285075960679,
 302: 0.17605004468275245,
 303: 0.2323503127792672,
 310: 0.1420911528150134,
 337: 0.35150431933273757,
 342: 0.20613643133750373,
 353: 0.21268990169794458,
 354: 0.1471551980935359,
 361: 0.333631218349717,
 366: 0.8370568960381293,
 369: 0.2844801906464105,
 372: 0.22609472743521,
 374: 0.23681858802502234,
 377: 0.1691986893059279,
 381: 0.17009234435507894,
 393: 0.11349419124218052,
 400: 0.45606196008340777,
 402: 0.2752457551385165,
 409: 0.24813821864760202,
 410: 0.18498659517426272,
 411: 0.35031277926720283,
 421: 0.16473041406017278,
 422: 0.3571641346440274,
 429: 0.3717605004468275,
 442: 0.25767053917187965,
 443: 0.19332737563300564,
 448: 0.5075960679177838,
 452: 0.7101578790586833,
 458: 0.17039022937146261,
 481: 0.16592195412570748,
 482: 0.42865653857610964,
 489: 0.24932975871313673,
 492: 0.43312481382186474,
 500: 0.2719690199582961,
 504: 0.25767053917187965,
 506: 0.3395889186773905,
 515: 0.21834971700923442,
 516: 0.5507893952934168,
 518: 0.19213583556747096,
 520: 0.3827822460530235,
 530: 0.6252606493893357,
 531: 0.8835269585939827,
 534: 0.524873398868037,
 536: 0.12838844206136432,
 543: 0.07536490914507,
 558: 0.1423890378313971,
 559: 0.16473041406017278,
 566: 0.3395889186773905,
 567: 0.4101876675603217,
 568: 0.20226392612451594,
 569: 0.2597557342865654,
 570: 0.16234733392910336,
 577: 0.3532916294310396,
 591: 0.3857610962168603,
 596: 0.9195710455764075,
 598: 0.36044086982424783,
 604: 0.6279416145367888,
 607: 0.2779267202859696,
 609: 0.23443550789395293,
 617: 0.13136729222520108,
 622: 0.5686624962764373,
 627: 0.2624366994340185,
 636: 0.19005064045278522,
 645: 0.15192135835567472,
 648: 0.0902591599642538,
 649: 0.11170688114387846,
 651: 0.1954125707476914,
 657: 0.171879654453381,
 659: 0.5299374441465594,
 662: 0.4524873398868037,
 670: 0.09085492999702115,
 671: 0.17813523979743817,
 673: 0.4804885314268692,
 692: 0.23056300268096513,
 693: 0.12540959189752754,
 704: 0.3461423890378314,
 709: 0.570747691391123,
 714: 0.2826928805481084,
 723: 0.26630920464700625,
 725: 0.5796842418826333,
 731: 0.16264521894548703,
 738: 0.1817098599940423,
 739: 0.7765862377122431,
 742: 0.1840929401251117,
 749: 0.5585344057193923,
 753: 0.41227286267500746,
 755: 0.13434614238903783,
 760: 0.1593684837652666,
 762: 0.27047959487637774,
 764: 0.2779267202859696,
 766: 0.40125111706881145,
 768: 0.3211200476616026,
 770: 0.2853738456955615,
 773: 0.49865951742627346,
 776: 0.5662794161453679,
 777: 0.42776288352695857,
 778: 0.2347333929103366,
 779: 0.4539767649687221,
 780: 0.11706881143878463,
 784: 0.474232946082812,
 786: 0.7044980637473935,
 792: 0.11021745606196008,
 795: 0.17098599940422995,
 796: 0.1593684837652666,
 798: 0.1456657730116175,
 800: 0.19809353589514447,
 801: 0.11379207625856419,
 802: 0.21090259159964253,
 804: 0.3240988978254394,
 812: 0.19005064045278522,
 818: 0.4524873398868037,
 825: 0.20732797140303844,
 826: 0.17545427464998511,
 834: 0.14179326779862972,
 836: 0.2618409294012511,
 837: 0.3949955317247542,
 838: 0.2100089365504915,
 840: 0.1605600238308013,
 841: 0.548704200178731,
 843: 0.1927316056002383,
 847: 0.2993744414655943,
 850: 0.2907357759904677,
 852: 0.22698838248436104,
 861: 0.3857610962168603,
 864: 0.5978552278820375,
 867: 0.3103961870717903,
 875: 0.6315162347333929,
 885: 0.13523979743818887,
 887: 0.13523979743818887,
 888: 0.22341376228775692,
 889: 0.34584450402144773,
 902: 0.36133452487339884,
 903: 0.2943103961870718,
 908: 0.1739648495680667,
 911: 0.3488233541852845,
 915: 0.6812630324694667,
 924: 0.08251414953827822,
 931: 0.1483467381590706,
 937: 0.13643133750372355,
 950: 0.15966636878165028,
 964: 0.33571641346440273,
 965: 0.7071790288948466,
 969: 0.3199285075960679,
 971: 0.7199880845993446,
 980: 0.5558534405719392,
 982: 0.09949359547214776,
 985: 0.18081620494489126,
 992: 0.20554066130473636,
 996: 0.37980339588918677,
 998: 0.3434614238903783,
 1005: 0.30294906166219837,
 1014: 0.20077450104259756,
 1028: 0.07625856419422103,
 1034: 0.10932380101280906,
 1041: 0.1420911528150134,
 1048: 0.14387846291331546,
 1049: 0.5719392314566577,
 1053: 0.12153708668453976,
 1054: 0.11587727137324992,
 1055: 0.6657730116175157,
 1057: 0.6157283288650581,
 1073: 0.21834971700923442,
 1093: 0.7036044086982425,
 1101: 0.19213583556747096,
 1102: 0.2806076854334227,
 1104: 0.45874292523086085,
 1106: 0.20554066130473636,
 1114: 0.22311587727137325,
 1117: 0.107536490914507,
 1122: 0.42716711349419123,
 1131: 0.40125111706881145,
 1133: 0.1778373547810545,
 1134: 0.48882931188561213,
 1135: 0.09711051534107834,
 1140: 0.18617813523979743,
 1158: 0.19988084599344652,
 1166: 0.21328567173071195,
 1176: 0.2907357759904677,
 1178: 0.18588025022341376,
 1181: 0.31843908251414954,
 1183: 0.44325290437890974,
 1186: 0.24426571343461423,
 1187: 0.4509979148048853,
 1188: 0.1334524873398868,
 1190: 0.31218349717009236,
 1191: 0.4113792076258564,
 1192: 0.43282692880548107,
 1193: 0.3053321417932678,
 1194: 0.3264819779565088,
 1196: 0.26541554959785524,
 1198: 0.16026213881441764,
 1199: 0.14864462317545427,
 1201: 0.14536788799523384,
 1205: 0.46797736073875484,
 1206: 0.2660113196306226,
 1207: 0.4974679773607387,
 1209: 0.3160560023830801,
 1212: 0.48019064641048553,
 1215: 0.15996425379803395,
 1231: 0.27137324992552875,
 1233: 0.5555555555555556,
 1237: 0.1864760202561811,
 1244: 0.14030384271671134,
 1246: 0.2386058981233244,
 1258: 0.6017277330950253,
 1280: 0.5930890676198987,
 1281: 0.39946380697050937,
 1296: 0.8001191540065534,
 1298: 0.12094131665177241,
 1299: 0.25409591897527556,
 1300: 0.40393208221626453,
 1301: 0.3026511766458147,
 1302: 0.35180220434912124,
 1303: 0.35865355972594576,
 1305: 0.1966041108132261,
 1306: 0.18439082514149538,
 1308: 0.22549895740244266,
 1309: 0.2642240095323205,
 1313: 0.23741435805778968,
 1314: 0.1986893059279118,
 1320: 0.16353887399463807,
 1334: 0.10634495084897229,
 1335: 0.6621983914209115,
 1340: 0.35090854929997023,
 1342: 0.38337801608579086,
 1359: 0.6145367887995233,
 1360: 0.5320226392612452,
 1361: 0.6318141197497765,
 1362: 0.35090854929997023,
 1363: 0.24158474828716114,
 1369: 0.14179326779862972,
 1379: 0.5433422698838248,
 1383: 0.3378016085790885,
 1388: 0.6353887399463807,
 1398: 0.528448019064641,
 1399: 0.21566875186178136,
 1404: 0.2162645218945487,
 1405: 0.18736967530533213,
 1407: 0.33661006851355374,
 1412: 0.3726541554959785,
 1413: 0.7140303842716711,
 1415: 0.41674113792076256,
 1424: 0.21656240691093237,
 1425: 0.17813523979743817,
 1426: 0.19481680071492405,
 1427: 0.5034256776884123,
 1431: 0.3735478105451296,
 1434: 0.16949657432231158,
 1436: 0.7006255585344057,
 1441: 0.43818885910038724,
 1443: 0.2746499851057492,
 1444: 0.17873100983020554,
 1445: 0.2555853440571939,
 1446: 0.3681858802502234,
 1451: 0.17605004468275245,
 1453: 0.2862675007447125,
 1461: 0.3285671730711945,
 1462: 0.8129282097110515,
 1465: 0.5144474232946082,
 1470: 0.07357759904676794,
 1477: 0.4265713434614239,
 1492: 0.430145963658028,
 1493: 0.37920762585641943,
 1494: 0.1730711945189157,
 1501: 0.21477509681263032,
 1528: 0.47750968126303245,
 1529: 0.1546023235031278,
 1540: 0.5802800119154007,
 1549: 0.11587727137324992,
 1560: 0.40482573726541554,
 1572: 0.3172475424486148,
 1576: 0.17217753946976466,
 1577: 0.14149538278224605,
 1578: 0.270181709859994,
 1580: 0.32797140303842715,
 1581: 0.22043491212392016,
 1584: 0.1358355674709562,
 1585: 0.33631218349717007,
 1587: 0.16592195412570748,
 1591: 0.193923145665773,
 1592: 0.7485850461721775,
 1593: 0.5439380399165922,
 1600: 0.2779267202859696,
 1625: 0.44801906464104857,
 1629: 0.13285671730711945,
 1637: 0.13613345248733988,
 1638: 0.29103366100685135,
 1652: 0.35895144474232943,
 1667: 0.2955019362526065,
 1671: 0.4283586535597259,
 1684: 0.1966041108132261,
 1687: 0.259159964253798,
 1688: 0.2990765564492106,
 1690: 0.2767351802204349,
 1706: 0.6499851057491808,
 1713: 0.128686327077748,
 1727: 0.6058981233243967,
 1728: 0.906166219839142,
 1730: 0.21924337205838546,
 1731: 0.13762287756925826,
 1754: 0.6505808757819481,
 1756: 0.3967828418230563,
 1758: 0.11051534107834375,
 1763: 0.19719988084599344,
 1764: 0.3771224307417337,
 1766: 0.17247542448614833,
 1769: 0.13404825737265416,
 1771: 0.5856419422103069,
 1772: 0.4709562109025916,
 1773: 0.2213285671730712,
 1780: 0.31665177241584747,
 1796: 0.16353887399463807,
 1798: 0.14179326779862972,
 1799: 0.15907059874888294,
 1819: 0.6574322311587727,
 1821: 0.17843312481382187,
 1824: 0.39976169198689304,
 1859: 0.33184390825141497,
 1863: 0.569854036341972,
 1864: 0.1111111111111111,
 1866: 0.473339291033661,
 1872: 0.7980339588918677,
 1878: 0.2719690199582961,
 1879: 0.580875781948168,
 1894: 0.2103068215668752,
 1902: 0.32529043789097406,
 1920: 0.139708072683944,
 1921: 0.5519809353589514,
 1943: 0.4069109323801013,
 1948: 0.11438784629133154,
 1954: 0.1554959785522788,
 1955: 0.3583556747095621,
 1956: 0.2025618111408996,
 1966: 0.18319928507596067,
 1972: 0.1307715221924337,
 1975: 0.18022043491212392,
 1976: 0.1766458147155198,
 1979: 0.15758117366696456,
 1991: 0.14536788799523384,
 1993: 0.1224307417336908,
 1994: 0.21954125707476912,
 1997: 0.26124515936848375,
 2007: 0.1989871909442955,
 2028: 0.2201370271075365,
 2043: 0.13494191242180517,
 2046: 0.4060172773309502,
 2052: 0.5352993744414656,
 2053: 0.24515936848376527,
 2056: 0.28120345546619,
 2059: 0.15251712838844206,
 2060: 0.13315460232350312,
 2063: 0.42210306821566873,
 2066: 0.22281799225498958,
 2076: 0.3112898421209413,
 2083: 0.6687518617813524,
 2087: 0.6344950848972296,
 2089: 0.268394399761692,
 2090: 0.34554661900506406,
 2091: 0.5296395591301757,
 2092: 0.8010128090557045,
 2093: 0.11706881143878463,
 2099: 0.11051534107834375,
 2105: 0.23830801310694072,
 2106: 0.13494191242180517,
 2137: 0.6878165028299077,
 2142: 0.26035150431933274,
 2144: 0.26362823949955316,
 2153: 0.12392016681560918,
 2155: 0.14626154304438485,
 2156: 0.2320524277628835,
 2158: 0.11289842120941317,
 2163: 0.09353589514447423,
 2166: 0.2966934763181412,
 2175: 0.5218945487042002,
 2177: 0.20851951146857312,
 2182: 0.08430145963658028,
 2184: 0.7327971403038427,
 2185: 0.5993446529639559,
 2186: 0.12809055704498062,
 2187: 0.10783437593089068,
 2191: 0.8060768543342269,
 2203: 0.20345546619005064,
 2217: 0.22907357759904676,
 2220: 0.6410485552576706,
 2226: 0.40214477211796246,
 2228: 0.5755138516532619,
 2231: 0.4101876675603217,
 2232: 0.2037533512064343,
 2233: 0.2752457551385165,
 2239: 0.24635090854929997,
 2245: 0.4459338695263628,
 2247: 0.14536788799523384,
 2251: 0.2210306821566875,
 2253: 0.21537086684539766,
 2257: 0.5424486148346738,
 2264: 0.26005361930294907,
 2267: 0.34495084897229666,
 2284: 0.14894250819183794,
 2285: 0.6148346738159071,
 2286: 0.14864462317545427,
 2287: 0.4203157581173667,
 2288: 0.45427464998510575,
 2301: 0.28150134048257375,
 2308: 0.5612153708668454,
 2309: 0.2728626750074471,
 2310: 0.24813821864760202,
 2312: 0.13672922252010725,
 2313: 0.2675007447125409,
 2316: 0.2514149538278225,
 2326: 0.19809353589514447,
 2328: 0.26779862972892465,
 2344: 0.19511468573130772,
 2350: 0.14745308310991956,
 2366: 0.09859994042299672,
 2370: 0.21298778671432828,
 2371: 0.18260351504319333,
 2373: 0.37682454572535,
 2378: 0.8826333035448317,
 2379: 0.4980637473935061,
 2385: 0.13196306225796842,
 2387: 0.2889484658921656,
 2392: 0.13017575215966637,
 2396: 0.32558832290735773,
 2399: 0.19839142091152814,
 2402: 0.2731605600238308,
 2411: 0.2287756925826631,
 2413: 0.16085790884718498,
 2415: 0.0938337801608579,
 2419: 0.9243372058385463,
 2421: 0.42686922847780756,
 2422: 0.6934763181411975,
 2423: 0.25260649389335715,
 2424: 0.40125111706881145,
 2438: 0.7092642240095323,
 2451: 0.37682454572535,
 2454: 0.14804885314268693,
 2457: 0.7846291331546023,
 2460: 0.3854632112004766,
 2470: 0.4870420017873101,
 2471: 0.2990765564492106,
 2480: 0.21924337205838546,
 2481: 0.17992254989574025,
 2483: 0.12511170688114387,
 2485: 0.16830503425677687,
 2491: 0.29371462615430444,
 2492: 0.5612153708668454,
 2493: 0.14745308310991956,
 2495: 0.3681858802502234,
 2501: 0.15787905868334823,
 2503: 0.1671134941912422,
 2505: 0.12332439678284182,
 2522: 0.20792374143580578,
 2527: 0.15370866845397677,
 2532: 0.4548704200178731,
 2533: 0.1495382782246053,
 2535: 0.2767351802204349,
 2536: 0.12809055704498062,
 2537: 0.6940720881739648,
 2541: 0.12392016681560918,
 2542: 0.18528448019064642,
 2560: 0.3726541554959785,
 2565: 0.13196306225796842,
 2571: 0.24069109323801013,
 2583: 0.18230563002680963,
 2584: 0.2037533512064343,
 2585: 0.3214179326779863,
 2591: 0.7170092344355079,
 2594: 0.2707774798927614,
 2603: 0.43967828418230565,
 2612: 0.14626154304438485,
 2617: 0.5838546321120047,
 2621: 0.5397676496872207,
 2624: 0.2826928805481084,
 2626: 0.3461423890378314,
 2628: 0.5105749180816205,
 2637: 0.5338099493595472,
 2645: 0.16085790884718498,
 2649: 0.2409889782543938,
 2651: 0.32797140303842715,
 2652: 0.5239797438188859,
 2653: 0.3535895144474233,
 2654: 0.3026511766458147,
 2655: 0.24605302353291628,
 2656: 0.5495978552278821,
 2657: 0.28358653559725944,
 2660: 0.17813523979743817,
 2663: 0.785820673220137,
 2664: 0.8796544533809949,
 2669: 0.24128686327077747,
 2670: 0.43044384867441166,
 2671: 0.13434614238903783,
 2673: 0.2615430443848674,
 2675: 0.22907357759904676,
 2689: 0.6175156389633601,
 2690: 0.1593684837652666,
 2694: 0.3854632112004766,
 2703: 0.270181709859994,
 2706: 0.10723860589812333,
 2717: 0.16621983914209115,
 2719: 0.36044086982424783,
 2723: 0.3008638665475126,
 2725: 0.25856419422103066,
 2731: 0.15966636878165028,
 2736: 0.6481977956508788,
 2752: 0.28835269585939827,
 2762: 0.15966636878165028,
 2763: 0.4113792076258564,
 2764: 0.14268692284778076,
 2765: 0.09502532022639261,
 2766: 0.3866547512660113,
 2768: 0.4804885314268692,
 2769: 0.09234435507893952,
 2771: 0.3109919571045576,
 2781: 0.5221924337205839,
 2782: 0.5600238308013107,
 2784: 0.4203157581173667,
 2785: 0.2871611557938636,
 2787: 0.5793863568662496,
 2794: 0.34167411379207624,
 2795: 0.6508787607983318,
 2797: 0.4676794757223712,
 2804: 0.30294906166219837,
 2812: 0.6830503425677689,
 2815: 0.16621983914209115,
 2828: 0.12838844206136432,
 2831: 0.29222520107238603,
 2850: 0.41435805778969315,
 2870: 0.44772117962466484,
 2879: 0.22341376228775692,
 2881: 0.1373249925528746,
 2885: 0.10962168602919273,
 2887: 0.47661602621388144,
 2890: 0.1641346440274054,
 2891: 0.25618111408996125,
 2893: 0.3264819779565088,
 2897: 0.685731307715222,
 2902: 0.342865653857611,
 2907: 0.2841823056300268,
 2908: 0.6297289246350909,
 2916: 0.3932082216264522,
 2917: 0.22073279714030383,
 2918: 0.37503723562704794,
 2921: 0.19958296097706285,
 2926: 0.5415549597855228,
 2941: 0.31426869228477805,
 2953: 0.6943699731903485,
 2954: 0.1790288948465892,
 2956: 0.22549895740244266,
 2959: 0.12779267202859695,
 2964: 0.2457551385165326,
 2965: 0.8030980041703902,
 2967: 0.5397676496872207,
 2970: 0.36907953529937443,
 2974: 0.17456061960083408,
 2979: 0.29192731605600236,
 2985: 0.17485850461721775,
 2995: 0.6565385761096216,
 2996: 0.5320226392612452,
 2997: 0.7902889484658921,
 3010: 0.7545427464998511,
 3016: 0.18856121537086684,
 3017: 0.11468573130771521,
 3020: 0.29877867143282694,
 3022: 0.20196604110813227,
 3023: 0.5978552278820375,
 3026: 0.7044980637473935,
 3027: 0.18945487042001788,
 3034: 0.28507596067917784,
 3037: 0.505510872803098,
 3040: 0.2695859398272267,
 3047: 0.755436401549002,
 3053: 0.19958296097706285,
 3054: 0.21328567173071195,
 3058: 0.2335418528448019,
 3064: 0.12004766160262138,
 3073: 0.3473339291033661,
 3075: 0.47482871611557936,
 3076: 0.4667858206732201,
 3077: 0.33124813821864757,
 3080: 0.4215072981829014,
 3081: 0.322609472743521,
 3097: 0.7908847184986595,
 3108: 0.42716711349419123,
 3109: 0.63777182007745,
 3116: 0.13196306225796842,
 3121: 0.2618409294012511,
 3122: 0.24158474828716114,
 3124: 0.6338993148644623,
 3129: 0.39439976169198687,
 3132: 0.30563002680965146,
 3136: 0.3857610962168603,
 3140: 0.14000595770032767,
 3148: 0.13255883229073578,
 3163: 0.06285373845695562,
 3164: 0.31158772713732497,
 3166: 0.4474232946082812,
 3167: 0.6526660708966339,
 3172: 0.36907953529937443,
 3180: 0.3211200476616026,
 3185: 0.2615430443848674,
 3186: 0.4807864164432529,
 3188: 0.13404825737265416,
 3203: 0.15132558832290735,
 3210: 0.7399463806970509,
 3211: 0.26899016979445933,
 3212: 0.17217753946976466,
 3213: 0.342865653857611,
 3228: 0.536788799523384,
 3240: 0.5397676496872207,
 3241: 0.18975275543640155,
 3244: 0.40393208221626453,
 3245: 0.20792374143580578,
 3247: 0.7047959487637772,
 3252: 0.38754840631516235,
 3259: 0.26392612451593683,
 3261: 0.10783437593089068,
 3264: 0.9261245159368483,
 3266: 0.5969615728328865,
 3269: 0.2955019362526065,
 3270: 0.26899016979445933,
 3276: 0.6011319630622579,
 3278: 0.3077152219243372,
 3281: 0.1522192433720584,
 3294: 0.2112004766160262,
 3295: 0.17456061960083408,
 3298: 0.5099791480488531,
 3300: 0.35924932975871315,
 3304: 0.6124515936848376,
 3305: 0.42180518319928506,
 3318: 0.20822162645218945,
 3319: 0.23056300268096513,
 3322: 0.5370866845397676,
 3323: 0.25350014894250816,
 3325: 0.27822460530235327,
 3326: 0.2237116473041406,
 3357: 0.18468871015787905,
 3358: 0.118558236520703,
 2: 0.07745010425975574,
 26: 0.18826333035448317,
 32: 0.1730711945189157,
 70: 0.3065236818588025,
 91: 0.4769139112302651,
 147: 0.22073279714030383,
 163: 0.3512064343163539,
 186: 0.6797736073875484,
 187: 0.3160560023830801,
 195: 0.29848078641644327,
 202: 0.15370866845397677,
 213: 0.11796246648793565,
 217: 0.34048257372654156,
 246: 0.36044086982424783,
 247: 0.4152517128388442,
 250: 0.3479296991361334,
 251: 0.26899016979445933,
 257: 0.1766458147155198,
 319: 0.16026213881441764,
 320: 0.15668751861781352,
 339: 0.33571641346440273,
 376: 0.2496276437295204,
 394: 0.47065832588620793,
 439: 0.21596663687816503,
 464: 0.2624366994340185,
 483: 0.17634792969913612,
 486: 0.19928507596067918,
 523: 0.3675901102174561,
 533: 0.4462317545427465,
 554: 0.22311587727137325,
 555: 0.13285671730711945,
 595: 0.19451891569854035,
 619: 0.09562109025915996,
 635: 0.09859994042299672,
 706: 0.2963955913017575,
 758: 0.44504021447721176,
 781: 0.15519809353589514,
 785: 0.41495382782246054,
 799: 0.23145665773011617,
 803: 0.24158474828716114,
 806: 0.1423890378313971,
 827: 0.14268692284778076,
 860: 0.3559725945784927,

In [18]:
dcentralities2[2220] # centraility of PCR in Jan

0.6410485552576706

In [19]:
target_word = text_jan['label'][2219]
target_word

'pcr'

In [ ]:
The most central node in

In [20]:
americanNeighbors = g2.neighbors(2220)
g_sub2 = g2.subgraph(americanNeighbors)
print(nx.info(g_sub2))

Name:
Type: Graph
Number of nodes: 2152
Number of edges: 743870
Average degree: 691.3290

In [42]:
dcentralities_gsub = nx.degree_centrality(g_sub2)
s_dcentralities_gsub=sorted(dcentralities_gsub.items(), reverse = True, key = lambda x:x[1])

In [43]:
s_dcentralities_gsub

[(3264, 0.9781496978149697),
 (596, 0.9725708972570897),
 (2664, 0.9493258949325895),
 (2419, 0.9386331938633193),
 (1728, 0.9344490934449093),
 (366, 0.9228265922826592),
 (531, 0.911668991166899),
 (2378, 0.8921431892143189),
 (2457, 0.8898186889818689),
 (133, 0.8786610878661087),
 (2663, 0.8749418874941888),
 (3097, 0.8586703858670386),
 (1296, 0.8558809855880986),
 (1462, 0.8540213854021386),
 (2191, 0.8512319851231985),
 (2184, 0.8498372849837285),
 (2092, 0.8475127847512784),
 (1872, 0.8437935843793584),
 (551, 0.8423988842398884),
 (3247, 0.8349604834960483),
 (1592, 0.8340306834030683),
 (124, 0.8247326824732683),
 (186, 0.8224081822408182),
 (131, 0.8214783821478382),
 (2317, 0.8214783821478382),
 (2965, 0.8210134821013482),
 (3210, 0.8210134821013482),
 (2591, 0.8186889818688982),
 (2736, 0.8163644816364481),
 (1093, 0.8131101813110181),
 (3047, 0.8107856810785681),
 (915, 0.8089260808926081),
 (1413, 0.805671780567178),
 (2997, 0.805206880520688),
 (23, 0.801487680148768),
 (2809, 0.800557880055788),
 (971, 0.798698279869828),
 (739, 0.7973035797303579),
 (2953, 0.7973035797303579),
 (1436, 0.795908879590888),
 (1825, 0.7889353788935378),
 (3010, 0.7880055788005579),
 (2841, 0.7824267782426778),
 (2422, 0.7810320781032077),
 (2067, 0.7717340771734077),
 (452, 0.7694095769409577),
 (2438, 0.7633658763365876),
 (2795, 0.7615062761506276),
 (59, 0.7601115760111575),
 (1732, 0.7596466759646676),
 (1359, 0.7545327754532776),
 (1322, 0.7540678754067875),
 (965, 0.7526731752673175),
 (604, 0.7508135750813575),
 (1361, 0.7443049744304974),
 (786, 0.7429102742910274),
 (44, 0.7401208740120874),
 (3266, 0.7387261738726174),
 (1335, 0.7298930729893073),
 (1819, 0.7289632728963272),
 (2995, 0.7271036727103672),
 (2119, 0.7271036727103672),
 (1829, 0.7238493723849372),
 (1055, 0.7233844723384472),
 (2185, 0.7224546722454672),
 (2908, 0.7219897721989772),
 (164, 0.7205950720595072),
 (3026, 0.7187354718735471),
 (3109, 0.7182705718270571),
 (29, 0.7154811715481171),
 (3167, 0.7136215713621571),
 (1468, 0.7112970711297071),
 (224, 0.7108321710832171),
 (1727, 0.7108321710832171),
 (530, 0.705253370525337),
 (2812, 0.703393770339377),
 (749, 0.702928870292887),
 (2715, 0.701999070199907),
 (1611, 0.701069270106927),
 (1258, 0.699674569967457),
 (2137, 0.699674569967457),
 (2537, 0.6973500697350069),
 (140, 0.6973500697350069),
 (2689, 0.696885169688517),
 (763, 0.6959553695955369),
 (3276, 0.6945606694560669),
 (291, 0.6894467689446768),
 (1733, 0.6889818688981869),
 (1280, 0.6885169688516969),
 (2897, 0.6885169688516969),
 (1706, 0.6847977684797768),
 (2228, 0.6843328684332868),
 (1540, 0.6838679683867969),
 (1771, 0.6796838679683868),
 (2837, 0.6792189679218967),
 (2083, 0.6787540678754068),
 (1879, 0.6745699674569967),
 (3240, 0.6741050674105067),
 (65, 0.6731752673175267),
 (2817, 0.6717805671780567),
 (317, 0.6708507670850767),
 (1754, 0.6689911668991166),
 (1921, 0.6652719665271967),
 (875, 0.6648070664807066),
 (1388, 0.6629474662947467),
 (1863, 0.6624825662482566),
 (1759, 0.6624825662482566),
 (1420, 0.6615527661552766),
 (2656, 0.6596931659693166),
 (63, 0.6582984658298465),
 (1777, 0.6569037656903766),
 (2781, 0.6564388656438865),
 (1465, 0.6559739655973965),
 (3023, 0.6559739655973965),
 (1137, 0.6559739655973965),
 (2087, 0.6555090655509065),
 (2787, 0.6545792654579266),
 (3304, 0.6531845653184565),
 (1661, 0.6508600650860065),
 (1049, 0.6494653649465365),
 (2257, 0.6494653649465365),
 (659, 0.6443514644351465),
 (2927, 0.6424918642491864),
 (3231, 0.6397024639702463),
 (1427, 0.6392375639237564),
 (485, 0.6392375639237564),
 (864, 0.6383077638307764),
 (2285, 0.6373779637377963),
 (1360, 0.6369130636913064),
 (1442, 0.6364481636448164),
 (776, 0.6355183635518363),
 (2091, 0.6341236634123664),
 (444, 0.6336587633658763),
 (2447, 0.6336587633658763),
 (1057, 0.6317991631799162),
 (1506, 0.6308693630869363),
 (430, 0.6304044630404463),
 (345, 0.6266852626685262),
 (3228, 0.6234309623430963),
 (3037, 0.6225011622501162),
 (1473, 0.6220362622036262),
 (2175, 0.6197117619711762),
 (873, 0.6183170618317062),
 (725, 0.6178521617852162),
 (3124, 0.6178521617852162),
 (2782, 0.6155276615527662),
 (448, 0.6145978614597861),
 (2962, 0.6118084611808461),
 (2621, 0.6113435611343561),
 (2668, 0.6099488609948861),
 (534, 0.6071594607159461),
 (1233, 0.606694560669456),
 (2617, 0.606229660622966),
 (2492, 0.6052998605299861),
 (1909, 0.603905160390516),
 (2113, 0.601115760111576),
 (21, 0.600650860065086),
 (1866, 0.5960018596001859),
 (173, 0.5960018596001859),
 (2797, 0.5950720595072059),
 (2662, 0.5936773593677359),
 (3219, 0.5936773593677359),
 (2926, 0.5932124593212459),
 (909, 0.5927475592747559),
 (462, 0.5890283589028359),
 (709, 0.5862389586238959),
 (404, 0.5857740585774058),
 (2525, 0.5843793584379359),
 (999, 0.5834495583449558),
 (91, 0.5815899581589958),
 (2750, 0.5811250581125058),
 (622, 0.5801952580195258),
 (701, 0.5801952580195258),
 (1025, 0.5801952580195258),
 (2273, 0.5797303579730357),
 (2569, 0.5774058577405857),
 (125, 0.5764760576476058),
 (741, 0.5750813575081357),
 (2640, 0.5736866573686658),
 (1772, 0.5732217573221757),
 (1347, 0.5727568572756857),
 (779, 0.5722919572291957),
 (3322, 0.5713621571362157),
 (633, 0.5713621571362157),
 (980, 0.5662482566248257),
 (2597, 0.5662482566248257),
 (2967, 0.5648535564853556),
 (2308, 0.5639237563923756),
 (2948, 0.5639237563923756),
 (662, 0.5634588563458857),
 (1398, 0.5634588563458857),
 (1397, 0.5634588563458857),
 (281, 0.5625290562529056),
 (818, 0.5615992561599256),
 (2280, 0.5611343561134355),
 (1593, 0.5602045560204556),
 (273, 0.5602045560204556),
 (758, 0.5597396559739656),
 (400, 0.5588098558809855),
 (1435, 0.5583449558344956),
 (356, 0.5578800557880056),
 (1104, 0.5569502556950255),
 (2628, 0.5564853556485355),
 (516, 0.5560204556020455),
 (561, 0.5560204556020455),
 (3029, 0.5550906555090656),
 (1984, 0.5541608554160855),
 (54, 0.5532310553231055),
 (2205, 0.5527661552766155),
 (305, 0.5523012552301255),
 (2052, 0.5518363551836355),
 (2406, 0.5495118549511855),
 (1779, 0.5490469549046955),
 (927, 0.5462575546257554),
 (3100, 0.5457926545792654),
 (773, 0.5453277545327755),
 (1221, 0.5439330543933054),
 (2652, 0.5434681543468154),
 (3298, 0.5434681543468154),
 (1171, 0.5425383542538355),
 (2604, 0.5425383542538355),
 (1108, 0.5420734542073454),
 (748, 0.5411436541143654),
 (3076, 0.5402138540213853),
 (841, 0.5388191538819154),
 (1183, 0.5383542538354253),
 (2046, 0.5383542538354253),
 (1379, 0.5374244537424454),
 (2996, 0.5369595536959554),
 (394, 0.5346350534635054),
 (2103, 0.5337052533705253),
 (2114, 0.5318456531845653),
 (1671, 0.5290562529056253),
 (3156, 0.5285913528591353),
 (1344, 0.5281264528126453),
 (1455, 0.5267317526731753),
 (2416, 0.5267317526731753),
 (1432, 0.5262668526266853),
 (1268, 0.5248721524872152),
 (2561, 0.5234774523477452),
 (3350, 0.5234774523477452),
 (1300, 0.5230125523012552),
 (2778, 0.5230125523012552),
 (282, 0.5225476522547652),
 (3090, 0.5225476522547652),
 (1212, 0.5220827522082752),
 (1207, 0.5192933519293351),
 (2288, 0.5192933519293351),
 (3224, 0.5192933519293351),
 (3166, 0.5183635518363552),
 (1676, 0.5183635518363552),
 (2001, 0.5178986517898652),
 (2694, 0.5169688516968851),
 (1673, 0.5160390516039052),
 (3106, 0.5155741515574152),
 (371, 0.5155741515574152),
 (1748, 0.5151092515109251),
 (1415, 0.5141794514179451),
 (2685, 0.5141794514179451),
 (1492, 0.5118549511854951),
 (753, 0.511390051139005),
 (1122, 0.5109251510925151),
 (533, 0.5109251510925151),
 (322, 0.509530450953045),
 (142, 0.509065550906555),
 (785, 0.507205950720595),
 (1366, 0.507205950720595),
 (2379, 0.5058112505811251),
 (3129, 0.504881450488145),
 (3292, 0.504881450488145),
 (1942, 0.504881450488145),
 (3244, 0.503951650395165),
 (2295, 0.503951650395165),
 (3101, 0.503951650395165),
 (2768, 0.5034867503486751),
 (199, 0.503021850302185),
 (148, 0.502556950255695),
 (777, 0.502556950255695),
 (2607, 0.501627150162715),
 (247, 0.500697350069735),
 (2101, 0.499767549976755),
 (3235, 0.499767549976755),
 (1515, 0.499767549976755),
 (1636, 0.49604834960483496),
 (145, 0.4951185495118549),
 (1134, 0.49465364946536494),
 (3108, 0.49465364946536494),
 (2733, 0.49465364946536494),
 (359, 0.4941887494188749),
 (1094, 0.4932589493258949),
 (1528, 0.4927940492794049),
 (1071, 0.4927940492794049),
 (784, 0.4909344490934449),
 (19, 0.4909344490934449),
 (1450, 0.4904695490469549),
 (3080, 0.49000464900046486),
 (2470, 0.4895397489539749),
 (179, 0.4895397489539749),
 (2887, 0.48907484890748487),
 (382, 0.48907484890748487),
 (2666, 0.48907484890748487),
 (1281, 0.4881450488145049),
 (2532, 0.4881450488145049),
 (2916, 0.4881450488145049),
 (367, 0.4881450488145049),
 (673, 0.48675034867503486),
 (2665, 0.48628544862854484),
 (2850, 0.48582054858205487),
 (3252, 0.48582054858205487),
 (3305, 0.48582054858205487),
 (2747, 0.48582054858205487),
 (3186, 0.48535564853556484),
 (2070, 0.48442584844258485),
 (3183, 0.4839609483960948),
 (1518, 0.4834960483496048),
 (1665, 0.4834960483496048),
 (1205, 0.48303114830311483),
 (3151, 0.48303114830311483),
 (1226, 0.4825662482566248),
 (1275, 0.4816364481636448),
 (2118, 0.4816364481636448),
 (3254, 0.4816364481636448),
 (1962, 0.48070664807066477),
 (1542, 0.4802417480241748),
 (457, 0.4797768479776848),
 (1660, 0.4793119479311948),
 (2833, 0.4793119479311948),
 (1511, 0.47838214783821476),
 (2994, 0.47838214783821476),
 (2460, 0.4779172477917248),
 (1598, 0.4779172477917248),
 (1412, 0.47652254765225477),
 (1192, 0.47605764760576474),
 (3075, 0.47605764760576474),
 (2421, 0.4755927475592747),
 (1056, 0.4755927475592747),
 (1846, 0.4755927475592747),
 (259, 0.47512784751278475),
 (1126, 0.47512784751278475),
 (3015, 0.47512784751278475),
 (1279, 0.4746629474662947),
 (900, 0.4746629474662947),
 (2799, 0.4741980474198047),
 (2245, 0.47373314737331473),
 (934, 0.4732682473268247),
 (2063, 0.4718735471873547),
 (1371, 0.4718735471873547),
 (38, 0.4714086471408647),
 (1926, 0.4714086471408647),
 (766, 0.4704788470478847),
 (242, 0.4700139470013947),
 (2650, 0.4700139470013947),
 (2573, 0.4700139470013947),
 (783, 0.4700139470013947),
 (1802, 0.46908414690841466),
 (3237, 0.46815434681543466),
 (75, 0.46768944676894464),
 (2282, 0.46722454672245467),
 (2324, 0.46722454672245467),
 (1874, 0.46675964667596465),
 (2918, 0.4662947466294746),
 (1493, 0.46582984658298465),
 (1886, 0.46582984658298465),
 (695, 0.46582984658298465),
 (2603, 0.46443514644351463),
 (157, 0.46443514644351463),
 (1672, 0.46350534635053464),
 (1543, 0.4630404463040446),
 (482, 0.4625755462575546),
 (1887, 0.4625755462575546),
 (2969, 0.4625755462575546),
 (2117, 0.4611808461180846),
 (976, 0.4602510460251046),
 (2577, 0.4602510460251046),
 (2922, 0.45978614597861456),
 (2682, 0.45885634588563456),
 (1341, 0.4569967456996746),
 (1814, 0.4569967456996746),
 (2849, 0.45560204556020456),
 (1187, 0.45513714551371454),
 (2451, 0.45513714551371454),
 (3004, 0.45513714551371454),
 (928, 0.45513714551371454),
 (1625, 0.45420734542073454),
 (590, 0.45420734542073454),
 (2430, 0.4537424453742445),
 (1652, 0.4532775453277545),
 (1867, 0.4532775453277545),
 (1349, 0.4532775453277545),
 (889, 0.4528126452812645),
 (411, 0.4523477452347745),
 (583, 0.4523477452347745),
 (278, 0.4514179451417945),
 (2193, 0.4504881450488145),
 (1630, 0.4500232450023245),
 (2902, 0.4490934449093445),
 (2719, 0.4486285448628545),
 (1602, 0.4486285448628545),
 (1804, 0.4486285448628545),
 (1983, 0.44816364481636445),
 (3134, 0.4476987447698745),
 (350, 0.44676894467689443),
 (860, 0.44583914458391444),
 (1336, 0.44583914458391444),
 (1220, 0.44583914458391444),
 (2440, 0.4453742445374244),
 (1042, 0.4435146443514644),
 (3136, 0.4430497443049744),
 (1875, 0.4430497443049744),
 (2325, 0.4430497443049744),
 (1407, 0.4421199442119944),
 (1303, 0.4416550441655044),
 (2811, 0.4416550441655044),
 (1595, 0.4411901441190144),
 (679, 0.44026034402603437),
 (1362, 0.4397954439795444),
 (130, 0.4397954439795444),
 (246, 0.43886564388656435),
 (361, 0.4384007438400744),
 (996, 0.4384007438400744),
 (2702, 0.43793584379358436),
 (1589, 0.4374709437470944),
 (637, 0.4374709437470944),
 (1191, 0.43700604370060436),
 (2930, 0.43654114365411434),
 (1325, 0.43654114365411434),
 (233, 0.43607624360762437),
 (911, 0.43561134356113435),
 (1213, 0.4351464435146443),
 (1368, 0.4351464435146443),
 (1557, 0.4351464435146443),
 (1824, 0.43468154346815435),
 (772, 0.43468154346815435),
 (10, 0.43421664342166433),
 (1342, 0.4337517433751743),
 (2804, 0.43328684332868433),
 (422, 0.4323570432357043),
 (1131, 0.4323570432357043),
 (1151, 0.4323570432357043),
 (676, 0.4318921431892143),
 (1554, 0.4314272431427243),
 (1801, 0.4314272431427243),
 (1477, 0.43096234309623427),
 (894, 0.43096234309623427),
 (675, 0.4304974430497443),
 (3213, 0.4300325430032543),
 (2318, 0.4300325430032543),
 (2794, 0.4291027429102743),
 (1417, 0.42863784286378426),
 (362, 0.42724314272431424),
 (2970, 0.42677824267782427),
 (2939, 0.42677824267782427),
 (1955, 0.4258484425848442),
 (2763, 0.4258484425848442),
 (591, 0.42538354253835425),
 (344, 0.42491864249186423),
 (218, 0.42491864249186423),
 (1078, 0.42491864249186423),
 (1699, 0.42491864249186423),
 (2626, 0.4244537424453742),
 (567, 0.42398884239888424),
 (710, 0.4235239423523942),
 (477, 0.42305904230590424),
 (250, 0.4225941422594142),
 (2808, 0.4221292422129242),
 (3132, 0.4216643421664342),
 (86, 0.4216643421664342),
 (2932, 0.4216643421664342),
 (3314, 0.4211994421199442),
 (722, 0.4211994421199442),
 (134, 0.4211994421199442),
 (2856, 0.4202696420269642),
 (2653, 0.4198047419804742),
 (57, 0.4198047419804742),
 (1496, 0.41933984193398416),
 (3172, 0.4188749418874942),
 (39, 0.4188749418874942),
 (1180, 0.41841004184100417),
 (804, 0.41794514179451414),
 (2670, 0.4174802417480242),
 (1623, 0.4174802417480242),
 (1551, 0.4174802417480242),
 (1943, 0.41701534170153415),
 (1881, 0.41701534170153415),
 (1560, 0.41562064156206413),
 (3250, 0.41515574151557416),
 (1152, 0.41469084146908414),
 (2443, 0.41469084146908414),
 (564, 0.4142259414225941),
 (640, 0.4142259414225941),
 (1414, 0.4142259414225941),
 (2560, 0.41376104137610414),
 (426, 0.4132961413296141),
 (1302, 0.4119014411901441),
 (378, 0.4119014411901441),
 (339, 0.4114365411436541),
 (3077, 0.4109716410971641),
 (2172, 0.4109716410971641),
 (2766, 0.4105067410506741),
 (2102, 0.4105067410506741),
 (2870, 0.40911204091120407),
 (3329, 0.40911204091120407),
 (831, 0.40911204091120407),
 (2226, 0.40771734077173405),
 (2240, 0.40771734077173405),
 (2296, 0.4072524407252441),
 (704, 0.40678754067875406),
 (2912, 0.40678754067875406),
 (520, 0.40632264063226403),
 (2373, 0.40539284053928404),
 (2424, 0.40539284053928404),
 (2651, 0.40539284053928404),
 (1248, 0.404927940492794),
 (2209, 0.404927940492794),
 (1935, 0.404927940492794),
 (2231, 0.403998140399814),
 (166, 0.403998140399814),
 (1139, 0.403533240353324),
 (1859, 0.402603440260344),
 (1146, 0.402603440260344),
 (1579, 0.402603440260344),
 (1711, 0.40213854021385403),
 (1273, 0.40213854021385403),
 (1654, 0.40213854021385403),
 (100, 0.401208740120874),
 (1357, 0.400743840074384),
 (1756, 0.400278940027894),
 (1960, 0.400278940027894),
 (2116, 0.400278940027894),
 (1364, 0.400278940027894),
 (664, 0.39981403998140397),
 (1594, 0.39981403998140397),
 (929, 0.399349139934914),
 (207, 0.399349139934914),
 (1746, 0.399349139934914),
 (2620, 0.399349139934914),
 (45, 0.399349139934914),
 (2638, 0.399349139934914),
 (1744, 0.39841933984193395),
 (577, 0.397954439795444),
 (1338, 0.397954439795444),
 (973, 0.397954439795444),
 (2976, 0.39748953974895396),
 (476, 0.39748953974895396),
 (907, 0.39655973965597396),
 (3128, 0.39655973965597396),
 (143, 0.39655973965597396),
 (2581, 0.39655973965597396),
 (175, 0.39516503951650395),
 (2658, 0.39516503951650395),
 (2698, 0.39516503951650395),
 (144, 0.3947001394700139),
 (120, 0.39423523942352395),
 (163, 0.39377033937703393),
 (2618, 0.39377033937703393),
 (1631, 0.39377033937703393),
 (1902, 0.3933054393305439),
 (2194, 0.39284053928405394),
 (2693, 0.39284053928405394),
 (2657, 0.3919107391910739),
 (1607, 0.3919107391910739),
 (1662, 0.3919107391910739),
 (3191, 0.3919107391910739),
 (2107, 0.3914458391445839),
 (212, 0.3909809390980939),
 (1794, 0.3909809390980939),
 (78, 0.39051603905160387),
 (2630, 0.3900511390051139),
 (2582, 0.3900511390051139),
 (1176, 0.38912133891213385),
 (2941, 0.38912133891213385),
 (1457, 0.38912133891213385),
 (2234, 0.38912133891213385),
 (99, 0.3886564388656439),
 (1184, 0.3886564388656439),
 (2495, 0.38819153881915386),
 (198, 0.38679683867968384),
 (2301, 0.38679683867968384),
 (424, 0.38679683867968384),
 (3117, 0.38633193863319387),
 (2743, 0.38586703858670385),
 (1667, 0.3854021385402138),
 (1448, 0.38493723849372385),
 (2615, 0.38447233844723383),
 (1904, 0.38447233844723383),
 (204, 0.3840074384007438),
 (1373, 0.3840074384007438),
 (2710, 0.3840074384007438),
 (3263, 0.38354253835425384),
 (2925, 0.3830776383077638),
 (2352, 0.3826127382612738),
 (2598, 0.3826127382612738),
 (1339, 0.3826127382612738),
 (3107, 0.3821478382147838),
 (2445, 0.3821478382147838),
 (549, 0.3816829381682938),
 (1301, 0.3812180381218038),
 (1229, 0.3812180381218038),
 (2980, 0.3812180381218038),
 (1775, 0.3812180381218038),
 (261, 0.3807531380753138),
 (3078, 0.3807531380753138),
 (2971, 0.37889353788935376),
 (1256, 0.3784286378428638),
 (2810, 0.3784286378428638),
 (706, 0.37796373779637377),
 (2558, 0.37796373779637377),
 (547, 0.37749883774988374),
 (1633, 0.37749883774988374),
 (268, 0.37749883774988374),
 (1023, 0.3770339377033938),
 (2289, 0.3770339377033938),
 (1402, 0.37656903765690375),
 (1461, 0.3761041376104137),
 (92, 0.3761041376104137),
 (1431, 0.37563923756392376),
 (3269, 0.37563923756392376),
 (3278, 0.37563923756392376),
 (2189, 0.37563923756392376),
 (112, 0.37563923756392376),
 (2816, 0.37563923756392376),
 (337, 0.37517433751743373),
 (1638, 0.37517433751743373),
 (1688, 0.37517433751743373),
 (1018, 0.37517433751743373),
 (187, 0.3747094374709437),
 (1919, 0.3747094374709437),
 (284, 0.3747094374709437),
 (2426, 0.37424453742445374),
 (3180, 0.3737796373779637),
 (1923, 0.3737796373779637),
 (403, 0.3737796373779637),
 (1928, 0.3728498372849837),
 (2509, 0.3728498372849837),
 (1077, 0.3723849372384937),
 (2578, 0.3723849372384937),
 (872, 0.3719200371920037),
 (2300, 0.3719200371920037),
 (3020, 0.3714551371455137),
 (1088, 0.3714551371455137),
 (2672, 0.3714551371455137),
 (3088, 0.3709902370990237),
 (2559, 0.3705253370525337),
 (2396, 0.36959553695955366),
 (2174, 0.36959553695955366),
 (3251, 0.3691306369130637),
 (2632, 0.3691306369130637),
 (539, 0.36866573686657367),
 (847, 0.36820083682008364),
 (484, 0.36820083682008364),
 (1024, 0.3677359367735937),
 (598, 0.36727103672710365),
 (2909, 0.36727103672710365),
 (959, 0.3668061366806137),
 (2018, 0.3668061366806137),
 (2249, 0.3668061366806137),
 (292, 0.36634123663412366),
 (2563, 0.36634123663412366),
 (388, 0.36634123663412366),
 (1087, 0.36634123663412366),
 (1877, 0.36634123663412366),
 (2713, 0.36587633658763363),
 (2839, 0.36587633658763363),
 (1383, 0.36541143654114366),
 (2752, 0.36541143654114366),
 (1512, 0.36541143654114366),
 (1590, 0.36541143654114366),
 (1046, 0.36541143654114366),
 (1620, 0.36541143654114366),
 (412, 0.36541143654114366),
 (714, 0.36494653649465364),
 (70, 0.36494653649465364),
 (498, 0.36494653649465364),
 (1416, 0.36494653649465364),
 (2723, 0.3644816364481636),
 (1784, 0.3644816364481636),
 (2754, 0.3644816364481636),
 (4, 0.3635518363551836),
 (3312, 0.3635518363551836),
 (2192, 0.3635518363551836),
 (3300, 0.3630869363086936),
 (1254, 0.3630869363086936),
 (1069, 0.36262203626220363),
 (501, 0.3621571362157136),
 (1605, 0.3621571362157136),
 (1843, 0.3616922361692236),
 (1686, 0.3616922361692236),
 (184, 0.3612273361227336),
 (47, 0.3607624360762436),
 (902, 0.3607624360762436),
 (1026, 0.3607624360762436),
 (1145, 0.3607624360762436),
 (606, 0.3607624360762436),

In [44]:
row = text_jan['id'][3357]
text_jan['label'][row-1]

'zoonotic virus'

In [24]:
text_jan

,id,label,x,y,cluster,weight<Links>,weight<Total link strength>,weight<Occurrences>
0,1,21st century,0.0522,0.6146,3,694,1718,239
1,2,a resolution,1.4952,0.1170,2,260,761,53
2,3,abdomen,-0.5169,-0.6004,1,819,2484,231
3,4,abdominal pain,-0.3455,-0.3431,1,1029,3410,323
4,5,abdominal surgery,-0.8209,-0.6241,1,781,2741,221
...,...,...,...,...,...,...,...,...
3353,3354,zika virus,0.7893,0.2393,2,716,2122,177
3354,3355,zikv,0.8772,0.1872,2,597,1669,133
3355,3356,zoonose,0.3931,0.6305,3,400,1194,148
3356,3357,zoonotic disease,0.3931,0.5302,3,620,1788,173
3357,3358,zoonotic virus,0.8253,0.3608,2,398,986,88

In [25]:
def node_word(node_dict,text):
    new_dict = {}
    for key,value in node_dict.items():
        if key<=len(text):
            row = text['id'][key-1]
            if row < 5401:
                word = text['label'][row-1]
            else:
                #print(key)
                word = text['label'][row-3]
            new_dict[word]=value
        else:
            row = text['id'][key-2]
            word = text['label'][row-2]
            new_dict[word]=value
            #print(row,word)
    return new_dict

In [26]:
dcentralities2

{1: 0.20673220137027107,
 4: 0.3065236818588025,
 10: 0.41942210306821565,
 14: 0.1620494489127197,
 21: 0.5013404825737265,
 23: 0.7044980637473935,
 29: 0.6252606493893357,
 33: 0.18915698540363418,
 34: 0.09949359547214776,
 44: 0.6300268096514745,
 47: 0.27047959487637774,
 52: 0.47393506106642835,
 61: 0.3264819779565088,
 72: 0.1546023235031278,
 73: 0.11826035150431934,
 75: 0.4384867441167709,
 76: 0.1778373547810545,
 77: 0.11021745606196008,
 82: 0.0816204944891272,
 98: 0.035746201966041107,
 99: 0.3315460232350313,
 111: 0.26630920464700625,
 124: 0.7566279416145367,
 125: 0.504617217753947,
 126: 0.18379505510872804,
 127: 0.20285969615728328,
 129: 0.12332439678284182,
 131: 0.7080726839439976,
 133: 0.7372654155495978,
 145: 0.39201668156091746,
 148: 0.49210604706583255,
 152: 0.08698242478403335,
 160: 0.07208817396484957,
 164: 0.6133452487339887,
 170: 0.20613643133750373,
 184: 0.31665177241584747,
 198: 0.38516532618409294,
 200: 0.17992254989574025,
 204: 0.3726541554959785,
 214: 0.2817992254989574,
 215: 0.2103068215668752,
 221: 0.128686327077748,
 222: 0.19302949061662197,
 223: 0.11408996127494787,
 224: 0.6008340780458743,
 225: 0.21656240691093237,
 229: 0.2734584450402145,
 233: 0.3443550789395293,
 239: 0.3452487339886804,
 242: 0.38844206136431336,
 243: 0.22639261245159367,
 245: 0.1620494489127197,
 248: 0.2088173964849568,
 258: 0.2064343163538874,
 259: 0.40988978254393804,
 261: 0.28865058087578194,
 266: 0.4447423294608281,
 283: 0.28150134048257375,
 292: 0.3199285075960679,
 302: 0.17605004468275245,
 303: 0.2323503127792672,
 310: 0.1420911528150134,
 337: 0.35150431933273757,
 342: 0.20613643133750373,
 353: 0.21268990169794458,
 354: 0.1471551980935359,
 361: 0.333631218349717,
 366: 0.8370568960381293,
 369: 0.2844801906464105,
 372: 0.22609472743521,
 374: 0.23681858802502234,
 377: 0.1691986893059279,
 381: 0.17009234435507894,
 393: 0.11349419124218052,
 400: 0.45606196008340777,
 402: 0.2752457551385165,
 409: 0.24813821864760202,
 410: 0.18498659517426272,
 411: 0.35031277926720283,
 421: 0.16473041406017278,
 422: 0.3571641346440274,
 429: 0.3717605004468275,
 442: 0.25767053917187965,
 443: 0.19332737563300564,
 448: 0.5075960679177838,
 452: 0.7101578790586833,
 458: 0.17039022937146261,
 481: 0.16592195412570748,
 482: 0.42865653857610964,
 489: 0.24932975871313673,
 492: 0.43312481382186474,
 500: 0.2719690199582961,
 504: 0.25767053917187965,
 506: 0.3395889186773905,
 515: 0.21834971700923442,
 516: 0.5507893952934168,
 518: 0.19213583556747096,
 520: 0.3827822460530235,
 530: 0.6252606493893357,
 531: 0.8835269585939827,
 534: 0.524873398868037,
 536: 0.12838844206136432,
 543: 0.07536490914507,
 558: 0.1423890378313971,
 559: 0.16473041406017278,
 566: 0.3395889186773905,
 567: 0.4101876675603217,
 568: 0.20226392612451594,
 569: 0.2597557342865654,
 570: 0.16234733392910336,
 577: 0.3532916294310396,
 591: 0.3857610962168603,
 596: 0.9195710455764075,
 598: 0.36044086982424783,
 604: 0.6279416145367888,
 607: 0.2779267202859696,
 609: 0.23443550789395293,
 617: 0.13136729222520108,
 622: 0.5686624962764373,
 627: 0.2624366994340185,
 636: 0.19005064045278522,
 645: 0.15192135835567472,
 648: 0.0902591599642538,
 649: 0.11170688114387846,
 651: 0.1954125707476914,
 657: 0.171879654453381,
 659: 0.5299374441465594,
 662: 0.4524873398868037,
 670: 0.09085492999702115,
 671: 0.17813523979743817,
 673: 0.4804885314268692,
 692: 0.23056300268096513,
 693: 0.12540959189752754,
 704: 0.3461423890378314,
 709: 0.570747691391123,
 714: 0.2826928805481084,
 723: 0.26630920464700625,
 725: 0.5796842418826333,
 731: 0.16264521894548703,
 738: 0.1817098599940423,
 739: 0.7765862377122431,
 742: 0.1840929401251117,
 749: 0.5585344057193923,
 753: 0.41227286267500746,
 755: 0.13434614238903783,
 760: 0.1593684837652666,
 762: 0.27047959487637774,
 764: 0.2779267202859696,
 766: 0.40125111706881145,
 768: 0.3211200476616026,
 770: 0.2853738456955615,
 773: 0.49865951742627346,
 776: 0.5662794161453679,
 777: 0.42776288352695857,
 778: 0.2347333929103366,
 779: 0.4539767649687221,
 780: 0.11706881143878463,
 784: 0.474232946082812,
 786: 0.7044980637473935,
 792: 0.11021745606196008,
 795: 0.17098599940422995,
 796: 0.1593684837652666,
 798: 0.1456657730116175,
 800: 0.19809353589514447,
 801: 0.11379207625856419,
 802: 0.21090259159964253,
 804: 0.3240988978254394,
 812: 0.19005064045278522,
 818: 0.4524873398868037,
 825: 0.20732797140303844,
 826: 0.17545427464998511,
 834: 0.14179326779862972,
 836: 0.2618409294012511,
 837: 0.3949955317247542,
 838: 0.2100089365504915,
 840: 0.1605600238308013,
 841: 0.548704200178731,
 843: 0.1927316056002383,
 847: 0.2993744414655943,
 850: 0.2907357759904677,
 852: 0.22698838248436104,
 861: 0.3857610962168603,
 864: 0.5978552278820375,
 867: 0.3103961870717903,
 875: 0.6315162347333929,
 885: 0.13523979743818887,
 887: 0.13523979743818887,
 888: 0.22341376228775692,
 889: 0.34584450402144773,
 902: 0.36133452487339884,
 903: 0.2943103961870718,
 908: 0.1739648495680667,
 911: 0.3488233541852845,
 915: 0.6812630324694667,
 924: 0.08251414953827822,
 931: 0.1483467381590706,
 937: 0.13643133750372355,
 950: 0.15966636878165028,
 964: 0.33571641346440273,
 965: 0.7071790288948466,
 969: 0.3199285075960679,
 971: 0.7199880845993446,
 980: 0.5558534405719392,
 982: 0.09949359547214776,
 985: 0.18081620494489126,
 992: 0.20554066130473636,
 996: 0.37980339588918677,
 998: 0.3434614238903783,
 1005: 0.30294906166219837,
 1014: 0.20077450104259756,
 1028: 0.07625856419422103,
 1034: 0.10932380101280906,
 1041: 0.1420911528150134,
 1048: 0.14387846291331546,
 1049: 0.5719392314566577,
 1053: 0.12153708668453976,
 1054: 0.11587727137324992,
 1055: 0.6657730116175157,
 1057: 0.6157283288650581,
 1073: 0.21834971700923442,
 1093: 0.7036044086982425,
 1101: 0.19213583556747096,
 1102: 0.2806076854334227,
 1104: 0.45874292523086085,
 1106: 0.20554066130473636,
 1114: 0.22311587727137325,
 1117: 0.107536490914507,
 1122: 0.42716711349419123,
 1131: 0.40125111706881145,
 1133: 0.1778373547810545,
 1134: 0.48882931188561213,
 1135: 0.09711051534107834,
 1140: 0.18617813523979743,
 1158: 0.19988084599344652,
 1166: 0.21328567173071195,
 1176: 0.2907357759904677,
 1178: 0.18588025022341376,
 1181: 0.31843908251414954,
 1183: 0.44325290437890974,
 1186: 0.24426571343461423,
 1187: 0.4509979148048853,
 1188: 0.1334524873398868,
 1190: 0.31218349717009236,
 1191: 0.4113792076258564,
 1192: 0.43282692880548107,
 1193: 0.3053321417932678,
 1194: 0.3264819779565088,
 1196: 0.26541554959785524,
 1198: 0.16026213881441764,
 1199: 0.14864462317545427,
 1201: 0.14536788799523384,
 1205: 0.46797736073875484,
 1206: 0.2660113196306226,
 1207: 0.4974679773607387,
 1209: 0.3160560023830801,
 1212: 0.48019064641048553,
 1215: 0.15996425379803395,
 1231: 0.27137324992552875,
 1233: 0.5555555555555556,
 1237: 0.1864760202561811,
 1244: 0.14030384271671134,
 1246: 0.2386058981233244,
 1258: 0.6017277330950253,
 1280: 0.5930890676198987,
 1281: 0.39946380697050937,
 1296: 0.8001191540065534,
 1298: 0.12094131665177241,
 1299: 0.25409591897527556,
 1300: 0.40393208221626453,
 1301: 0.3026511766458147,
 1302: 0.35180220434912124,
 1303: 0.35865355972594576,
 1305: 0.1966041108132261,
 1306: 0.18439082514149538,
 1308: 0.22549895740244266,
 1309: 0.2642240095323205,
 1313: 0.23741435805778968,
 1314: 0.1986893059279118,
 1320: 0.16353887399463807,
 1334: 0.10634495084897229,
 1335: 0.6621983914209115,
 1340: 0.35090854929997023,
 1342: 0.38337801608579086,
 1359: 0.6145367887995233,
 1360: 0.5320226392612452,
 1361: 0.6318141197497765,
 1362: 0.35090854929997023,
 1363: 0.24158474828716114,
 1369: 0.14179326779862972,
 1379: 0.5433422698838248,
 1383: 0.3378016085790885,
 1388: 0.6353887399463807,
 1398: 0.528448019064641,
 1399: 0.21566875186178136,
 1404: 0.2162645218945487,
 1405: 0.18736967530533213,
 1407: 0.33661006851355374,
 1412: 0.3726541554959785,
 1413: 0.7140303842716711,
 1415: 0.41674113792076256,
 1424: 0.21656240691093237,
 1425: 0.17813523979743817,
 1426: 0.19481680071492405,
 1427: 0.5034256776884123,
 1431: 0.3735478105451296,
 1434: 0.16949657432231158,
 1436: 0.7006255585344057,
 1441: 0.43818885910038724,
 1443: 0.2746499851057492,
 1444: 0.17873100983020554,
 1445: 0.2555853440571939,
 1446: 0.3681858802502234,
 1451: 0.17605004468275245,
 1453: 0.2862675007447125,
 1461: 0.3285671730711945,
 1462: 0.8129282097110515,
 1465: 0.5144474232946082,
 1470: 0.07357759904676794,
 1477: 0.4265713434614239,
 1492: 0.430145963658028,
 1493: 0.37920762585641943,
 1494: 0.1730711945189157,
 1501: 0.21477509681263032,
 1528: 0.47750968126303245,
 1529: 0.1546023235031278,
 1540: 0.5802800119154007,
 1549: 0.11587727137324992,
 1560: 0.40482573726541554,
 1572: 0.3172475424486148,
 1576: 0.17217753946976466,
 1577: 0.14149538278224605,
 1578: 0.270181709859994,
 1580: 0.32797140303842715,
 1581: 0.22043491212392016,
 1584: 0.1358355674709562,
 1585: 0.33631218349717007,
 1587: 0.16592195412570748,
 1591: 0.193923145665773,
 1592: 0.7485850461721775,
 1593: 0.5439380399165922,
 1600: 0.2779267202859696,
 1625: 0.44801906464104857,
 1629: 0.13285671730711945,
 1637: 0.13613345248733988,
 1638: 0.29103366100685135,
 1652: 0.35895144474232943,
 1667: 0.2955019362526065,
 1671: 0.4283586535597259,
 1684: 0.1966041108132261,
 1687: 0.259159964253798,
 1688: 0.2990765564492106,
 1690: 0.2767351802204349,
 1706: 0.6499851057491808,
 1713: 0.128686327077748,
 1727: 0.6058981233243967,
 1728: 0.906166219839142,
 1730: 0.21924337205838546,
 1731: 0.13762287756925826,
 1754: 0.6505808757819481,
 1756: 0.3967828418230563,
 1758: 0.11051534107834375,
 1763: 0.19719988084599344,
 1764: 0.3771224307417337,
 1766: 0.17247542448614833,
 1769: 0.13404825737265416,
 1771: 0.5856419422103069,
 1772: 0.4709562109025916,
 1773: 0.2213285671730712,
 1780: 0.31665177241584747,
 1796: 0.16353887399463807,
 1798: 0.14179326779862972,
 1799: 0.15907059874888294,
 1819: 0.6574322311587727,
 1821: 0.17843312481382187,
 1824: 0.39976169198689304,
 1859: 0.33184390825141497,
 1863: 0.569854036341972,
 1864: 0.1111111111111111,
 1866: 0.473339291033661,
 1872: 0.7980339588918677,
 1878: 0.2719690199582961,
 1879: 0.580875781948168,
 1894: 0.2103068215668752,
 1902: 0.32529043789097406,
 1920: 0.139708072683944,
 1921: 0.5519809353589514,
 1943: 0.4069109323801013,
 1948: 0.11438784629133154,
 1954: 0.1554959785522788,
 1955: 0.3583556747095621,
 1956: 0.2025618111408996,
 1966: 0.18319928507596067,
 1972: 0.1307715221924337,
 1975: 0.18022043491212392,
 1976: 0.1766458147155198,
 1979: 0.15758117366696456,
 1991: 0.14536788799523384,
 1993: 0.1224307417336908,
 1994: 0.21954125707476912,
 1997: 0.26124515936848375,
 2007: 0.1989871909442955,
 2028: 0.2201370271075365,
 2043: 0.13494191242180517,
 2046: 0.4060172773309502,
 2052: 0.5352993744414656,
 2053: 0.24515936848376527,
 2056: 0.28120345546619,
 2059: 0.15251712838844206,
 2060: 0.13315460232350312,
 2063: 0.42210306821566873,
 2066: 0.22281799225498958,
 2076: 0.3112898421209413,
 2083: 0.6687518617813524,
 2087: 0.6344950848972296,
 2089: 0.268394399761692,
 2090: 0.34554661900506406,
 2091: 0.5296395591301757,
 2092: 0.8010128090557045,
 2093: 0.11706881143878463,
 2099: 0.11051534107834375,
 2105: 0.23830801310694072,
 2106: 0.13494191242180517,
 2137: 0.6878165028299077,
 2142: 0.26035150431933274,
 2144: 0.26362823949955316,
 2153: 0.12392016681560918,
 2155: 0.14626154304438485,
 2156: 0.2320524277628835,
 2158: 0.11289842120941317,
 2163: 0.09353589514447423,
 2166: 0.2966934763181412,
 2175: 0.5218945487042002,
 2177: 0.20851951146857312,
 2182: 0.08430145963658028,
 2184: 0.7327971403038427,
 2185: 0.5993446529639559,
 2186: 0.12809055704498062,
 2187: 0.10783437593089068,
 2191: 0.8060768543342269,
 2203: 0.20345546619005064,
 2217: 0.22907357759904676,
 2220: 0.6410485552576706,
 2226: 0.40214477211796246,
 2228: 0.5755138516532619,
 2231: 0.4101876675603217,
 2232: 0.2037533512064343,
 2233: 0.2752457551385165,
 2239: 0.24635090854929997,
 2245: 0.4459338695263628,
 2247: 0.14536788799523384,
 2251: 0.2210306821566875,
 2253: 0.21537086684539766,
 2257: 0.5424486148346738,
 2264: 0.26005361930294907,
 2267: 0.34495084897229666,
 2284: 0.14894250819183794,
 2285: 0.6148346738159071,
 2286: 0.14864462317545427,
 2287: 0.4203157581173667,
 2288: 0.45427464998510575,
 2301: 0.28150134048257375,
 2308: 0.5612153708668454,
 2309: 0.2728626750074471,
 2310: 0.24813821864760202,
 2312: 0.13672922252010725,
 2313: 0.2675007447125409,
 2316: 0.2514149538278225,
 2326: 0.19809353589514447,
 2328: 0.26779862972892465,
 2344: 0.19511468573130772,
 2350: 0.14745308310991956,
 2366: 0.09859994042299672,
 2370: 0.21298778671432828,
 2371: 0.18260351504319333,
 2373: 0.37682454572535,
 2378: 0.8826333035448317,
 2379: 0.4980637473935061,
 2385: 0.13196306225796842,
 2387: 0.2889484658921656,
 2392: 0.13017575215966637,
 2396: 0.32558832290735773,
 2399: 0.19839142091152814,
 2402: 0.2731605600238308,
 2411: 0.2287756925826631,
 2413: 0.16085790884718498,
 2415: 0.0938337801608579,
 2419: 0.9243372058385463,
 2421: 0.42686922847780756,
 2422: 0.6934763181411975,
 2423: 0.25260649389335715,
 2424: 0.40125111706881145,
 2438: 0.7092642240095323,
 2451: 0.37682454572535,
 2454: 0.14804885314268693,
 2457: 0.7846291331546023,
 2460: 0.3854632112004766,
 2470: 0.4870420017873101,
 2471: 0.2990765564492106,
 2480: 0.21924337205838546,
 2481: 0.17992254989574025,
 2483: 0.12511170688114387,
 2485: 0.16830503425677687,
 2491: 0.29371462615430444,
 2492: 0.5612153708668454,
 2493: 0.14745308310991956,
 2495: 0.3681858802502234,
 2501: 0.15787905868334823,
 2503: 0.1671134941912422,
 2505: 0.12332439678284182,
 2522: 0.20792374143580578,
 2527: 0.15370866845397677,
 2532: 0.4548704200178731,
 2533: 0.1495382782246053,
 2535: 0.2767351802204349,
 2536: 0.12809055704498062,
 2537: 0.6940720881739648,
 2541: 0.12392016681560918,
 2542: 0.18528448019064642,
 2560: 0.3726541554959785,
 2565: 0.13196306225796842,
 2571: 0.24069109323801013,
 2583: 0.18230563002680963,
 2584: 0.2037533512064343,
 2585: 0.3214179326779863,
 2591: 0.7170092344355079,
 2594: 0.2707774798927614,
 2603: 0.43967828418230565,
 2612: 0.14626154304438485,
 2617: 0.5838546321120047,
 2621: 0.5397676496872207,
 2624: 0.2826928805481084,
 2626: 0.3461423890378314,
 2628: 0.5105749180816205,
 2637: 0.5338099493595472,
 2645: 0.16085790884718498,
 2649: 0.2409889782543938,
 2651: 0.32797140303842715,
 2652: 0.5239797438188859,
 2653: 0.3535895144474233,
 2654: 0.3026511766458147,
 2655: 0.24605302353291628,
 2656: 0.5495978552278821,
 2657: 0.28358653559725944,
 2660: 0.17813523979743817,
 2663: 0.785820673220137,
 2664: 0.8796544533809949,
 2669: 0.24128686327077747,
 2670: 0.43044384867441166,
 2671: 0.13434614238903783,
 2673: 0.2615430443848674,
 2675: 0.22907357759904676,
 2689: 0.6175156389633601,
 2690: 0.1593684837652666,
 2694: 0.3854632112004766,
 2703: 0.270181709859994,
 2706: 0.10723860589812333,
 2717: 0.16621983914209115,
 2719: 0.36044086982424783,
 2723: 0.3008638665475126,
 2725: 0.25856419422103066,
 2731: 0.15966636878165028,
 2736: 0.6481977956508788,
 2752: 0.28835269585939827,
 2762: 0.15966636878165028,
 2763: 0.4113792076258564,
 2764: 0.14268692284778076,
 2765: 0.09502532022639261,
 2766: 0.3866547512660113,
 2768: 0.4804885314268692,
 2769: 0.09234435507893952,
 2771: 0.3109919571045576,
 2781: 0.5221924337205839,
 2782: 0.5600238308013107,
 2784: 0.4203157581173667,
 2785: 0.2871611557938636,
 2787: 0.5793863568662496,
 2794: 0.34167411379207624,
 2795: 0.6508787607983318,
 2797: 0.4676794757223712,
 2804: 0.30294906166219837,
 2812: 0.6830503425677689,
 2815: 0.16621983914209115,
 2828: 0.12838844206136432,
 2831: 0.29222520107238603,
 2850: 0.41435805778969315,
 2870: 0.44772117962466484,
 2879: 0.22341376228775692,
 2881: 0.1373249925528746,
 2885: 0.10962168602919273,
 2887: 0.47661602621388144,
 2890: 0.1641346440274054,
 2891: 0.25618111408996125,
 2893: 0.3264819779565088,
 2897: 0.685731307715222,
 2902: 0.342865653857611,
 2907: 0.2841823056300268,
 2908: 0.6297289246350909,
 2916: 0.3932082216264522,
 2917: 0.22073279714030383,
 2918: 0.37503723562704794,
 2921: 0.19958296097706285,
 2926: 0.5415549597855228,
 2941: 0.31426869228477805,
 2953: 0.6943699731903485,
 2954: 0.1790288948465892,
 2956: 0.22549895740244266,
 2959: 0.12779267202859695,
 2964: 0.2457551385165326,
 2965: 0.8030980041703902,
 2967: 0.5397676496872207,
 2970: 0.36907953529937443,
 2974: 0.17456061960083408,
 2979: 0.29192731605600236,
 2985: 0.17485850461721775,
 2995: 0.6565385761096216,
 2996: 0.5320226392612452,
 2997: 0.7902889484658921,
 3010: 0.7545427464998511,
 3016: 0.18856121537086684,
 3017: 0.11468573130771521,
 3020: 0.29877867143282694,
 3022: 0.20196604110813227,
 3023: 0.5978552278820375,
 3026: 0.7044980637473935,
 3027: 0.18945487042001788,
 3034: 0.28507596067917784,
 3037: 0.505510872803098,
 3040: 0.2695859398272267,
 3047: 0.755436401549002,
 3053: 0.19958296097706285,
 3054: 0.21328567173071195,
 3058: 0.2335418528448019,
 3064: 0.12004766160262138,
 3073: 0.3473339291033661,
 3075: 0.47482871611557936,
 3076: 0.4667858206732201,
 3077: 0.33124813821864757,
 3080: 0.4215072981829014,
 3081: 0.322609472743521,
 3097: 0.7908847184986595,
 3108: 0.42716711349419123,
 3109: 0.63777182007745,
 3116: 0.13196306225796842,
 3121: 0.2618409294012511,
 3122: 0.24158474828716114,
 3124: 0.6338993148644623,
 3129: 0.39439976169198687,
 3132: 0.30563002680965146,
 3136: 0.3857610962168603,
 3140: 0.14000595770032767,
 3148: 0.13255883229073578,
 3163: 0.06285373845695562,
 3164: 0.31158772713732497,
 3166: 0.4474232946082812,
 3167: 0.6526660708966339,
 3172: 0.36907953529937443,
 3180: 0.3211200476616026,
 3185: 0.2615430443848674,
 3186: 0.4807864164432529,
 3188: 0.13404825737265416,
 3203: 0.15132558832290735,
 3210: 0.7399463806970509,
 3211: 0.26899016979445933,
 3212: 0.17217753946976466,
 3213: 0.342865653857611,
 3228: 0.536788799523384,
 3240: 0.5397676496872207,
 3241: 0.18975275543640155,
 3244: 0.40393208221626453,
 3245: 0.20792374143580578,
 3247: 0.7047959487637772,
 3252: 0.38754840631516235,
 3259: 0.26392612451593683,
 3261: 0.10783437593089068,
 3264: 0.9261245159368483,
 3266: 0.5969615728328865,
 3269: 0.2955019362526065,
 3270: 0.26899016979445933,
 3276: 0.6011319630622579,
 3278: 0.3077152219243372,
 3281: 0.1522192433720584,
 3294: 0.2112004766160262,
 3295: 0.17456061960083408,
 3298: 0.5099791480488531,
 3300: 0.35924932975871315,
 3304: 0.6124515936848376,
 3305: 0.42180518319928506,
 3318: 0.20822162645218945,
 3319: 0.23056300268096513,
 3322: 0.5370866845397676,
 3323: 0.25350014894250816,
 3325: 0.27822460530235327,
 3326: 0.2237116473041406,
 3357: 0.18468871015787905,
 3358: 0.118558236520703,
 2: 0.07745010425975574,
 26: 0.18826333035448317,
 32: 0.1730711945189157,
 70: 0.3065236818588025,
 91: 0.4769139112302651,
 147: 0.22073279714030383,
 163: 0.3512064343163539,
 186: 0.6797736073875484,
 187: 0.3160560023830801,
 195: 0.29848078641644327,
 202: 0.15370866845397677,
 213: 0.11796246648793565,
 217: 0.34048257372654156,
 246: 0.36044086982424783,
 247: 0.4152517128388442,
 250: 0.3479296991361334,
 251: 0.26899016979445933,
 257: 0.1766458147155198,
 319: 0.16026213881441764,
 320: 0.15668751861781352,
 339: 0.33571641346440273,
 376: 0.2496276437295204,
 394: 0.47065832588620793,
 439: 0.21596663687816503,
 464: 0.2624366994340185,
 483: 0.17634792969913612,
 486: 0.19928507596067918,
 523: 0.3675901102174561,
 533: 0.4462317545427465,
 554: 0.22311587727137325,
 555: 0.13285671730711945,
 595: 0.19451891569854035,
 619: 0.09562109025915996,
 635: 0.09859994042299672,
 706: 0.2963955913017575,
 758: 0.44504021447721176,
 781: 0.15519809353589514,
 785: 0.41495382782246054,
 799: 0.23145665773011617,
 803: 0.24158474828716114,
 806: 0.1423890378313971,
 827: 0.14268692284778076,
 860: 0.3559725945784927,

In [27]:
# 2021 most centralized data：
output_jan = node_word(dcentralities2,text_jan)
output_jan_sorted = sorted(output_jan.items(), reverse = True, key = lambda x:x[1])

In [87]:
#是否有bridge distance one？ centrality 提升很大的？

In [29]:
dcentralities2

{1: 0.20673220137027107,
 4: 0.3065236818588025,
 10: 0.41942210306821565,
 14: 0.1620494489127197,
 21: 0.5013404825737265,
 23: 0.7044980637473935,
 29: 0.6252606493893357,
 33: 0.18915698540363418,
 34: 0.09949359547214776,
 44: 0.6300268096514745,
 47: 0.27047959487637774,
 52: 0.47393506106642835,
 61: 0.3264819779565088,
 72: 0.1546023235031278,
 73: 0.11826035150431934,
 75: 0.4384867441167709,
 76: 0.1778373547810545,
 77: 0.11021745606196008,
 82: 0.0816204944891272,
 98: 0.035746201966041107,
 99: 0.3315460232350313,
 111: 0.26630920464700625,
 124: 0.7566279416145367,
 125: 0.504617217753947,
 126: 0.18379505510872804,
 127: 0.20285969615728328,
 129: 0.12332439678284182,
 131: 0.7080726839439976,
 133: 0.7372654155495978,
 145: 0.39201668156091746,
 148: 0.49210604706583255,
 152: 0.08698242478403335,
 160: 0.07208817396484957,
 164: 0.6133452487339887,
 170: 0.20613643133750373,
 184: 0.31665177241584747,
 198: 0.38516532618409294,
 200: 0.17992254989574025,
 204: 0.3726541554959785,
 214: 0.2817992254989574,
 215: 0.2103068215668752,
 221: 0.128686327077748,
 222: 0.19302949061662197,
 223: 0.11408996127494787,
 224: 0.6008340780458743,
 225: 0.21656240691093237,
 229: 0.2734584450402145,
 233: 0.3443550789395293,
 239: 0.3452487339886804,
 242: 0.38844206136431336,
 243: 0.22639261245159367,
 245: 0.1620494489127197,
 248: 0.2088173964849568,
 258: 0.2064343163538874,
 259: 0.40988978254393804,
 261: 0.28865058087578194,
 266: 0.4447423294608281,
 283: 0.28150134048257375,
 292: 0.3199285075960679,
 302: 0.17605004468275245,
 303: 0.2323503127792672,
 310: 0.1420911528150134,
 337: 0.35150431933273757,
 342: 0.20613643133750373,
 353: 0.21268990169794458,
 354: 0.1471551980935359,
 361: 0.333631218349717,
 366: 0.8370568960381293,
 369: 0.2844801906464105,
 372: 0.22609472743521,
 374: 0.23681858802502234,
 377: 0.1691986893059279,
 381: 0.17009234435507894,
 393: 0.11349419124218052,
 400: 0.45606196008340777,
 402: 0.2752457551385165,
 409: 0.24813821864760202,
 410: 0.18498659517426272,
 411: 0.35031277926720283,
 421: 0.16473041406017278,
 422: 0.3571641346440274,
 429: 0.3717605004468275,
 442: 0.25767053917187965,
 443: 0.19332737563300564,
 448: 0.5075960679177838,
 452: 0.7101578790586833,
 458: 0.17039022937146261,
 481: 0.16592195412570748,
 482: 0.42865653857610964,
 489: 0.24932975871313673,
 492: 0.43312481382186474,
 500: 0.2719690199582961,
 504: 0.25767053917187965,
 506: 0.3395889186773905,
 515: 0.21834971700923442,
 516: 0.5507893952934168,
 518: 0.19213583556747096,
 520: 0.3827822460530235,
 530: 0.6252606493893357,
 531: 0.8835269585939827,
 534: 0.524873398868037,
 536: 0.12838844206136432,
 543: 0.07536490914507,
 558: 0.1423890378313971,
 559: 0.16473041406017278,
 566: 0.3395889186773905,
 567: 0.4101876675603217,
 568: 0.20226392612451594,
 569: 0.2597557342865654,
 570: 0.16234733392910336,
 577: 0.3532916294310396,
 591: 0.3857610962168603,
 596: 0.9195710455764075,
 598: 0.36044086982424783,
 604: 0.6279416145367888,
 607: 0.2779267202859696,
 609: 0.23443550789395293,
 617: 0.13136729222520108,
 622: 0.5686624962764373,
 627: 0.2624366994340185,
 636: 0.19005064045278522,
 645: 0.15192135835567472,
 648: 0.0902591599642538,
 649: 0.11170688114387846,
 651: 0.1954125707476914,
 657: 0.171879654453381,
 659: 0.5299374441465594,
 662: 0.4524873398868037,
 670: 0.09085492999702115,
 671: 0.17813523979743817,
 673: 0.4804885314268692,
 692: 0.23056300268096513,
 693: 0.12540959189752754,
 704: 0.3461423890378314,
 709: 0.570747691391123,
 714: 0.2826928805481084,
 723: 0.26630920464700625,
 725: 0.5796842418826333,
 731: 0.16264521894548703,
 738: 0.1817098599940423,
 739: 0.7765862377122431,
 742: 0.1840929401251117,
 749: 0.5585344057193923,
 753: 0.41227286267500746,
 755: 0.13434614238903783,
 760: 0.1593684837652666,
 762: 0.27047959487637774,
 764: 0.2779267202859696,
 766: 0.40125111706881145,
 768: 0.3211200476616026,
 770: 0.2853738456955615,
 773: 0.49865951742627346,
 776: 0.5662794161453679,
 777: 0.42776288352695857,
 778: 0.2347333929103366,
 779: 0.4539767649687221,
 780: 0.11706881143878463,
 784: 0.474232946082812,
 786: 0.7044980637473935,
 792: 0.11021745606196008,
 795: 0.17098599940422995,
 796: 0.1593684837652666,
 798: 0.1456657730116175,
 800: 0.19809353589514447,
 801: 0.11379207625856419,
 802: 0.21090259159964253,
 804: 0.3240988978254394,
 812: 0.19005064045278522,
 818: 0.4524873398868037,
 825: 0.20732797140303844,
 826: 0.17545427464998511,
 834: 0.14179326779862972,
 836: 0.2618409294012511,
 837: 0.3949955317247542,
 838: 0.2100089365504915,
 840: 0.1605600238308013,
 841: 0.548704200178731,
 843: 0.1927316056002383,
 847: 0.2993744414655943,
 850: 0.2907357759904677,
 852: 0.22698838248436104,
 861: 0.3857610962168603,
 864: 0.5978552278820375,
 867: 0.3103961870717903,
 875: 0.6315162347333929,
 885: 0.13523979743818887,
 887: 0.13523979743818887,
 888: 0.22341376228775692,
 889: 0.34584450402144773,
 902: 0.36133452487339884,
 903: 0.2943103961870718,
 908: 0.1739648495680667,
 911: 0.3488233541852845,
 915: 0.6812630324694667,
 924: 0.08251414953827822,
 931: 0.1483467381590706,
 937: 0.13643133750372355,
 950: 0.15966636878165028,
 964: 0.33571641346440273,
 965: 0.7071790288948466,
 969: 0.3199285075960679,
 971: 0.7199880845993446,
 980: 0.5558534405719392,
 982: 0.09949359547214776,
 985: 0.18081620494489126,
 992: 0.20554066130473636,
 996: 0.37980339588918677,
 998: 0.3434614238903783,
 1005: 0.30294906166219837,
 1014: 0.20077450104259756,
 1028: 0.07625856419422103,
 1034: 0.10932380101280906,
 1041: 0.1420911528150134,
 1048: 0.14387846291331546,
 1049: 0.5719392314566577,
 1053: 0.12153708668453976,
 1054: 0.11587727137324992,
 1055: 0.6657730116175157,
 1057: 0.6157283288650581,
 1073: 0.21834971700923442,
 1093: 0.7036044086982425,
 1101: 0.19213583556747096,
 1102: 0.2806076854334227,
 1104: 0.45874292523086085,
 1106: 0.20554066130473636,
 1114: 0.22311587727137325,
 1117: 0.107536490914507,
 1122: 0.42716711349419123,
 1131: 0.40125111706881145,
 1133: 0.1778373547810545,
 1134: 0.48882931188561213,
 1135: 0.09711051534107834,
 1140: 0.18617813523979743,
 1158: 0.19988084599344652,
 1166: 0.21328567173071195,
 1176: 0.2907357759904677,
 1178: 0.18588025022341376,
 1181: 0.31843908251414954,
 1183: 0.44325290437890974,
 1186: 0.24426571343461423,
 1187: 0.4509979148048853,
 1188: 0.1334524873398868,
 1190: 0.31218349717009236,
 1191: 0.4113792076258564,
 1192: 0.43282692880548107,
 1193: 0.3053321417932678,
 1194: 0.3264819779565088,
 1196: 0.26541554959785524,
 1198: 0.16026213881441764,
 1199: 0.14864462317545427,
 1201: 0.14536788799523384,
 1205: 0.46797736073875484,
 1206: 0.2660113196306226,
 1207: 0.4974679773607387,
 1209: 0.3160560023830801,
 1212: 0.48019064641048553,
 1215: 0.15996425379803395,
 1231: 0.27137324992552875,
 1233: 0.5555555555555556,
 1237: 0.1864760202561811,
 1244: 0.14030384271671134,
 1246: 0.2386058981233244,
 1258: 0.6017277330950253,
 1280: 0.5930890676198987,
 1281: 0.39946380697050937,
 1296: 0.8001191540065534,
 1298: 0.12094131665177241,
 1299: 0.25409591897527556,
 1300: 0.40393208221626453,
 1301: 0.3026511766458147,
 1302: 0.35180220434912124,
 1303: 0.35865355972594576,
 1305: 0.1966041108132261,
 1306: 0.18439082514149538,
 1308: 0.22549895740244266,
 1309: 0.2642240095323205,
 1313: 0.23741435805778968,
 1314: 0.1986893059279118,
 1320: 0.16353887399463807,
 1334: 0.10634495084897229,
 1335: 0.6621983914209115,
 1340: 0.35090854929997023,
 1342: 0.38337801608579086,
 1359: 0.6145367887995233,
 1360: 0.5320226392612452,
 1361: 0.6318141197497765,
 1362: 0.35090854929997023,
 1363: 0.24158474828716114,
 1369: 0.14179326779862972,
 1379: 0.5433422698838248,
 1383: 0.3378016085790885,
 1388: 0.6353887399463807,
 1398: 0.528448019064641,
 1399: 0.21566875186178136,
 1404: 0.2162645218945487,
 1405: 0.18736967530533213,
 1407: 0.33661006851355374,
 1412: 0.3726541554959785,
 1413: 0.7140303842716711,
 1415: 0.41674113792076256,
 1424: 0.21656240691093237,
 1425: 0.17813523979743817,
 1426: 0.19481680071492405,
 1427: 0.5034256776884123,
 1431: 0.3735478105451296,
 1434: 0.16949657432231158,
 1436: 0.7006255585344057,
 1441: 0.43818885910038724,
 1443: 0.2746499851057492,
 1444: 0.17873100983020554,
 1445: 0.2555853440571939,
 1446: 0.3681858802502234,
 1451: 0.17605004468275245,
 1453: 0.2862675007447125,
 1461: 0.3285671730711945,
 1462: 0.8129282097110515,
 1465: 0.5144474232946082,
 1470: 0.07357759904676794,
 1477: 0.4265713434614239,
 1492: 0.430145963658028,
 1493: 0.37920762585641943,
 1494: 0.1730711945189157,
 1501: 0.21477509681263032,
 1528: 0.47750968126303245,
 1529: 0.1546023235031278,
 1540: 0.5802800119154007,
 1549: 0.11587727137324992,
 1560: 0.40482573726541554,
 1572: 0.3172475424486148,
 1576: 0.17217753946976466,
 1577: 0.14149538278224605,
 1578: 0.270181709859994,
 1580: 0.32797140303842715,
 1581: 0.22043491212392016,
 1584: 0.1358355674709562,
 1585: 0.33631218349717007,
 1587: 0.16592195412570748,
 1591: 0.193923145665773,
 1592: 0.7485850461721775,
 1593: 0.5439380399165922,
 1600: 0.2779267202859696,
 1625: 0.44801906464104857,
 1629: 0.13285671730711945,
 1637: 0.13613345248733988,
 1638: 0.29103366100685135,
 1652: 0.35895144474232943,
 1667: 0.2955019362526065,
 1671: 0.4283586535597259,
 1684: 0.1966041108132261,
 1687: 0.259159964253798,
 1688: 0.2990765564492106,
 1690: 0.2767351802204349,
 1706: 0.6499851057491808,
 1713: 0.128686327077748,
 1727: 0.6058981233243967,
 1728: 0.906166219839142,
 1730: 0.21924337205838546,
 1731: 0.13762287756925826,
 1754: 0.6505808757819481,
 1756: 0.3967828418230563,
 1758: 0.11051534107834375,
 1763: 0.19719988084599344,
 1764: 0.3771224307417337,
 1766: 0.17247542448614833,
 1769: 0.13404825737265416,
 1771: 0.5856419422103069,
 1772: 0.4709562109025916,
 1773: 0.2213285671730712,
 1780: 0.31665177241584747,
 1796: 0.16353887399463807,
 1798: 0.14179326779862972,
 1799: 0.15907059874888294,
 1819: 0.6574322311587727,
 1821: 0.17843312481382187,
 1824: 0.39976169198689304,
 1859: 0.33184390825141497,
 1863: 0.569854036341972,
 1864: 0.1111111111111111,
 1866: 0.473339291033661,
 1872: 0.7980339588918677,
 1878: 0.2719690199582961,
 1879: 0.580875781948168,
 1894: 0.2103068215668752,
 1902: 0.32529043789097406,
 1920: 0.139708072683944,
 1921: 0.5519809353589514,
 1943: 0.4069109323801013,
 1948: 0.11438784629133154,
 1954: 0.1554959785522788,
 1955: 0.3583556747095621,
 1956: 0.2025618111408996,
 1966: 0.18319928507596067,
 1972: 0.1307715221924337,
 1975: 0.18022043491212392,
 1976: 0.1766458147155198,
 1979: 0.15758117366696456,
 1991: 0.14536788799523384,
 1993: 0.1224307417336908,
 1994: 0.21954125707476912,
 1997: 0.26124515936848375,
 2007: 0.1989871909442955,
 2028: 0.2201370271075365,
 2043: 0.13494191242180517,
 2046: 0.4060172773309502,
 2052: 0.5352993744414656,
 2053: 0.24515936848376527,
 2056: 0.28120345546619,
 2059: 0.15251712838844206,
 2060: 0.13315460232350312,
 2063: 0.42210306821566873,
 2066: 0.22281799225498958,
 2076: 0.3112898421209413,
 2083: 0.6687518617813524,
 2087: 0.6344950848972296,
 2089: 0.268394399761692,
 2090: 0.34554661900506406,
 2091: 0.5296395591301757,
 2092: 0.8010128090557045,
 2093: 0.11706881143878463,
 2099: 0.11051534107834375,
 2105: 0.23830801310694072,
 2106: 0.13494191242180517,
 2137: 0.6878165028299077,
 2142: 0.26035150431933274,
 2144: 0.26362823949955316,
 2153: 0.12392016681560918,
 2155: 0.14626154304438485,
 2156: 0.2320524277628835,
 2158: 0.11289842120941317,
 2163: 0.09353589514447423,
 2166: 0.2966934763181412,
 2175: 0.5218945487042002,
 2177: 0.20851951146857312,
 2182: 0.08430145963658028,
 2184: 0.7327971403038427,
 2185: 0.5993446529639559,
 2186: 0.12809055704498062,
 2187: 0.10783437593089068,
 2191: 0.8060768543342269,
 2203: 0.20345546619005064,
 2217: 0.22907357759904676,
 2220: 0.6410485552576706,
 2226: 0.40214477211796246,
 2228: 0.5755138516532619,
 2231: 0.4101876675603217,
 2232: 0.2037533512064343,
 2233: 0.2752457551385165,
 2239: 0.24635090854929997,
 2245: 0.4459338695263628,
 2247: 0.14536788799523384,
 2251: 0.2210306821566875,
 2253: 0.21537086684539766,
 2257: 0.5424486148346738,
 2264: 0.26005361930294907,
 2267: 0.34495084897229666,
 2284: 0.14894250819183794,
 2285: 0.6148346738159071,
 2286: 0.14864462317545427,
 2287: 0.4203157581173667,
 2288: 0.45427464998510575,
 2301: 0.28150134048257375,
 2308: 0.5612153708668454,
 2309: 0.2728626750074471,
 2310: 0.24813821864760202,
 2312: 0.13672922252010725,
 2313: 0.2675007447125409,
 2316: 0.2514149538278225,
 2326: 0.19809353589514447,
 2328: 0.26779862972892465,
 2344: 0.19511468573130772,
 2350: 0.14745308310991956,
 2366: 0.09859994042299672,
 2370: 0.21298778671432828,
 2371: 0.18260351504319333,
 2373: 0.37682454572535,
 2378: 0.8826333035448317,
 2379: 0.4980637473935061,
 2385: 0.13196306225796842,
 2387: 0.2889484658921656,
 2392: 0.13017575215966637,
 2396: 0.32558832290735773,
 2399: 0.19839142091152814,
 2402: 0.2731605600238308,
 2411: 0.2287756925826631,
 2413: 0.16085790884718498,
 2415: 0.0938337801608579,
 2419: 0.9243372058385463,
 2421: 0.42686922847780756,
 2422: 0.6934763181411975,
 2423: 0.25260649389335715,
 2424: 0.40125111706881145,
 2438: 0.7092642240095323,
 2451: 0.37682454572535,
 2454: 0.14804885314268693,
 2457: 0.7846291331546023,
 2460: 0.3854632112004766,
 2470: 0.4870420017873101,
 2471: 0.2990765564492106,
 2480: 0.21924337205838546,
 2481: 0.17992254989574025,
 2483: 0.12511170688114387,
 2485: 0.16830503425677687,
 2491: 0.29371462615430444,
 2492: 0.5612153708668454,
 2493: 0.14745308310991956,
 2495: 0.3681858802502234,
 2501: 0.15787905868334823,
 2503: 0.1671134941912422,
 2505: 0.12332439678284182,
 2522: 0.20792374143580578,
 2527: 0.15370866845397677,
 2532: 0.4548704200178731,
 2533: 0.1495382782246053,
 2535: 0.2767351802204349,
 2536: 0.12809055704498062,
 2537: 0.6940720881739648,
 2541: 0.12392016681560918,
 2542: 0.18528448019064642,
 2560: 0.3726541554959785,
 2565: 0.13196306225796842,
 2571: 0.24069109323801013,
 2583: 0.18230563002680963,
 2584: 0.2037533512064343,
 2585: 0.3214179326779863,
 2591: 0.7170092344355079,
 2594: 0.2707774798927614,
 2603: 0.43967828418230565,
 2612: 0.14626154304438485,
 2617: 0.5838546321120047,
 2621: 0.5397676496872207,
 2624: 0.2826928805481084,
 2626: 0.3461423890378314,
 2628: 0.5105749180816205,
 2637: 0.5338099493595472,
 2645: 0.16085790884718498,
 2649: 0.2409889782543938,
 2651: 0.32797140303842715,
 2652: 0.5239797438188859,
 2653: 0.3535895144474233,
 2654: 0.3026511766458147,
 2655: 0.24605302353291628,
 2656: 0.5495978552278821,
 2657: 0.28358653559725944,
 2660: 0.17813523979743817,
 2663: 0.785820673220137,
 2664: 0.8796544533809949,
 2669: 0.24128686327077747,
 2670: 0.43044384867441166,
 2671: 0.13434614238903783,
 2673: 0.2615430443848674,
 2675: 0.22907357759904676,
 2689: 0.6175156389633601,
 2690: 0.1593684837652666,
 2694: 0.3854632112004766,
 2703: 0.270181709859994,
 2706: 0.10723860589812333,
 2717: 0.16621983914209115,
 2719: 0.36044086982424783,
 2723: 0.3008638665475126,
 2725: 0.25856419422103066,
 2731: 0.15966636878165028,
 2736: 0.6481977956508788,
 2752: 0.28835269585939827,
 2762: 0.15966636878165028,
 2763: 0.4113792076258564,
 2764: 0.14268692284778076,
 2765: 0.09502532022639261,
 2766: 0.3866547512660113,
 2768: 0.4804885314268692,
 2769: 0.09234435507893952,
 2771: 0.3109919571045576,
 2781: 0.5221924337205839,
 2782: 0.5600238308013107,
 2784: 0.4203157581173667,
 2785: 0.2871611557938636,
 2787: 0.5793863568662496,
 2794: 0.34167411379207624,
 2795: 0.6508787607983318,
 2797: 0.4676794757223712,
 2804: 0.30294906166219837,
 2812: 0.6830503425677689,
 2815: 0.16621983914209115,
 2828: 0.12838844206136432,
 2831: 0.29222520107238603,
 2850: 0.41435805778969315,
 2870: 0.44772117962466484,
 2879: 0.22341376228775692,
 2881: 0.1373249925528746,
 2885: 0.10962168602919273,
 2887: 0.47661602621388144,
 2890: 0.1641346440274054,
 2891: 0.25618111408996125,
 2893: 0.3264819779565088,
 2897: 0.685731307715222,
 2902: 0.342865653857611,
 2907: 0.2841823056300268,
 2908: 0.6297289246350909,
 2916: 0.3932082216264522,
 2917: 0.22073279714030383,
 2918: 0.37503723562704794,
 2921: 0.19958296097706285,
 2926: 0.5415549597855228,
 2941: 0.31426869228477805,
 2953: 0.6943699731903485,
 2954: 0.1790288948465892,
 2956: 0.22549895740244266,
 2959: 0.12779267202859695,
 2964: 0.2457551385165326,
 2965: 0.8030980041703902,
 2967: 0.5397676496872207,
 2970: 0.36907953529937443,
 2974: 0.17456061960083408,
 2979: 0.29192731605600236,
 2985: 0.17485850461721775,
 2995: 0.6565385761096216,
 2996: 0.5320226392612452,
 2997: 0.7902889484658921,
 3010: 0.7545427464998511,
 3016: 0.18856121537086684,
 3017: 0.11468573130771521,
 3020: 0.29877867143282694,
 3022: 0.20196604110813227,
 3023: 0.5978552278820375,
 3026: 0.7044980637473935,
 3027: 0.18945487042001788,
 3034: 0.28507596067917784,
 3037: 0.505510872803098,
 3040: 0.2695859398272267,
 3047: 0.755436401549002,
 3053: 0.19958296097706285,
 3054: 0.21328567173071195,
 3058: 0.2335418528448019,
 3064: 0.12004766160262138,
 3073: 0.3473339291033661,
 3075: 0.47482871611557936,
 3076: 0.4667858206732201,
 3077: 0.33124813821864757,
 3080: 0.4215072981829014,
 3081: 0.322609472743521,
 3097: 0.7908847184986595,
 3108: 0.42716711349419123,
 3109: 0.63777182007745,
 3116: 0.13196306225796842,
 3121: 0.2618409294012511,
 3122: 0.24158474828716114,
 3124: 0.6338993148644623,
 3129: 0.39439976169198687,
 3132: 0.30563002680965146,
 3136: 0.3857610962168603,
 3140: 0.14000595770032767,
 3148: 0.13255883229073578,
 3163: 0.06285373845695562,
 3164: 0.31158772713732497,
 3166: 0.4474232946082812,
 3167: 0.6526660708966339,
 3172: 0.36907953529937443,
 3180: 0.3211200476616026,
 3185: 0.2615430443848674,
 3186: 0.4807864164432529,
 3188: 0.13404825737265416,
 3203: 0.15132558832290735,
 3210: 0.7399463806970509,
 3211: 0.26899016979445933,
 3212: 0.17217753946976466,
 3213: 0.342865653857611,
 3228: 0.536788799523384,
 3240: 0.5397676496872207,
 3241: 0.18975275543640155,
 3244: 0.40393208221626453,
 3245: 0.20792374143580578,
 3247: 0.7047959487637772,
 3252: 0.38754840631516235,
 3259: 0.26392612451593683,
 3261: 0.10783437593089068,
 3264: 0.9261245159368483,
 3266: 0.5969615728328865,
 3269: 0.2955019362526065,
 3270: 0.26899016979445933,
 3276: 0.6011319630622579,
 3278: 0.3077152219243372,
 3281: 0.1522192433720584,
 3294: 0.2112004766160262,
 3295: 0.17456061960083408,
 3298: 0.5099791480488531,
 3300: 0.35924932975871315,
 3304: 0.6124515936848376,
 3305: 0.42180518319928506,
 3318: 0.20822162645218945,
 3319: 0.23056300268096513,
 3322: 0.5370866845397676,
 3323: 0.25350014894250816,
 3325: 0.27822460530235327,
 3326: 0.2237116473041406,
 3357: 0.18468871015787905,
 3358: 0.118558236520703,
 2: 0.07745010425975574,
 26: 0.18826333035448317,
 32: 0.1730711945189157,
 70: 0.3065236818588025,
 91: 0.4769139112302651,
 147: 0.22073279714030383,
 163: 0.3512064343163539,
 186: 0.6797736073875484,
 187: 0.3160560023830801,
 195: 0.29848078641644327,
 202: 0.15370866845397677,
 213: 0.11796246648793565,
 217: 0.34048257372654156,
 246: 0.36044086982424783,
 247: 0.4152517128388442,
 250: 0.3479296991361334,
 251: 0.26899016979445933,
 257: 0.1766458147155198,
 319: 0.16026213881441764,
 320: 0.15668751861781352,
 339: 0.33571641346440273,
 376: 0.2496276437295204,
 394: 0.47065832588620793,
 439: 0.21596663687816503,
 464: 0.2624366994340185,
 483: 0.17634792969913612,
 486: 0.19928507596067918,
 523: 0.3675901102174561,
 533: 0.4462317545427465,
 554: 0.22311587727137325,
 555: 0.13285671730711945,
 595: 0.19451891569854035,
 619: 0.09562109025915996,
 635: 0.09859994042299672,
 706: 0.2963955913017575,
 758: 0.44504021447721176,
 781: 0.15519809353589514,
 785: 0.41495382782246054,
 799: 0.23145665773011617,
 803: 0.24158474828716114,
 806: 0.1423890378313971,
 827: 0.14268692284778076,
 860: 0.3559725945784927,

In [45]:
#2020 most centralized data:
output_mar = node_word(dcentralities,text_march)
output_mar_sorted=sorted(output_mar.items(), reverse = True, key = lambda x:x[1])

In [46]:
#save outputs into pd:
df_central_jan = pd.DataFrame(output_jan_sorted,columns=['word','centrality'])
df_central_mar = pd.DataFrame(output_mar_sorted,columns=['word','centrality'])

In [47]:
df_central_jan['rank'] = df_central_jan['centrality'].rank(ascending=0,method='dense')

In [48]:
df_central_mar['rank'] = df_central_mar['centrality'].rank(ascending=0,method='dense')

In [49]:
df_central_mar[:50]

                                word  centrality  rank
0                               cell    0.823824   1.0
1                            patient    0.812479   2.0
2                               year    0.800300   3.0
3                               case    0.792626   4.0
4                            protein    0.791291   5.0
5               respiratory syndrome    0.673340   6.0
6                               acid    0.666166   7.0
7                         expression    0.651985   8.0
8                           sequence    0.637638   9.0
9                           outbreak    0.628462  10.0
10                         structure    0.615115  11.0
11                             mouse    0.609443  12.0
12  respiratory syndrome coronavirus    0.599933  13.0
13                           pathway    0.594928  14.0
14                           symptom    0.594428  15.0
15                          receptor    0.589256  16.0
16                             china    0.585752  17.0
17                               age    0.581248  18.0
18                             vitro    0.579913  19.0
19                           country    0.574575  20.0
20                             fever    0.563564  21.0
21                               rna    0.559059  22.0
22                             child    0.549716  23.0
23                          mutation    0.539373  24.0
24                               pcr    0.536370  25.0
25                       replication    0.530864  26.0
26                             month    0.530531  27.0
27                               mer    0.530030  28.0
28                           outcome    0.529696  29.0
29                         diagnosis    0.528529  30.0
30                      intervention    0.521522  31.0
31                            genome    0.520187  32.0
32                            domain    0.518018  33.0
33                           illness    0.517684  34.0
34                         pneumonia    0.517351  35.0
35                          molecule    0.510010  36.0
36                           complex    0.503003  37.0
37                              risk    0.500167  38.0
38                        interferon    0.494661  39.0
39                          mers cov    0.491158  40.0
40                          hospital    0.490490  41.0
41                            person    0.489323  42.0
42                             trial    0.485819  43.0
43                         community    0.482649  44.0
44                            health    0.478979  45.0
45                            middle    0.477477  46.0
46                               ifn    0.477144  47.0
47                         inhibitor    0.475809  48.0
48                          membrane    0.475642  49.0
49                         cell line    0.449116  50.0

In [51]:
df_central_jan[:50]

                                word  centrality  rank
0                              virus    0.926125   1.0
1                          procedure    0.924337   2.0
2                        coronavirus    0.919571   3.0
3                          mechanism    0.906166   4.0
4                       complication    0.883527   5.0
5                           practice    0.882633   6.0
6   respiratory syndrome coronavirus    0.879654   7.0
7                               cell    0.837057   8.0
8                        interaction    0.812928   9.0
9                confidence interval    0.806673  10.0
10                           pathway    0.806077  11.0
11                         structure    0.803098  12.0
12                      organization    0.801013  13.0
13                             human    0.800119  14.0
14                         morbidity    0.798034  15.0
15                            tissue    0.790885  16.0
16                           surgery    0.790289  17.0
17              respiratory syndrome    0.785821  18.0
18                           protein    0.784629  19.0
19                            device    0.776586  20.0
20                            animal    0.756628  21.0
21                            target    0.755436  22.0
22                            survey    0.754543  23.0
23                            lesion    0.748585  24.0
24                               min    0.741436  25.0
25            significant difference    0.741138  26.0
26                           vaccine    0.739946  27.0
27                          antibody    0.737265  28.0
28                          pathogen    0.732797  29.0
29                        odds ratio    0.727435  30.0
30                        expression    0.719988  31.0
31                          receptor    0.717009  32.0
32                      inflammation    0.714030  33.0
33                  clinical outcome    0.710158  34.0
34                          property    0.709264  35.0
35                              anti    0.708073  36.0
36                        experiment    0.707179  37.0
37                      hypertension    0.705690  38.0
38                   viral infection    0.704796  39.0
39                              acid    0.704498  40.0
40                            domain    0.704498  40.0
41                 systematic review    0.704498  40.0
42                              gene    0.703604  41.0
43                            median    0.701817  42.0
44                         inhibitor    0.700626  43.0
45                            strain    0.694370  44.0
46                     questionnaire    0.694072  45.0
47                         admission    0.694072  45.0
48                        production    0.693476  46.0
49                              pain    0.687817  47.0

# Second Time Merge

In [87]:
pd_merge = pd.merge(df_central_mar,df_central_jan,on=['word','word']) #x is mar y is jan
pd_merge['change_centrality'] = pd_merge['centrality_y'] - pd_merge['centrality_x']

In [89]:
pd_merge.sort_values('change_centrality')

,word,centrality_x,rank_x,centrality_y,rank_y,change_centrality
38,infected cell,0.407241,64.0,0.296396,527.0,-0.110845
48,virus replication,0.380714,84.0,0.295502,530.0,-0.085212
89,open reading frame,0.308475,146.0,0.227882,734.0,-0.080593
76,mhv,0.326660,128.0,0.248138,670.0,-0.078522
122,pedv,0.269603,189.0,0.197200,832.0,-0.072403
...,...,...,...,...,...,...
342,hypertension,0.167334,444.0,0.705690,38.0,0.538356
70,practice,0.342009,116.0,0.882633,6.0,0.540625
452,pain,0.143810,537.0,0.687817,47.0,0.544006
382,systematic review,0.157991,480.0,0.704498,40.0,0.546507
399,surgery,0.153820,493.0,0.790289,17.0,0.636468

In [52]:
pd_mar_jan = pd.merge(df_central_mar,df_central_jan,on=['word','word'])
pd_mar_jan['change'] = pd_mar_jan['rank_x'] - pd_mar_jan['rank_y']
pd_mar_jan

,word,centrality_x,rank_x,centrality_y,rank_y,change
0,cell,0.823824,1.0,0.837057,8.0,-7.0
1,protein,0.791291,5.0,0.784629,19.0,-14.0
2,respiratory syndrome,0.673340,6.0,0.785821,18.0,-12.0
3,acid,0.666166,7.0,0.704498,40.0,-33.0
4,expression,0.651985,8.0,0.719988,31.0,-23.0
...,...,...,...,...,...,...
1573,essay,0.015015,1275.0,0.136431,1034.0,241.0
1574,tbi,0.014014,1281.0,0.186774,866.0,415.0
1575,challenges opportunity,0.013180,1286.0,0.108728,1127.0,159.0
1576,v v,0.011011,1292.0,0.046470,1275.0,17.0
1577,significance statement,0.002503,1300.0,0.087876,1193.0,107.0

In [53]:
pd_mar_jan.sort_values("change",inplace=True)
pd_mar_jan.loc[(pd_mar_jan['change']>= -50) & (pd_mar_jan['change']<= 50)]

                    word  centrality_x  rank_x  centrality_y  rank_y  change
1044      overexpression      0.063230   986.0      0.136133  1035.0   -49.0
1000           flavonoid      0.066400   967.0      0.142091  1015.0   -48.0
621        incorporation      0.112446   697.0      0.223712   745.0   -48.0
1554               arima      0.022356  1231.0      0.042300  1278.0   -47.0
975           fatal case      0.070070   945.0      0.149240   992.0   -47.0
...                  ...           ...     ...           ...     ...     ...
1083  health information      0.060394  1003.0      0.160262   955.0    48.0
824             markedly      0.085419   853.0      0.205839   804.0    49.0
1275    natural disaster      0.046880  1084.0      0.136133  1035.0    49.0
82                 liver      0.313814   137.0      0.607388    88.0    49.0
1369    nasal congestion      0.039873  1126.0      0.123920  1076.0    50.0

[176 rows x 6 columns]

In [54]:
pd_mar_jan.loc[(pd_mar_jan['change']>= 800)]

,word,centrality_x,rank_x,centrality_y,rank_y,change
1235,identifier,0.049550,1068.0,0.421507,267.0,801.0
1302,magnetic resonance imaging,0.044711,1097.0,0.412273,284.0,813.0
1305,mri,0.044545,1098.0,0.411677,285.0,813.0
1142,scopus,0.056223,1028.0,0.480489,187.0,841.0
1035,body mass index,0.063730,983.0,0.536789,142.0,841.0
1056,sample size,0.062563,990.0,0.532023,146.0,844.0
1202,video,0.052719,1049.0,0.476318,194.0,855.0
1212,social distancing,0.052219,1052.0,0.476616,193.0,859.0
1120,primary outcome,0.058392,1015.0,0.529937,147.0,868.0
1251,consecutive patient,0.048549,1074.0,0.507596,164.0,910.0
1493,mmhg,0.029863,1186.0,0.417635,275.0,911.0
1387,main outcome,0.038205,1136.0,0.462615,210.0,926.0
1270,severe covid,0.047047,1083.0,0.566577,114.0,969.0
1483,sectional study,0.031031,1179.0,0.560024,122.0,1057.0

In [55]:
pd_mar_jan[:50]

,word,centrality_x,rank_x,centrality_y,rank_y,change
122,pedv,0.269603,189.0,0.197200,832.0,-643.0
180,human rhinovirus,0.225392,279.0,0.174561,907.0,-628.0
269,herd,0.186353,375.0,0.148645,994.0,-619.0
149,porcine epidemic diarrhea virus,0.248582,231.0,0.193625,844.0,-613.0
404,bocavirus,0.152152,499.0,0.114090,1109.0,-610.0
145,tgev,0.254755,222.0,0.199881,823.0,-601.0
282,cellular protein,0.181849,391.0,0.150432,988.0,-597.0
146,porcine reproductive respiratory syndrome virus,0.254755,222.0,0.202860,814.0,-592.0
413,nasopharyngeal aspirate,0.149983,507.0,0.117962,1096.0,-589.0
89,open reading frame,0.308475,146.0,0.227882,734.0,-588.0
107,nonstructural protein,0.280113,172.0,0.220137,757.0,-585.0
336,mutant virus,0.167835,441.0,0.139708,1023.0,-582.0
144,prrsv,0.255255,221.0,0.207030,800.0,-579.0
376,positive strand,0.158825,476.0,0.133750,1043.0,-567.0
156,positive sample,0.241742,247.0,0.203455,812.0,-565.0
101,ibv,0.282616,166.0,0.228776,731.0,-565.0
258,hmpv,0.189857,363.0,0.169794,923.0,-560.0
361,vsv,0.161662,465.0,0.139410,1024.0,-559.0
324,parainfluenza,0.170671,429.0,0.150432,988.0,-559.0
143,orf,0.255923,220.0,0.213584,778.0,-558.0
302,capsid protein,0.175509,410.0,0.156688,967.0,-557.0
172,transmissible gastroenteritis virus,0.231231,270.0,0.199583,824.0,-554.0
295,h3n2,0.177845,401.0,0.160560,954.0,-553.0
245,flavivirus,0.194695,348.0,0.177242,898.0,-550.0
278,recombinant virus,0.184351,383.0,0.167709,930.0,-547.0
189,mammalian cell,0.219052,291.0,0.195710,837.0,-546.0
366,dsrna,0.160994,469.0,0.142389,1014.0,-545.0
76,mhv,0.326660,128.0,0.248138,670.0,-542.0
229,vesicular stomatitis virus,0.199032,333.0,0.184987,872.0,-539.0
259,bovine coronavirus,0.189356,364.0,0.176348,901.0,-537.0
349,envelope glycoprotein,0.164998,452.0,0.150432,988.0,-536.0
437,influenza b,0.146980,524.0,0.129282,1058.0,-534.0
114,mouse hepatitis virus,0.277945,178.0,0.234733,711.0,-533.0
417,b virus,0.149149,512.0,0.133155,1045.0,-533.0
459,untranslated region,0.142809,542.0,0.124516,1074.0,-532.0
251,virus entry,0.192860,355.0,0.180816,886.0,-531.0
347,virol,0.165666,450.0,0.152815,980.0,-530.0
247,type i interferon,0.193861,351.0,0.182306,881.0,-530.0
436,human bocavirus,0.146980,524.0,0.131069,1052.0,-528.0
410,recombinant protein,0.150984,504.0,0.137325,1031.0,-527.0
497,utr,0.134635,581.0,0.114686,1107.0,-526.0
375,human immunodeficiency virus type,0.158992,475.0,0.148049,996.0,-521.0
290,streptococcus pneumoniae,0.178679,398.0,0.171582,917.0,-519.0
192,real time rt pcr,0.217384,294.0,0.203753,811.0,-517.0
544,metapneumovirus,0.125125,631.0,0.102770,1147.0,-516.0
160,infectious bronchitis virus,0.236904,255.0,0.216562,768.0,-513.0
292,membrane fusion,0.178178,399.0,0.173667,910.0,-511.0
419,point mutation,0.149149,512.0,0.140006,1022.0,-510.0
134,nucleotide,0.261261,207.0,0.233244,716.0,-509.0
392,murine coronavirus,0.154821,489.0,0.147453,998.0,-509.0

In [56]:
pd_mar_jan['centrality_change'] = pd_mar_jan['centrality_y'] - pd_mar_jan['centrality_x']

In [57]:
pd_mar_jan

,word,centrality_x,rank_x,centrality_y,rank_y,change,centrality_change
122,pedv,0.269603,189.0,0.197200,832.0,-643.0,-0.072403
180,human rhinovirus,0.225392,279.0,0.174561,907.0,-628.0,-0.050831
269,herd,0.186353,375.0,0.148645,994.0,-619.0,-0.037708
149,porcine epidemic diarrhea virus,0.248582,231.0,0.193625,844.0,-613.0,-0.054957
404,bocavirus,0.152152,499.0,0.114090,1109.0,-610.0,-0.038062
...,...,...,...,...,...,...,...
1251,consecutive patient,0.048549,1074.0,0.507596,164.0,910.0,0.459048
1493,mmhg,0.029863,1186.0,0.417635,275.0,911.0,0.387772
1387,main outcome,0.038205,1136.0,0.462615,210.0,926.0,0.424411
1270,severe covid,0.047047,1083.0,0.566577,114.0,969.0,0.519530
1483,sectional study,0.031031,1179.0,0.560024,122.0,1057.0,0.528993

In [58]:
pd_mar_jan.sort_values("centrality_change",inplace=True)
pd_mar_jan[(pd_mar_jan.centrality_change < 0.001) & (pd_mar_jan.centrality_change > -0.01)]

,word,centrality_x,rank_x,centrality_y,rank_y,change,centrality_change
810,a resolution,0.087254,842.0,0.077450,1225.0,-383.0,-0.009804
739,lrti,0.095762,794.0,0.086387,1198.0,-404.0,-0.009376
419,point mutation,0.149149,512.0,0.140006,1022.0,-510.0,-0.009143
433,fip,0.147147,523.0,0.138517,1027.0,-504.0,-0.008631
171,fusion protein,0.231565,268.0,0.223116,747.0,-479.0,-0.008449
825,dub,0.085419,853.0,0.077748,1224.0,-371.0,-0.007671
140,sequence analysis,0.259259,214.0,0.251713,661.0,-447.0,-0.007546
469,ili,0.140974,552.0,0.133452,1044.0,-492.0,-0.007522
392,murine coronavirus,0.154821,489.0,0.147453,998.0,-509.0,-0.007368
655,influenza b virus,0.107608,724.0,0.100387,1155.0,-431.0,-0.007220
183,cytopathic effect,0.223724,282.0,0.216562,768.0,-486.0,-0.007161
290,streptococcus pneumoniae,0.178679,398.0,0.171582,917.0,-519.0,-0.007097
374,vlp,0.158992,475.0,0.152219,982.0,-507.0,-0.006773
1,protein,0.791291,5.0,0.784629,19.0,-14.0,-0.006662
327,cdna,0.169837,433.0,0.164135,942.0,-509.0,-0.005702
458,virus isolation,0.143143,540.0,0.137623,1030.0,-490.0,-0.005520
154,parainfluenza virus,0.243410,243.0,0.238010,700.0,-457.0,-0.005400
1018,prise,0.064898,976.0,0.059577,1262.0,-286.0,-0.005321
672,eav,0.104104,745.0,0.099196,1159.0,-414.0,-0.004908
694,bcov,0.101101,763.0,0.096217,1169.0,-406.0,-0.004884
292,membrane fusion,0.178178,399.0,0.173667,910.0,-511.0,-0.004511
328,fecal sample,0.169837,433.0,0.165624,937.0,-504.0,-0.004212
68,wild type,0.345846,114.0,0.341972,417.0,-303.0,-0.003874
398,rig,0.153820,493.0,0.150730,987.0,-494.0,-0.003091
585,fcov,0.118619,666.0,0.115579,1104.0,-438.0,-0.003039
648,wnv,0.108609,718.0,0.106047,1136.0,-418.0,-0.002562
268,small interfering rna,0.187354,373.0,0.184987,872.0,-499.0,-0.002367
405,rsv infection,0.152152,499.0,0.149836,990.0,-491.0,-0.002316
418,isg,0.149149,512.0,0.146857,1000.0,-488.0,-0.002292
248,hrv,0.193694,352.0,0.191540,851.0,-499.0,-0.002154
274,polyprotein,0.185519,379.0,0.183795,876.0,-497.0,-0.001724
522,ndv,0.129963,605.0,0.128388,1061.0,-456.0,-0.001575
443,genomic rna,0.145646,530.0,0.144176,1008.0,-478.0,-0.001469
367,retrovirus,0.160827,470.0,0.159368,958.0,-488.0,-0.001459
322,denv,0.171672,425.0,0.170390,921.0,-496.0,-0.001281
453,ebov,0.143644,538.0,0.142687,1013.0,-475.0,-0.000957
81,epitope,0.317818,135.0,0.316950,473.0,-338.0,-0.000868
147,cattle,0.250417,229.0,0.249628,667.0,-438.0,-0.000789
409,feline coronavirus,0.151151,503.0,0.150432,988.0,-485.0,-0.000719
44,glycoprotein,0.384218,79.0,0.383676,329.0,-250.0,-0.000542
663,mouth disease virus,0.105939,734.0,0.105749,1137.0,-403.0,-0.000190
197,virus particle,0.215716,298.0,0.215669,771.0,-473.0,-0.000047
681,npa,0.102936,752.0,0.103068,1146.0,-394.0,0.000132
360,vaccinia virus,0.161828,464.0,0.162049,949.0,-485.0,0.000221
165,sirna,0.236236,258.0,0.236521,705.0,-447.0,0.000284
155,cytoplasm,0.242910,245.0,0.243372,685.0,-440.0,0.000462

In [107]:
pd_mar_jan[pd_mar_jan['word']=='covid19']

Empty DataFrame
Columns: [word, centrality_x, rank_x, centrality_y, rank_y, change]
Index: []

In [59]:
cen_diff = {}
for i in df_central_mar[:50].word:
    word = i
    central_jan = df_central_mar[:50][df_central_jan.word==i]
    if central_jan.items():
        print(central_jan.centrality)
        print(i)

7    0.651985
Name: centrality, dtype: float64
cell
Series([], Name: centrality, dtype: float64)
patient
Series([], Name: centrality, dtype: float64)
year
Series([], Name: centrality, dtype: float64)
case
18    0.579913
Name: centrality, dtype: float64
protein
17    0.581248
Name: centrality, dtype: float64
respiratory syndrome
39    0.491158
Name: centrality, dtype: float64
acid
30    0.521522
Name: centrality, dtype: float64
expression
Series([], Name: centrality, dtype: float64)
sequence
Series([], Name: centrality, dtype: float64)
outbreak
11    0.609443
Name: centrality, dtype: float64
structure
Series([], Name: centrality, dtype: float64)
mouse
6    0.666166
Name: centrality, dtype: float64
respiratory syndrome coronavirus
10    0.615115
Name: centrality, dtype: float64
pathway
Series([], Name: centrality, dtype: float64)
symptom
31    0.520187
Name: centrality, dtype: float64
receptor
Series([], Name: centrality, dtype: float64)
china
Series([], Name: centrality, dtype: float64)
age
Series([], Name: centrality, dtype: float64)
vitro
Series([], Name: centrality, dtype: float64)
country
Series([], Name: centrality, dtype: float64)
fever
Series([], Name: centrality, dtype: float64)
rna
Series([], Name: centrality, dtype: float64)
child
Series([], Name: centrality, dtype: float64)
mutation
Series([], Name: centrality, dtype: float64)
pcr
Series([], Name: centrality, dtype: float64)
replication
Series([], Name: centrality, dtype: float64)
month
Series([], Name: centrality, dtype: float64)
mer
Series([], Name: centrality, dtype: float64)
outcome
Series([], Name: centrality, dtype: float64)
diagnosis
Series([], Name: centrality, dtype: float64)
intervention
Series([], Name: centrality, dtype: float64)
genome
40    0.49049
Name: centrality, dtype: float64
domain
Series([], Name: centrality, dtype: float64)
illness
Series([], Name: centrality, dtype: float64)
pneumonia
Series([], Name: centrality, dtype: float64)
molecule
Series([], Name: centrality, dtype: float64)
complex
Series([], Name: centrality, dtype: float64)
risk
Series([], Name: centrality, dtype: float64)
interferon
Series([], Name: centrality, dtype: float64)
mers cov
Series([], Name: centrality, dtype: float64)
hospital
Series([], Name: centrality, dtype: float64)
person
Series([], Name: centrality, dtype: float64)
trial
Series([], Name: centrality, dtype: float64)
community
Series([], Name: centrality, dtype: float64)
health
Series([], Name: centrality, dtype: float64)
middle
Series([], Name: centrality, dtype: float64)
ifn
44    0.478979
Name: centrality, dtype: float64
inhibitor
Series([], Name: centrality, dtype: float64)
membrane
Series([], Name: centrality, dtype: float64)
cell line

<ipython-input-59-3db72acd2671>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  central_jan = df_central_mar[:50][df_central_jan.word==i]

In [64]:
pd_mar_jan.sort_values('centrality_change')[:20]

,word,centrality_x,rank_x,centrality_y,rank_y,change,centrality_change
38,infected cell,0.407241,64.0,0.296396,527.0,-463.0,-0.110845
48,virus replication,0.380714,84.0,0.295502,530.0,-446.0,-0.085212
89,open reading frame,0.308475,146.0,0.227882,734.0,-588.0,-0.080593
76,mhv,0.326660,128.0,0.248138,670.0,-542.0,-0.078522
122,pedv,0.269603,189.0,0.197200,832.0,-643.0,-0.072403
69,virion,0.344511,115.0,0.277629,584.0,-469.0,-0.066882
62,viral protein,0.352186,106.0,0.289246,549.0,-443.0,-0.062939
24,ifn,0.477144,47.0,0.415550,278.0,-231.0,-0.061594
17,genome,0.520187,32.0,0.458743,211.0,-179.0,-0.061444
107,nonstructural protein,0.280113,172.0,0.220137,757.0,-585.0,-0.059976
15,replication,0.530864,26.0,0.473637,200.0,-174.0,-0.057227
149,porcine epidemic diarrhea virus,0.248582,231.0,0.193625,844.0,-613.0,-0.054957
145,tgev,0.254755,222.0,0.199881,823.0,-601.0,-0.054874
101,ibv,0.282616,166.0,0.228776,731.0,-565.0,-0.053840
146,porcine reproductive respiratory syndrome virus,0.254755,222.0,0.202860,814.0,-592.0,-0.051895
180,human rhinovirus,0.225392,279.0,0.174561,907.0,-628.0,-0.050831
67,mutant,0.346847,113.0,0.296098,528.0,-415.0,-0.050749
40,residue,0.403237,70.0,0.353590,387.0,-317.0,-0.049647
144,prrsv,0.255255,221.0,0.207030,800.0,-579.0,-0.048225
90,phylogenetic analysis,0.307474,147.0,0.260054,635.0,-488.0,-0.047421